// Generated by @bwp-web/codegen from packages/codegen/src/components/agenda-row.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { meta, playground, variants } from './solar.js';

// Storybook reads a story file statically, so the default export is an object literal here.
export default {
  title: 'SOLAR/Agenda Row',
  ...meta('Agenda Row'),
} satisfies Meta;
export const Playground: StoryObj = playground('Agenda Row');
export const Variants: StoryObj = variants('Agenda Row');
