// Generated by @bwp-web/codegen from packages/codegen/src/components/bar-stack.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { meta, playground, variants } from './solar.js';

// Storybook reads a story file statically, so the default export is an object literal here.
export default {
  title: 'SOLAR/Bar Stack',
  ...meta('Bar Stack'),
} satisfies Meta;
export const Playground: StoryObj = playground('Bar Stack');
export const Variants: StoryObj = variants('Bar Stack');
