// Generated by @bwp-web/codegen from packages/codegen/src/components/button-group.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { meta, playground, variants } from './solar.js';

// Storybook reads a story file statically, so the default export is an object literal here.
export default {
  title: 'SOLAR/Button Group',
  ...meta('Button Group'),
} satisfies Meta;
export const Playground: StoryObj = playground('Button Group');
export const Variants: StoryObj = variants('Button Group');
