// Generated by @bwp-web/codegen from packages/codegen/src/components/column-item.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { meta, playground, variants } from './solar.js';

// Storybook reads a story file statically, so the default export is an object literal here.
export default {
  title: 'SOLAR/Column Item',
  ...meta('Column Item'),
} satisfies Meta;
export const Playground: StoryObj = playground('Column Item');
export const Variants: StoryObj = variants('Column Item');
