// Generated by @bwp-web/codegen from packages/codegen/src/components/data-legend.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { meta, playground, variants } from './solar.js';

// Storybook reads a story file statically, so the default export is an object literal here.
export default {
  title: 'SOLAR/Data Legend',
  ...meta('Data Legend'),
} satisfies Meta;
export const Playground: StoryObj = playground('Data Legend');
export const Variants: StoryObj = variants('Data Legend');
