// Generated by @bwp-web/codegen from packages/codegen/src/components/device-card.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { meta, playground, variants } from './solar.js';

// Storybook reads a story file statically, so the default export is an object literal here.
export default {
  title: 'SOLAR/Device Card',
  ...meta('Device Card'),
} satisfies Meta;
export const Playground: StoryObj = playground('Device Card');
export const Variants: StoryObj = variants('Device Card');
