// Generated by @bwp-web/codegen from packages/codegen/src/components/dropdown-group-label.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { meta, playground, variants } from './solar.js';

// Storybook reads a story file statically, so the default export is an object literal here.
export default {
  title: 'SOLAR/Dropdown Group Label',
  ...meta('Dropdown Group Label'),
} satisfies Meta;
export const Playground: StoryObj = playground('Dropdown Group Label');
export const Variants: StoryObj = variants('Dropdown Group Label');
