// Generated by @bwp-web/codegen from packages/codegen/src/components/insight-card-small.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { meta, playground, variants } from './solar.js';

// Storybook reads a story file statically, so the default export is an object literal here.
export default {
  title: 'SOLAR/Insight Card Small',
  ...meta('Insight Card Small'),
} satisfies Meta;
export const Playground: StoryObj = playground('Insight Card Small');
export const Variants: StoryObj = variants('Insight Card Small');
