// Generated by @bwp-web/codegen from packages/codegen/src/components/launch-card-full-screen.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { meta, playground, variants } from './solar.js';

// Storybook reads a story file statically, so the default export is an object literal here.
export default {
  title: 'SOLAR/Launch Card Full Screen',
  ...meta('Launch Card Full Screen'),
} satisfies Meta;
export const Playground: StoryObj = playground('Launch Card Full Screen');
export const Variants: StoryObj = variants('Launch Card Full Screen');
