// Generated by @bwp-web/codegen from packages/codegen/src/components/section-nav-item.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { meta, playground, variants } from './solar.js';

// Storybook reads a story file statically, so the default export is an object literal here.
export default {
  title: 'SOLAR/Section Nav Item',
  ...meta('Section Nav Item'),
} satisfies Meta;
export const Playground: StoryObj = playground('Section Nav Item');
export const Variants: StoryObj = variants('Section Nav Item');
