// Generated by @bwp-web/codegen from packages/codegen/src/components/time-axis-label.mjs. Do not edit.
import type { Meta, StoryObj } from '@storybook/react-vite';
import { meta, playground, variants } from './solar.js';

// Storybook reads a story file statically, so the default export is an object literal here.
export default {
  title: 'SOLAR/Time Axis Label',
  ...meta('Time Axis Label'),
} satisfies Meta;
export const Playground: StoryObj = playground('Time Axis Label');
export const Variants: StoryObj = variants('Time Axis Label');
