import { join } from 'node:path';
import { specDir } from '../util/paths.mjs';
import { writeGenerated } from '../util/write.mjs';
import { byCodeUnit } from '../util/sort.mjs';

const cell = (value) => String(value).replaceAll('|', '\\|');

/**
 * Renders the governance report as markdown. Kept separate from the write so it can be
 * asserted on without touching spec/.
 */
export function renderDeviations(deviations, fileVersion) {
  // Dedupe by token: today every rule fires at most once per token, but a future rule that
  // fires twice would otherwise silently double a row.
  const unique = [
    ...new Map(deviations.map((d) => [d.token, d])).values(),
  ].sort((a, b) => byCodeUnit(a.token, b.token));
  const rows = unique
    .map(
      (d) =>
        `| \`${d.token}\` | ${cell(d.figmaValue)} | ${cell(d.reason)} | ${cell(d.raise ?? 'no action')} |`,
    )
    .join('\n');
  return (
    `# SOLAR code deviations from Figma\n\n` +
    `Generated by \`npm run solar:codegen\` from \`spec/tokens.json\` and \`spec/icons.json\`. ` +
    `Foundations Figma file version \`${fileVersion}\`; the \`icon.*\` and \`logo.*\` rows come from the ` +
    `SOLAR Icons file, whose version is recorded in \`spec/icons.json\`.\n\n` +
    `Each row is a place where the generated code deliberately differs from what the Figma data says.\n` +
    `The mirror in \`docs/\` is never edited to accommodate these; take them to SOLAR governance.\n\n` +
    (unique.length
      ? `| Token | Figma value | Why we differ | Action |\n| --- | --- | --- | --- |\n${rows}\n`
      : `No deviations.\n`)
  );
}

export function writeDeviationsReport(deviations, fileVersion) {
  return writeGenerated(
    join(specDir, 'deviations.md'),
    renderDeviations(deviations, fileVersion),
  );
}
