// Generated by @bwp-web/codegen from packages/codegen/src/components/. Do not edit.
// How each generated widget is built in one oracle variant, by its name (see builders.dart).

import 'builders.dart';
import 'button.dart';
import 'button_group.dart';
import 'icon_button.dart';
import 'spinner.dart';
import 'statusindicator.dart';

const builders = <String, VariantBuilder>{
  'Button': buildButton,
  'Button Group': buildButtonGroup,
  'Icon Button': buildIconButton,
  'Spinner': buildSpinner,
  'StatusIndicator': buildStatusIndicator,
};
