// Generated by @bwp-web/codegen from packages/codegen/src/components/action-card.mjs. Do not edit.
/**
 * SOLAR Action Card.
 *
 * Generated from its template in `packages/codegen/src/components/` on every `npm run
 * solar:codegen`: change the template there, never this file. What it looks like is not here. That
 * is the recipe, `solarActionCardStyle` and `solarActionCardCompose` in `@bwp-web/styles/mui`: the
 * surface’s fill, edge, shadow and focus ring by status and state, its words’ and icons’ ink.
 *
 * A card that asks for one thing (set up a room, fix a fault): an `icon` and its `title`, a More
 * menu of `moreItems`, the content (the `description`, in Figma's words' look, then the caller's
 * children), and its calls to action, the caller's SOLAR Buttons (sm, as Figma draws them): the
 * `primaryAction` and `secondaryAction` at rest, the primary alone once `done` (secondary) or in
 * `danger` (a danger primary). Given `onClick` or `href`, it is pressable: its title is the button
 * or link, and its hit area the whole card, its Buttons and the More menu reachable above it; it is
 * hovered and focused only then. Drawn from Figma's layer tree (`internal/layers.tsx`). The app
 * must load `@bwp-web/styles/tokens.css`.
 */

import { useSolarProps } from './internal/theme.js';
import Box, { type BoxProps } from '@mui/material/Box';
import ButtonBase from '@mui/material/ButtonBase';
import { IconMore } from '@bwp-web/assets';
import {
  forwardRef,
  useRef,
  useState,
  type MouseEvent,
  type ReactNode,
} from 'react';
import {
  solarActionCardCompose,
  solarActionCardStyle,
  type SolarActionCardProps,
} from '@bwp-web/styles/mui';
import type { CardMoreItem } from './Card.js';
import { DropdownItem } from './DropdownItem.js';
import { DropdownMenu } from './DropdownMenu.js';
import { drawChildren, type DrawnLayer } from './internal/layers.js';

/** Each layer's children, as Figma nests them. */
const TREE: Record<string, string[]> = {
  root: ['title', 'content', 'cta', 'button'],
  title: ['icon', 'titleTitle', 'iconMore'],
  content: ['description'],
  cta: ['primaryCTA', 'secondaryCTA'],
};
const SLOTS: Record<string, string> = {
  icon: 'icon',
  content: 'content',
  cta: 'cta',
  primaryCTA: 'primaryCTA',
  secondaryCTA: 'secondaryCTA',
  titleTitle: 'title',
  description: 'description',
};

export interface ActionCardProps
  extends
    SolarActionCardProps,
    // MUI types BoxProps' ref for any element; the component's own, a <div>, comes from forwardRef.
    Omit<
      BoxProps,
      | keyof SolarActionCardProps
      | 'title'
      | 'icon'
      | 'description'
      | 'children'
      | 'primaryAction'
      | 'secondaryAction'
      | 'onClick'
      | 'ref'
    > {
  /** What it asks for, in a few words; its action’s name where it is pressable. */
  title: ReactNode;
  /** An icon before the title. */
  icon?: ReactNode;
  /** The content’s words, in the look Figma draws them. */
  description?: ReactNode;
  /** The caller’s content, after the description. */
  children?: ReactNode;
  /** The call to action: a SOLAR Button, sm; once done or in danger, the only one. */
  primaryAction?: ReactNode;
  /** Another at rest, beside it: a SOLAR Button, sm and secondary. */
  secondaryAction?: ReactNode;
  /** The More menu's actions: a button opens them. */
  moreItems?: CardMoreItem[];
  /** The More button's accessible name. */
  moreLabel?: string;
  /** Makes it pressable: its title is a button that calls it. */
  onClick?: (event: MouseEvent<HTMLElement>) => void;
  /** Makes it pressable: its title is a link here. */
  href?: string;
}

export const ActionCard = forwardRef<HTMLDivElement, ActionCardProps>(
  function ActionCard(inProps, ref) {
    // As the app's MUI theme sets them (components.SolarActionCard), under the caller's own.
    const {
      status = 'default',
      title,
      icon,
      description,
      children,
      primaryAction,
      secondaryAction,
      moreItems,
      moreLabel = 'More actions',
      onClick,
      href,
      className,
      sx,
      ...rest
    } = useSolarProps(inProps, 'SolarActionCard');
    const look = { status };
    const composed = solarActionCardCompose(look);
    const pressable = onClick != null || href != null;
    const menu = moreItems != null && moreItems.length > 0;
    // A slot left empty is not drawn.
    const parts = {
      ...composed,
      icon: {
        ...composed.icon,
        present: composed.icon?.present !== false && icon != null,
      },
      description: {
        ...composed.description,
        present: composed.description?.present !== false && description != null,
      },
      primaryCTA: {
        ...composed.primaryCTA,
        present:
          composed.primaryCTA?.present !== false && primaryAction != null,
      },
      button: {
        ...composed.button,
        present: composed.button?.present !== false && primaryAction != null,
      },
      secondaryCTA: {
        ...composed.secondaryCTA,
        present:
          composed.secondaryCTA?.present !== false && secondaryAction != null,
      },
      iconMore: {
        ...composed.iconMore,
        present: composed.iconMore?.present !== false && menu,
      },
    };
    const [open, setOpen] = useState(false);
    const moreRef = useRef<HTMLButtonElement>(null);
    // Pressable, its title is its action, stretched over the card.
    const titled = pressable ? (
      <ButtonBase
        className="SolarActionCard-press"
        disableRipple
        {...(href != null ? { href } : {})}
        onClick={onClick}
      >
        {title}
      </ButtonBase>
    ) : (
      title
    );
    return (
      <>
        <Box
          ref={ref}
          className={
            [pressable ? 'SolarActionCard-pressable' : null, className]
              .filter(Boolean)
              .join(' ') || undefined
          }
          {...rest}
          sx={[solarActionCardStyle(look), ...(Array.isArray(sx) ? sx : [sx])]}
        >
          {drawChildren('root', {
            prefix: 'SolarActionCard',
            tree: TREE,
            slots: SLOTS,
            parts,
            text: { titleTitle: titled, description },
            icons: {
              icon: <span>{icon}</span>,
              primaryCTA: <span>{primaryAction}</span>,
              button: <span>{primaryAction}</span>,
              secondaryCTA: <span>{secondaryAction}</span>,
              iconMore: (
                <ButtonBase
                  ref={moreRef}
                  disableRipple
                  disabled={false}
                  aria-label={moreLabel}
                  aria-haspopup="menu"
                  aria-expanded={open}
                  onClick={() => setOpen(true)}
                >
                  <IconMore />
                </ButtonBase>
              ),
            },
            render: {
              // The content: Figma's description, then the caller's children.
              content: ({
                className: c,
                style,
                children: drawn,
              }: DrawnLayer) => (
                <div className={c} style={style}>
                  {drawn}
                  {children}
                </div>
              ),
            },
          })}
        </Box>
        {menu ? (
          <DropdownMenu
            anchorEl={moreRef.current}
            open={open}
            onClose={() => setOpen(false)}
          >
            {moreItems.map((item, i) => (
              <DropdownItem
                key={i}
                disabled={item.disabled}
                icon={item.icon}
                onClick={() => {
                  setOpen(false);
                  item.onSelect();
                }}
              >
                {item.label}
              </DropdownItem>
            ))}
          </DropdownMenu>
        ) : null}
      </>
    );
  },
);
