// Generated by @bwp-web/codegen from packages/codegen/src/components/breadcrumb-item.mjs. Do not edit.
/**
 * SOLAR Breadcrumb Item.
 *
 * Generated from its template in `packages/codegen/src/components/` on every `npm run
 * solar:codegen`: change the template there, never this file. What it looks like is not here. That
 * is the recipe, `solarBreadcrumbItemStyle` and `solarBreadcrumbItemCompose` in
 * `@bwp-web/styles/mui`: its words’ text style and ink by state.
 *
 * Bespoke: one segment of a Breadcrumbs trail, drawn from Figma's layer tree
 * (`internal/layers.tsx`). A link to an ancestor page where it has an `href` (a button, given
 * `onClick` alone); the `current` page, the trail's last, as text announced as the current page, no
 * link, as its description says; a `disabled` one as text. A focused link draws SOLAR's focus ring.
 * Its words are its children. Use it inside Breadcrumbs. The app must load
 * `@bwp-web/styles/tokens.css`.
 */

import { useSolarProps } from './internal/theme.js';
import Box, { type BoxProps } from '@mui/material/Box';
import { forwardRef, type MouseEventHandler, type ReactNode } from 'react';
import {
  solarBreadcrumbItemCompose,
  solarBreadcrumbItemStyle,
  type SolarBreadcrumbItemProps,
} from '@bwp-web/styles/mui';
import { drawChildren } from './internal/layers.js';

/** Each layer's children, as Figma nests them. */
const TREE: Record<string, string[]> = { root: ['label'] };
const SLOTS: Record<string, string> = {};

export interface BreadcrumbItemProps
  extends
    SolarBreadcrumbItemProps,
    // MUI types BoxProps' ref for any element; the component's own comes from forwardRef.
    Omit<
      BoxProps,
      keyof SolarBreadcrumbItemProps | 'children' | 'ref' | 'onClick'
    > {
  /** The page's name. */
  children: ReactNode;
  /** Where it goes: it is a link. */
  href?: string;
  /** Called when it is chosen, where it has no `href`: it is a button. */
  onClick?: MouseEventHandler<HTMLElement>;
}

export const BreadcrumbItem = forwardRef<HTMLElement, BreadcrumbItemProps>(
  function BreadcrumbItem(inProps, ref) {
    // As the app's MUI theme sets them (components.SolarBreadcrumbItem), under the caller's own.
    const { type, disabled, children, href, onClick, className, sx, ...rest } =
      useSolarProps(inProps, 'SolarBreadcrumbItem');
    // A link, a button, or the words alone: the current page, and a disabled link, are no control.
    const current = type === 'current';
    const control = !current && !disabled;
    const as = !control ? 'span' : href !== undefined ? 'a' : 'button';
    const parts = solarBreadcrumbItemCompose({ type, disabled });
    return (
      <Box
        component={as}
        ref={ref}
        href={as === 'a' ? href : undefined}
        type={as === 'button' ? 'button' : undefined}
        onClick={control ? onClick : undefined}
        aria-current={current ? 'page' : undefined}
        aria-disabled={disabled || undefined}
        className={
          [disabled ? 'SolarBreadcrumbItem-disabled' : null, className]
            .filter(Boolean)
            .join(' ') || undefined
        }
        {...rest}
        sx={[
          solarBreadcrumbItemStyle({ type, disabled }),
          ...(Array.isArray(sx) ? sx : [sx]),
        ]}
      >
        {drawChildren('root', {
          prefix: 'SolarBreadcrumbItem',
          tree: TREE,
          slots: SLOTS,
          parts,
          text: { label: children },
        })}
      </Box>
    );
  },
);
