// Generated by @bwp-web/codegen from packages/codegen/src/components/card.mjs. Do not edit.
/**
 * SOLAR Card.
 *
 * Generated from its template in `packages/codegen/src/components/` on every `npm run
 * solar:codegen`: change the template there, never this file. What it looks like is not here. That
 * is the recipe, `solarCardStyle` and `solarCardCompose` in `@bwp-web/styles/mui`: the surface’s
 * fill, edge, shadow and focus ring by status and state, its words’ and icons’ ink, the Tag it
 * shows, and the placeholders.
 *
 * The raised surface of the card family, for a titled piece of content: its `title`, an `icon`
 * before it and a `helper` after it, the content (the `description`, in Figma's words' look, then
 * the caller's children), a `tag` (a SOLAR Tag's words, in the status's look), and a More menu of
 * `moreItems`. Given `onClick` or `href`, it is pressable: its title is the button or link, named
 * by its words, and its hit area the whole card, so the More menu and the content's own controls
 * stay reachable above it; it is hovered and focused only then. `loading` draws Figma's
 * placeholders, announced busy. For a whole-surface action with a call to action use an Action
 * Card; for a grouping inside a larger surface, a Container. Drawn from Figma's layer tree
 * (`internal/layers.tsx`). The app must load `@bwp-web/styles/tokens.css`.
 */

import { useSolarProps } from './internal/theme.js';
import Box, { type BoxProps } from '@mui/material/Box';
import ButtonBase from '@mui/material/ButtonBase';
import { IconMore } from '@bwp-web/assets';
import {
  forwardRef,
  useRef,
  useState,
  type MouseEvent,
  type ReactNode,
} from 'react';
import {
  solarCardCompose,
  solarCardStyle,
  type SolarCardProps,
} from '@bwp-web/styles/mui';
import { DropdownItem } from './DropdownItem.js';
import { DropdownMenu } from './DropdownMenu.js';
import { drawChildren, type DrawnLayer } from './internal/layers.js';
import { Tag, type TagProps } from './Tag.js';

/** One action of a card's More menu. */
export interface CardMoreItem {
  /** Its words. */
  label: ReactNode;
  /** Called when it is chosen; the menu closes first. */
  onSelect: () => void;
  disabled?: boolean;
  /** An icon before its words. */
  icon?: ReactNode;
}

/** Each layer's children, as Figma nests them. */
const TREE: Record<string, string[]> = {
  root: ['title', 'skeleton', 'content', 'tag'],
  title: ['icon', 'titleTitle', 'helper', 'more'],
  content: [
    'description',
    'contentSkeleton',
    'contentSkeleton2',
    'contentSkeleton3',
  ],
};
const SLOTS: Record<string, string> = {
  icon: 'icon',
  titleTitle: 'title',
  helper: 'helper',
  more: 'more',
  content: 'content',
  tag: 'tag',
};

export interface CardProps
  extends
    SolarCardProps,
    // MUI types BoxProps' ref for any element; the component's own, a <div>, comes from forwardRef.
    Omit<
      BoxProps,
      | keyof SolarCardProps
      | 'title'
      | 'icon'
      | 'helper'
      | 'description'
      | 'children'
      | 'tag'
      | 'onClick'
      | 'ref'
    > {
  /** What the card is, in a few words; its action’s name where it is pressable. */
  title: ReactNode;
  /** An icon before the title. */
  icon?: ReactNode;
  /** A word after the title (a count, a date). */
  helper?: ReactNode;
  /** The content’s words, in the look Figma draws them. */
  description?: ReactNode;
  /** The caller’s content, after the description. */
  children?: ReactNode;
  /** A SOLAR Tag’s words, drawn in the status’s look. */
  tag?: ReactNode;
  /** The More menu's actions: a button opens them. */
  moreItems?: CardMoreItem[];
  /** The More button's accessible name. */
  moreLabel?: string;
  /** Makes it pressable: its title is a button that calls it. */
  onClick?: (event: MouseEvent<HTMLElement>) => void;
  /** Makes it pressable: its title is a link here. */
  href?: string;
}

export const Card = forwardRef<HTMLDivElement, CardProps>(
  function Card(inProps, ref) {
    // As the app's MUI theme sets them (components.SolarCard), under the caller's own.
    const {
      disabled = false,
      status = 'none',
      loading = false,
      title,
      icon,
      helper,
      description,
      children,
      tag,
      moreItems,
      moreLabel = 'More actions',
      onClick,
      href,
      className,
      sx,
      ...rest
    } = useSolarProps(inProps, 'SolarCard');
    // Figma draws a loading card, and a disabled one, with no status: its look is the same for all.
    const look = {
      disabled,
      status: loading || disabled ? ('none' as const) : status,
      loading,
    };
    const composed = solarCardCompose(look);
    // Pressable while it loads too, as Figma draws a loading card hovered: its title, the action,
    // is then its name alone.
    const pressable = (onClick != null || href != null) && !disabled;
    const menu = moreItems != null && moreItems.length > 0;
    const t = composed.tag;
    // A slot left empty is not drawn, and one Figma hides at rest is drawn where it is given.
    const parts = {
      ...composed,
      icon: { ...composed.icon, present: icon != null },
      helper: { ...composed.helper, present: helper != null },
      description: {
        ...composed.description,
        present: composed.description?.present !== false && description != null,
      },
      tag: {
        ...composed.tag,
        present: composed.tag?.present !== false && tag != null,
      },
      more: {
        ...composed.more,
        present: composed.more?.present !== false && menu,
      },
    };
    const [open, setOpen] = useState(false);
    const moreRef = useRef<HTMLButtonElement>(null);
    // Pressable, its title is its action, stretched over the card.
    const titled = pressable ? (
      <ButtonBase
        className="SolarCard-press"
        disableRipple
        {...(href != null ? { href } : {})}
        onClick={onClick}
      >
        {title}
      </ButtonBase>
    ) : (
      title
    );
    // Loading, where its title is not drawn (Card's; a Device Card's is), the action is drawn in
    // its place, its name alone.
    const waiting =
      pressable &&
      loading &&
      !['titleTitle'].some((l) => composed[l]?.present !== false) ? (
        <ButtonBase
          className="SolarCard-press"
          disableRipple
          {...(href != null ? { href } : {})}
          onClick={onClick}
        >
          <span className="SolarCard-name">{title}</span>
        </ButtonBase>
      ) : null;
    return (
      <>
        <Box
          ref={ref}
          aria-busy={loading || undefined}
          aria-disabled={disabled || undefined}
          className={
            [
              pressable ? 'SolarCard-pressable' : null,
              disabled ? 'SolarCard-disabled' : null,
              className,
            ]
              .filter(Boolean)
              .join(' ') || undefined
          }
          {...rest}
          sx={[solarCardStyle(look), ...(Array.isArray(sx) ? sx : [sx])]}
        >
          {waiting}
          {drawChildren('root', {
            prefix: 'SolarCard',
            tree: TREE,
            slots: SLOTS,
            parts,
            text: { titleTitle: titled, helper, description },
            icons: {
              icon: <span>{icon}</span>,
              more: (
                <ButtonBase
                  ref={moreRef}
                  disableRipple
                  disabled={disabled}
                  aria-label={moreLabel}
                  aria-haspopup="menu"
                  aria-expanded={open}
                  onClick={() => setOpen(true)}
                >
                  <IconMore />
                </ButtonBase>
              ),
            },
            render: {
              // The content: Figma's description (or, loading, its placeholder lines), then the caller's
              // children.
              content: ({
                className: c,
                style,
                children: drawn,
              }: DrawnLayer) => (
                <div className={c} style={style}>
                  {drawn}
                  {loading ? null : children}
                </div>
              ),
              // A SOLAR Tag, in the variant the recipe names, in its layer's element; loading, it is the
              // Tag's placeholder, its words hidden and keeping their room, on the fill the recipe draws it on.
              tag: ({ className: c, style }: DrawnLayer) => (
                <span
                  className={c}
                  style={style}
                  aria-hidden={loading || undefined}
                >
                  <Tag
                    status={t['variant.status'] as TagProps['status']}
                    {...(t['variant.invert'] === 'true'
                      ? { invert: true as const }
                      : {})}
                  >
                    {loading ? (
                      <span style={{ visibility: 'hidden' }}>{tag}</span>
                    ) : (
                      tag
                    )}
                  </Tag>
                </span>
              ),
            },
          })}
        </Box>
        {menu ? (
          <DropdownMenu
            anchorEl={moreRef.current}
            open={open}
            onClose={() => setOpen(false)}
          >
            {moreItems.map((item, i) => (
              <DropdownItem
                key={i}
                disabled={item.disabled}
                icon={item.icon}
                onClick={() => {
                  setOpen(false);
                  item.onSelect();
                }}
              >
                {item.label}
              </DropdownItem>
            ))}
          </DropdownMenu>
        ) : null}
      </>
    );
  },
);
