// Generated by @bwp-web/codegen from packages/codegen/src/components/context-menu-item.mjs. Do not edit.
/**
 * SOLAR Context Menu Item.
 *
 * Generated from its template in `packages/codegen/src/components/` on every `npm run
 * solar:codegen`: change the template there, never this file. What it looks like is not here. That
 * is the recipe, `solarContextMenuItemStyle` and `solarContextMenuItemCompose` in
 * `@bwp-web/styles/mui`: the row's fill by state, and its words', shortcut's and icons' ink,
 * destructive or not.
 *
 * One action of a ContextMenu: MUI's MenuItem, so the menu moves the focus from row to row with
 * the arrow keys, and a focused row draws Figma's focus. Its words, an icon either side and a
 * keyboard `shortcut` after them are drawn from Figma's layer tree (`internal/layers.tsx`).
 * `destructive` is for an action that cannot be undone (Delete), and only that, as SOLAR says. No
 * submenus: one level. The app must load `@bwp-web/styles/tokens.css`.
 */

import { useSolarProps } from './internal/theme.js';
import MenuItem, { type MenuItemProps } from '@mui/material/MenuItem';
import { forwardRef, type ReactNode } from 'react';
import {
  solarContextMenuItemCompose,
  solarContextMenuItemStyle,
  type SolarContextMenuItemProps,
} from '@bwp-web/styles/mui';
import { drawChildren } from './internal/layers.js';

/** Each layer's children, as Figma nests them. */
const TREE: Record<string, string[]> = {
  root: ['leadingIcon', 'label', 'shortcut', 'trailingIcon'],
};
const SLOTS: Record<string, string> = {
  leadingIcon: 'leadingIcon',
  label: 'label',
  shortcut: 'shortcut',
  trailingIcon: 'trailingIcon',
};

export interface ContextMenuItemProps
  extends
    SolarContextMenuItemProps,
    Omit<
      MenuItemProps,
      | keyof SolarContextMenuItemProps
      | 'children'
      | 'dense'
      | 'divider'
      | 'disableGutters'
      | 'selected'
      | 'ref'
    > {
  /** The action's words. */
  children: ReactNode;
  /** An icon before the words. */
  leadingIcon?: ReactNode;
  /** An icon after the words and the shortcut. */
  trailingIcon?: ReactNode;
  /** The action's keyboard shortcut, as the platform writes it (⌘C, Ctrl+C). */
  shortcut?: ReactNode;
}

export const ContextMenuItem = forwardRef<HTMLLIElement, ContextMenuItemProps>(
  function ContextMenuItem(inProps, ref) {
    // As the app's MUI theme sets them (components.SolarContextMenuItem), under the caller's own.
    const {
      disabled = false,
      destructive = false,
      children,
      leadingIcon,
      trailingIcon,
      shortcut,
      sx,
      ...rest
    } = useSolarProps(inProps, 'SolarContextMenuItem');
    const look = { disabled, destructive };
    const composed = solarContextMenuItemCompose(look);
    // A slot left empty is not drawn.
    const parts = {
      ...composed,
      leadingIcon: { ...composed.leadingIcon, present: leadingIcon != null },
      trailingIcon: { ...composed.trailingIcon, present: trailingIcon != null },
      shortcut: { ...composed.shortcut, present: shortcut != null },
    };
    return (
      <MenuItem
        ref={ref}
        {...rest}
        disabled={disabled}
        disableRipple
        sx={[
          solarContextMenuItemStyle(look),
          ...(Array.isArray(sx) ? sx : [sx]),
        ]}
      >
        {drawChildren('root', {
          prefix: 'SolarContextMenuItem',
          tree: TREE,
          slots: SLOTS,
          parts,
          text: { label: children, shortcut },
          icons: {
            leadingIcon: <span>{leadingIcon}</span>,
            trailingIcon: <span>{trailingIcon}</span>,
          },
        })}
      </MenuItem>
    );
  },
);
