// Generated by @bwp-web/codegen from packages/codegen/src/components/date-picker.mjs. Do not edit.
/**
 * SOLAR DatePicker.
 *
 * Generated from its template in `packages/codegen/src/components/` on every `npm run
 * solar:codegen`: change the template there, never this file. What it looks like is not here. That
 * is the recipe, `solarDatePickerStyle` and `solarDatePickerCompose` in `@bwp-web/styles/mui`: the
 * field's fill, edge and focus ring by state, its words' and icon's ink, and the label and helper.
 *
 * A date, typed or picked: its `label` above (a `mandatory` one is starred, and the input
 * required), its `helper` below, which says what is wrong where it is in `error`. The field is
 * MUI's InputBase, taking the date in the locale's figures (`24/04/2026`, `04/24/2026` in the
 * US), read on Enter and as the focus leaves; its calendar button, or the down arrow, opens a
 * DatePickerOpen under it, the focus on the chosen day, where a click or Enter picks one and
 * Escape closes it. `value` and `onChange` hold the date, an ISO string (`2026-04-24`), or null
 * for none; words that are no date leave it as it was, for the caller to flag with `error`.
 * `min`, `max` and `isDateDisabled` refuse dates in the calendar; `calendarProps` reach it.
 * The app must load `@bwp-web/styles/tokens.css`.
 */

import Box from '@mui/material/Box';
import InputBase, { type InputBaseProps } from '@mui/material/InputBase';
import { useControlled, useForkRef } from '@mui/material/utils';
import { IconCalendar } from '@bwp-web/assets';
import {
  forwardRef,
  useEffect,
  useId,
  useRef,
  useState,
  type ReactNode,
} from 'react';
import {
  solarDatePickerCompose,
  solarDatePickerStyle,
  solarDatePickerStyles,
  type SolarDatePickerProps,
} from '@bwp-web/styles/mui';
import { DatePickerOpen, type DatePickerOpenProps } from './DatePickerOpen.js';
import {
  dateOf,
  isoOf,
  parseIso,
  parseShortDate,
  shortDate,
} from './internal/calendar.js';
import {
  drawChildren,
  drawLayer,
  type LayerDrawing,
} from './internal/layers.js';

/** Each layer's children, as Figma nests them. */
const TREE: Record<string, string[]> = {
  root: ['label', 'field', 'helper'],
  label: ['labelLabel', 'required'],
  field: ['iconCalendar', 'value'],
};
const SLOTS: Record<string, string> = {
  label: 'label',
  required: 'required',
  value: 'value',
  helper: 'helper',
};

export interface DatePickerProps
  extends
    SolarDatePickerProps,
    Omit<
      InputBaseProps,
      | keyof SolarDatePickerProps
      | 'size'
      | 'color'
      | 'fullWidth'
      | 'margin'
      | 'multiline'
      | 'rows'
      | 'minRows'
      | 'maxRows'
      | 'startAdornment'
      | 'endAdornment'
      | 'required'
      | 'type'
      | 'value'
      | 'defaultValue'
      | 'onChange'
      | 'ref'
    > {
  /** What it asks for, above it. */
  label?: ReactNode;
  /** Whether it must be filled, which stars the label and makes the input required. */
  mandatory?: boolean;
  /** More about it, below; where it is in `error`, what is wrong. */
  helper?: ReactNode;
  /** The date, ISO (`2026-04-24`), where the caller keeps it; null for none. */
  value?: string | null;
  /** The date it starts with, where `value` does not say. */
  defaultValue?: string | null;
  /** Called with the date typed or picked, ISO, or null where the words are cleared. */
  onChange?: (value: string | null) => void;
  /** The locale its figures, months and weekdays are written in; the page's by default. */
  locale?: string;
  /** The earliest and latest dates the calendar takes, ISO. */
  min?: string;
  max?: string;
  /** Whether the calendar refuses a date, ISO (a weekend, a booked day). */
  isDateDisabled?: (date: string) => boolean;
  /** The week's first day, 0 for Sunday to 6 for Saturday; the locale's by default. */
  weekStartsOn?: number;
  /** More of the calendar's props (`type="double"`, `today`). */
  calendarProps?: Partial<DatePickerOpenProps>;
  /** Whether its panel is open, where the caller keeps it. */
  open?: boolean;
  /** Called when the panel opens, and when it closes. */
  onOpen?: () => void;
  onClose?: () => void;
  /** The button that opens the panel, named for a screen reader. */
  openLabel?: string;
}

export const DatePicker = forwardRef<HTMLDivElement, DatePickerProps>(
  function DatePicker(
    {
      size,
      disabled,
      error,
      label,
      mandatory = false,
      helper,
      id: idProp,
      value: valueProp,
      defaultValue = null,
      onChange,
      locale,
      min,
      max,
      isDateDisabled,
      weekStartsOn,
      calendarProps,
      open: openProp,
      onOpen,
      onClose,
      openLabel = 'Choose date',
      inputProps,
      inputRef: inputRefProp,
      onBlur,
      onKeyDown,
      className,
      style,
      sx,
      ...rest
    },
    ref,
  ) {
    const own = useId();
    const id = idProp ?? own;
    const [value, setValue] = useControlled<string | null>({
      controlled: valueProp,
      default: defaultValue,
      name: 'DatePicker',
      state: 'value',
    });
    const [open, setOpen] = useControlled({
      controlled: openProp,
      default: false,
      name: 'DatePicker',
      state: 'open',
    });
    // The words follow the value, as the locale writes it, and are the user's while typed.
    const day = parseIso(value);
    const words = day ? shortDate(day, locale) : '';
    const [text, setText] = useState(words);
    useEffect(() => setText(words), [words]);
    const field = useRef<HTMLDivElement>(null);
    const input = useRef<HTMLInputElement>(null);
    const inputRef = useForkRef(inputRefProp, input);
    const choose = (next: string | null) => {
      setValue(next);
      onChange?.(next);
    };
    /** The value the words are, or null where they are none. */
    const read = (typed: string): string | null => {
      const d = parseShortDate(typed, locale);
      return d ? isoOf(dateOf(d)) : null;
    };
    // The words read back: cleared, no value; a value, it; anything else leaves it as it was.
    const commit = () => {
      const typed = text.trim();
      if (typed === '') {
        if (value !== null) choose(null);
        return;
      }
      const next = read(typed);
      if (next === null) return;
      if (next !== value) choose(next);
      else setText(words);
    };
    const show = () => {
      if (disabled || open) return;
      setOpen(true);
      onOpen?.();
    };
    const hide = () => {
      setOpen(false);
      onClose?.();
    };
    // Filled where it holds words: they are then the value's, not the placeholder's.
    const filled = text !== '';
    const look = { size, disabled, error, filled };
    const parts = solarDatePickerCompose(look);
    const drawing: LayerDrawing = {
      prefix: 'SolarDatePicker',
      tree: TREE,
      slots: SLOTS,
      // A part left empty is not drawn.
      parts: {
        ...parts,
        label: { ...parts.label, present: label != null },
        required: { ...parts.required, present: mandatory },
        helper: { ...parts.helper, present: helper != null },
      },
      text: { labelLabel: label, required: <span aria-hidden>*</span> },
      render: {
        label: (layer) => <label htmlFor={id} {...layer} />,
        // The icon is the button that opens the panel.
        iconCalendar: (layer) => (
          <button
            type="button"
            className={layer.className}
            style={layer.style}
            aria-label={openLabel}
            aria-haspopup="dialog"
            aria-expanded={open}
            disabled={disabled}
            onClick={show}
          >
            <IconCalendar />
          </button>
        ),
        // The field is MUI's InputBase, the button before the input, which is its words.
        field: (layer) => (
          <InputBase
            {...rest}
            ref={field}
            className={layer.className}
            style={layer.style}
            id={id}
            value={text}
            onChange={(event) => setText(event.target.value)}
            onBlur={(event) => {
              commit();
              onBlur?.(event);
            }}
            onKeyDown={(event) => {
              if (event.key === 'Enter') commit();
              if (event.key === 'ArrowDown') {
                event.preventDefault();
                show();
              }
              onKeyDown?.(event);
            }}
            disabled={disabled}
            error={error}
            required={mandatory}
            inputRef={inputRef}
            startAdornment={drawLayer('iconCalendar', drawing)}
            inputProps={{
              ...inputProps,
              className: ['SolarDatePicker-value', inputProps?.className]
                .filter(Boolean)
                .join(' '),
              'aria-describedby': helper != null ? `${id}-helper` : undefined,
            }}
          />
        ),
        helper: (layer) => (
          <span
            id={`${id}-helper`}
            className={layer.className}
            style={layer.style}
          >
            {helper}
          </span>
        ),
      },
    };
    // The panel, under the field, as far from it as the helper is.
    const gap = solarDatePickerStyles.root.gap;
    return (
      <Box
        ref={ref}
        className={
          [
            filled ? 'SolarDatePicker-filled' : null,
            error ? 'SolarDatePicker-error' : null,
            disabled ? 'SolarDatePicker-disabled' : null,
            className,
          ]
            .filter(Boolean)
            .join(' ') || undefined
        }
        style={style}
        sx={[solarDatePickerStyle(look), ...(Array.isArray(sx) ? sx : [sx])]}
      >
        {drawChildren('root', drawing)}
        {open ? (
          <DatePickerOpen
            locale={locale}
            min={min}
            max={max}
            isDateDisabled={isDateDisabled}
            weekStartsOn={weekStartsOn}
            {...calendarProps}
            sx={[
              { marginTop: gap },
              ...(Array.isArray(calendarProps?.sx)
                ? calendarProps.sx
                : [calendarProps?.sx]),
            ]}
            anchorEl={field.current}
            open
            onClose={hide}
            value={value}
            onChange={(iso) => {
              choose(iso);
              hide();
              input.current?.focus();
            }}
            // eslint-disable-next-line jsx-a11y/no-autofocus -- a date picker's dialog focuses its day as it opens, as the pattern asks
            autoFocus
          />
        ) : null}
      </Box>
    );
  },
);
