// Generated by @bwp-web/codegen from packages/codegen/src/components/dropdown-item.mjs. Do not edit.
/**
 * SOLAR Dropdown Item.
 *
 * Generated from its template in `packages/codegen/src/components/` on every `npm run
 * solar:codegen`: change the template there, never this file. What it looks like is not here. That
 * is the recipe, `solarDropdownItemStyle` and `solarDropdownItemCompose` in `@bwp-web/styles/mui`:
 * the row's fill by state, and its words' and icon's ink.
 *
 * One row of a DropdownMenu: MUI's MenuItem, so the menu moves the focus from row to row with the
 * arrow keys, and a focused row draws Figma's hover, as SOLAR's description says a highlighted one
 * does. Its words, a second line (`helper`), an `icon` before them and a `checkbox` are drawn
 * from Figma's layer tree (`internal/layers.tsx`). The checkbox follows `selected` and makes the
 * row a menuitemcheckbox, announced checked; a single-choice menu gives its rows
 * `role="menuitemradio"`, announced checked where selected, and a listbox its rows
 * `role="option"`, announced selected (MUI's Select does). In a menu it takes the menu's size.
 * The app must load
 * `@bwp-web/styles/tokens.css`.
 */

import { useSolarProps } from './internal/theme.js';
import MenuItem, { type MenuItemProps } from '@mui/material/MenuItem';
import { forwardRef, type ReactNode } from 'react';
import {
  solarDropdownItemCompose,
  solarDropdownItemStyle,
  type SolarDropdownItemProps,
} from '@bwp-web/styles/mui';
import { Checkbox } from './Checkbox.js';
import { useDropdownMenuSize } from './DropdownMenu.js';
import { drawChildren } from './internal/layers.js';

/** Each layer's children, as Figma nests them. */
const TREE: Record<string, string[]> = {
  root: ['checkbox', 'icon', 'content'],
  content: ['label', 'helper'],
};
const SLOTS: Record<string, string> = {
  checkbox: 'checkbox',
  icon: 'icon',
  helper: 'helper',
};

export interface DropdownItemProps
  extends
    SolarDropdownItemProps,
    Omit<
      MenuItemProps,
      | keyof SolarDropdownItemProps
      | 'children'
      | 'dense'
      | 'divider'
      | 'disableGutters'
      | 'ref'
    > {
  /** The row's words. */
  children: ReactNode;
  /** A second line under the words, quieter. */
  helper?: ReactNode;
  /** An icon before the words. */
  icon?: ReactNode;
  /** Shows a checkbox before the words, checked where the row is selected: a choice of several. */
  checkbox?: boolean;
}

export const DropdownItem = forwardRef<HTMLLIElement, DropdownItemProps>(
  function DropdownItem(inProps, ref) {
    // As the app's MUI theme sets them (components.SolarDropdownItem), under the caller's own.
    const {
      size,
      selected = false,
      disabled = false,
      children,
      helper,
      icon,
      checkbox = false,
      role,
      className,
      sx,
      ...rest
    } = useSolarProps(inProps, 'SolarDropdownItem');
    // In a menu, the menu's size, as Figma draws its rows.
    const look = { size: useDropdownMenuSize() ?? size, selected, disabled };
    const composed = solarDropdownItemCompose(look);
    // A slot left empty is not drawn.
    const parts = {
      ...composed,
      checkbox: { ...composed.checkbox, present: checkbox },
      icon: { ...composed.icon, present: icon != null },
      helper: { ...composed.helper, present: helper != null },
    };
    const as = role ?? (checkbox ? 'menuitemcheckbox' : 'menuitem');
    // The box's variant, as the recipe names it in each of the row's prop states, which may hold
    // together (a selected row disabled).
    const box = (state: string) =>
      solarDropdownItemCompose(look, state).checkbox;
    return (
      <MenuItem
        ref={ref}
        role={as}
        aria-checked={
          as === 'menuitemcheckbox' || as === 'menuitemradio'
            ? selected
            : undefined
        }
        aria-selected={as === 'option' ? selected : undefined}
        {...rest}
        disabled={disabled}
        disableRipple
        // Its checkbox takes its hover, and its keyboard focus (Checkbox's recipe).
        className={[
          'SolarStatesScope',
          selected ? 'SolarDropdownItem-selected' : null,
          className,
        ]
          .filter(Boolean)
          .join(' ')}
        sx={[solarDropdownItemStyle(look), ...(Array.isArray(sx) ? sx : [sx])]}
      >
        {drawChildren('root', {
          prefix: 'SolarDropdownItem',
          tree: TREE,
          slots: SLOTS,
          parts,
          text: { label: children, helper },
          // The box is a SOLAR Checkbox in the variant the recipe names, inert: the row is the
          // control, and says what is chosen.
          render: {
            checkbox: ({ className, style }) => (
              <span className={className} style={style}>
                <Checkbox
                  inert
                  checked={
                    box(selected ? 'selected' : 'default')[
                      'variant.checked'
                    ] === 'true'
                  }
                  disabled={
                    box(disabled ? 'disabled' : 'default')[
                      'variant.disabled'
                    ] === 'true'
                  }
                />
              </span>
            ),
          },
          icons: { icon: <span>{icon}</span> },
        })}
      </MenuItem>
    );
  },
);
