// Generated by @bwp-web/codegen from packages/codegen/src/components/file-card.mjs. Do not edit.
/**
 * SOLAR File Card.
 *
 * Generated from its template in `packages/codegen/src/components/` on every `npm run
 * solar:codegen`: change the template there, never this file. What it looks like is not here. That
 * is the recipe, `solarFileCardStyle` and `solarFileCardCompose` in `@bwp-web/styles/mui`: the
 * tile’s edge, shadow and focus ring, the thumbnail’s fill, its words’ ink, and the create tile’s
 * Plus.
 *
 * One file in a file browser's grid: its `thumbnail` (a preview, filling it) or its type's
 * `fileIcon`, its `title` (its name) and `meta` (when it changed), and a More menu of `moreItems`;
 * or, as `create`, the tile that adds one, a Plus over its `title` (“New design”). Given `onClick`
 * or `href`, it is pressable: its name is the button or link, and its hit area the whole tile, the
 * More menu reachable above it; the tile is named by it, and focused only then. Drawn from Figma's
 * layer tree (`internal/layers.tsx`). The app must load `@bwp-web/styles/tokens.css`.
 */

import { useSolarProps } from './internal/theme.js';
import Box, { type BoxProps } from '@mui/material/Box';
import ButtonBase from '@mui/material/ButtonBase';
import { IconMore, IconPlus } from '@bwp-web/assets';
import {
  forwardRef,
  useRef,
  useState,
  type MouseEvent,
  type ReactNode,
} from 'react';
import {
  solarFileCardCompose,
  solarFileCardStyle,
  type SolarFileCardProps,
} from '@bwp-web/styles/mui';
import type { CardMoreItem } from './Card.js';
import { DropdownItem } from './DropdownItem.js';
import { DropdownMenu } from './DropdownMenu.js';
import { drawChildren } from './internal/layers.js';

/** Each layer's children, as Figma nests them. */
const TREE: Record<string, string[]> = {
  root: ['thumbnail', 'footer', 'frame1', 'label'],
  thumbnail: ['fileIcon'],
  footer: ['text', 'iconMore'],
  text: ['title', 'meta'],
  frame1: ['iconPlus'],
};
const SLOTS: Record<string, string> = {
  fileIcon: 'fileIcon',
  title: 'title',
  meta: 'meta',
  label: 'label',
};

export interface FileCardProps
  extends
    SolarFileCardProps,
    // MUI types BoxProps' ref for any element; the component's own, a <div>, comes from forwardRef.
    Omit<
      BoxProps,
      | keyof SolarFileCardProps
      | 'title'
      | 'meta'
      | 'fileIcon'
      | 'thumbnail'
      | 'onClick'
      | 'ref'
    > {
  /** The file’s name, or what the create tile adds; its action’s name where it is pressable. */
  title: ReactNode;
  /** When it changed (“Edited just now”). */
  meta?: ReactNode;
  /** Its type’s icon, where it has no thumbnail. */
  fileIcon?: ReactNode;
  /** A preview of it (an image), filling the thumbnail in place of its icon. */
  thumbnail?: ReactNode;
  /** The More menu's actions: a button opens them. */
  moreItems?: CardMoreItem[];
  /** The More button's accessible name. */
  moreLabel?: string;
  /** Makes it pressable: its title is a button that calls it. */
  onClick?: (event: MouseEvent<HTMLElement>) => void;
  /** Makes it pressable: its title is a link here. */
  href?: string;
}

export const FileCard = forwardRef<HTMLDivElement, FileCardProps>(
  function FileCard(inProps, ref) {
    // As the app's MUI theme sets them (components.SolarFileCard), under the caller's own.
    const {
      type = 'file',
      title,
      meta,
      fileIcon,
      thumbnail,
      moreItems,
      moreLabel = 'More actions',
      onClick,
      href,
      className,
      sx,
      ...rest
    } = useSolarProps(inProps, 'SolarFileCard');
    const look = { type };
    const composed = solarFileCardCompose(look);
    const pressable = onClick != null || href != null;
    const menu = moreItems != null && moreItems.length > 0;
    // A slot left empty is not drawn.
    const parts = {
      ...composed,
      meta: {
        ...composed.meta,
        present: composed.meta?.present !== false && meta != null,
      },
      fileIcon: {
        ...composed.fileIcon,
        present: composed.fileIcon?.present !== false && fileIcon != null,
      },
      iconMore: {
        ...composed.iconMore,
        present: composed.iconMore?.present !== false && menu,
      },
    };
    const [open, setOpen] = useState(false);
    const moreRef = useRef<HTMLButtonElement>(null);
    // Pressable, its title is its action, stretched over the card.
    const titled = pressable ? (
      <ButtonBase
        className="SolarFileCard-press"
        disableRipple
        {...(href != null ? { href } : {})}
        onClick={onClick}
      >
        {title}
      </ButtonBase>
    ) : (
      title
    );
    return (
      <>
        <Box
          ref={ref}
          className={
            [pressable ? 'SolarFileCard-pressable' : null, className]
              .filter(Boolean)
              .join(' ') || undefined
          }
          {...rest}
          sx={[solarFileCardStyle(look), ...(Array.isArray(sx) ? sx : [sx])]}
        >
          {drawChildren('root', {
            prefix: 'SolarFileCard',
            tree: TREE,
            slots: SLOTS,
            parts,
            text: { label: titled, title: titled, meta },
            icons: {
              iconPlus: <IconPlus />,
              fileIcon: <span>{fileIcon}</span>,
              iconMore: (
                <ButtonBase
                  ref={moreRef}
                  disableRipple
                  disabled={false}
                  aria-label={moreLabel}
                  aria-haspopup="menu"
                  aria-expanded={open}
                  onClick={() => setOpen(true)}
                >
                  <IconMore />
                </ButtonBase>
              ),
            },
            content: {
              ...(thumbnail != null ? { thumbnail } : {}),
            },
          })}
        </Box>
        {menu ? (
          <DropdownMenu
            anchorEl={moreRef.current}
            open={open}
            onClose={() => setOpen(false)}
          >
            {moreItems.map((item, i) => (
              <DropdownItem
                key={i}
                disabled={item.disabled}
                icon={item.icon}
                onClick={() => {
                  setOpen(false);
                  item.onSelect();
                }}
              >
                {item.label}
              </DropdownItem>
            ))}
          </DropdownMenu>
        ) : null}
      </>
    );
  },
);
