// Generated by @bwp-web/codegen from packages/codegen/src/components/insight-row.mjs. Do not edit.
/**
 * SOLAR Insight Row.
 *
 * Generated from its template in `packages/codegen/src/components/` on every `npm run
 * solar:codegen`: change the template there, never this file. What it looks like is not here. That
 * is the recipe, `solarInsightRowStyle` and `solarInsightRowCompose` in `@bwp-web/styles/mui`: the
 * surface’s edge, shadow and focus ring by state, the severity’s bar, its words, and the
 * placeholders.
 *
 * One insight on a line, in a feed or a panel (stack them in a List): its `severity`'s bar, named
 * by `severityLabel` (its severity's word by default) so it is read, not only seen, its `title` and
 * `meta` each cut short on one line, and the caller's `action` (a SOLAR Button, sm and secondary as
 * Figma draws it). Given `onClick` or `href`, it is pressable: its title is the button or link, and
 * its hit area the whole row, the action reachable above it; it is hovered and focused only then.
 * `loading` draws Figma's placeholders, announced busy. For the same as a card of its own use an
 * Insight Card. Drawn from Figma's layer tree (`internal/layers.tsx`). The app must load
 * `@bwp-web/styles/tokens.css`.
 */

import { useSolarProps } from './internal/theme.js';
import Box, { type BoxProps } from '@mui/material/Box';
import ButtonBase from '@mui/material/ButtonBase';
import { forwardRef, type MouseEvent, type ReactNode } from 'react';
import {
  solarInsightRowCompose,
  solarInsightRowStyle,
  type SolarInsightRowProps,
} from '@bwp-web/styles/mui';
import { drawChildren, type DrawnLayer } from './internal/layers.js';

/** Each layer's children, as Figma nests them. */
const TREE: Record<string, string[]> = {
  root: ['severityBar', 'content'],
  content: ['body', 'action'],
  body: ['title', 'meta', 'skeleton', 'skeleton2'],
};
const SLOTS: Record<string, string> = {
  title: 'title',
  meta: 'meta',
  action: 'action',
};

export interface InsightRowProps
  extends
    SolarInsightRowProps,
    // MUI types BoxProps' ref for any element; the component's own, a <div>, comes from forwardRef.
    Omit<
      BoxProps,
      | keyof SolarInsightRowProps
      | 'title'
      | 'meta'
      | 'action'
      | 'severityLabel'
      | 'onClick'
      | 'ref'
    > {
  /** What the insight is, in a few words; its action’s name where it is pressable. */
  title: ReactNode;
  /** Its details, in a line. */
  meta?: ReactNode;
  /** The caller’s action: a SOLAR Button, sm and secondary as Figma draws it. */
  action?: ReactNode;
  /** The severity’s name, read where the bar is seen; its word by default. */
  severityLabel?: string;
  /** Makes it pressable: its title is a button that calls it. */
  onClick?: (event: MouseEvent<HTMLElement>) => void;
  /** Makes it pressable: its title is a link here. */
  href?: string;
}

export const InsightRow = forwardRef<HTMLDivElement, InsightRowProps>(
  function InsightRow(inProps, ref) {
    // As the app's MUI theme sets them (components.SolarInsightRow), under the caller's own.
    const {
      severity = 'success',
      loading = false,
      title,
      meta,
      action,
      severityLabel,
      onClick,
      href,
      className,
      sx,
      ...rest
    } = useSolarProps(inProps, 'SolarInsightRow');
    // Figma draws a loading one, with no status: its look is the same for all.
    const look = { severity: loading ? ('info' as const) : severity, loading };
    const composed = solarInsightRowCompose(look);
    // Pressable while it loads too, as Figma draws a loading card hovered: its title, the action,
    // is then its name alone.
    const pressable = onClick != null || href != null;
    // The severity is read as well as seen: its word, where the caller names it no other way.
    const named =
      severityLabel ?? severity.charAt(0).toUpperCase() + severity.slice(1);
    // A slot left empty is not drawn.
    const parts = {
      ...composed,
      meta: {
        ...composed.meta,
        present: composed.meta?.present !== false && meta != null,
      },
      action: {
        ...composed.action,
        present: composed.action?.present !== false && action != null,
      },
    };
    // Pressable, its title is its action, stretched over the card.
    const titled = pressable ? (
      <ButtonBase
        className="SolarInsightRow-press"
        disableRipple
        {...(href != null ? { href } : {})}
        onClick={onClick}
      >
        {title}
      </ButtonBase>
    ) : (
      title
    );
    // Loading, where its title is not drawn (Card's; a Device Card's is), the action is drawn in
    // its place, its name alone.
    const waiting =
      pressable &&
      loading &&
      !['title'].some((l) => composed[l]?.present !== false) ? (
        <ButtonBase
          className="SolarInsightRow-press"
          disableRipple
          {...(href != null ? { href } : {})}
          onClick={onClick}
        >
          <span className="SolarInsightRow-name">{title}</span>
        </ButtonBase>
      ) : null;
    return (
      <>
        <Box
          ref={ref}
          aria-busy={loading || undefined}
          className={
            [pressable ? 'SolarInsightRow-pressable' : null, className]
              .filter(Boolean)
              .join(' ') || undefined
          }
          {...rest}
          sx={[solarInsightRowStyle(look), ...(Array.isArray(sx) ? sx : [sx])]}
        >
          {waiting}
          {drawChildren('root', {
            prefix: 'SolarInsightRow',
            tree: TREE,
            slots: SLOTS,
            parts,
            text: { title: titled, meta },
            icons: {
              action: <span>{action}</span>,
            },
            render: {
              // The severity's bar, named by its word, which is read and never seen.
              severityBar: ({ className: c, style }: DrawnLayer) => (
                <span className={c} style={style}>
                  <span className="SolarInsightRow-name">{named}</span>
                </span>
              ),
            },
          })}
        </Box>
      </>
    );
  },
);
