// Generated by @bwp-web/codegen from packages/codegen/src/components/paginationitem.mjs. Do not edit.
/**
 * SOLAR PaginationItem.
 *
 * Generated from its template in `packages/codegen/src/components/` on every `npm run
 * solar:codegen`: change the template there, never this file. What it looks like is not here. That
 * is the recipe, `solarPaginationItemStyle` and `solarPaginationItemCompose` in
 * `@bwp-web/styles/mui`: the page's fill and ring by state, and its number's ink.
 *
 * One page of a Pagination: MUI's ButtonBase, a button (a link where it has an `href`) that goes to
 * its page, its number its children, named "Page 3" for a screen reader (`aria-label`
 * overrides). The `selected` one is the current page (`aria-current="page"`). Its own 24 × 24 box
 * is its target: the pages sit 4px apart. Use it inside a Pagination. The app must load
 * `@bwp-web/styles/tokens.css`.
 */

import ButtonBase, { type ButtonBaseProps } from '@mui/material/ButtonBase';
import { forwardRef, type ReactNode } from 'react';
import {
  solarPaginationItemCompose,
  solarPaginationItemStyle,
  type SolarPaginationItemProps,
} from '@bwp-web/styles/mui';
import { drawChildren } from './internal/layers.js';

/** Each layer's children, as Figma nests them. */
const TREE: Record<string, string[]> = { root: ['page'] };
const SLOTS: Record<string, string> = { page: 'page' };

export interface PaginationItemProps
  extends
    SolarPaginationItemProps,
    Omit<ButtonBaseProps, keyof SolarPaginationItemProps | 'children' | 'ref'> {
  /** The page's number. */
  children: ReactNode;
  /** Where it goes: it is a link. */
  href?: string;
}

export const PaginationItem = forwardRef<
  HTMLButtonElement,
  PaginationItemProps
>(function PaginationItem(
  { selected = false, disabled = false, children, sx, ...rest },
  ref,
) {
  const look = { selected, disabled };
  const parts = solarPaginationItemCompose(look);
  return (
    <ButtonBase
      ref={ref}
      aria-current={selected ? 'page' : undefined}
      aria-label={
        typeof children === 'number' || typeof children === 'string'
          ? `Page ${children}`
          : undefined
      }
      {...rest}
      disabled={disabled}
      disableRipple
      sx={[solarPaginationItemStyle(look), ...(Array.isArray(sx) ? sx : [sx])]}
    >
      {drawChildren('root', {
        prefix: 'SolarPaginationItem',
        tree: TREE,
        slots: SLOTS,
        parts,
        text: { page: children },
      })}
    </ButtonBase>
  );
});
