// Generated by @bwp-web/codegen from packages/codegen/src/components/paginationellipsis.mjs. Do not edit.
/**
 * SOLAR PaginationEllipsis.
 *
 * Generated from its template in `packages/codegen/src/components/` on every `npm run
 * solar:codegen`: change the template there, never this file. What it looks like is not here. That
 * is the recipe, `solarPaginationEllipsisStyle` and `solarPaginationEllipsisCompose` in
 * `@bwp-web/styles/mui`: its box and its words’ text style and ink.
 *
 * Bespoke: the gap in a Pagination's pages, an ellipsis drawn from Figma's layer tree
 * (`internal/layers.tsx`): static text, never a control, as its description says ("Ellipsis is
 * static text, never a 'jump' trigger"). The app must load `@bwp-web/styles/tokens.css`.
 */

import Box, { type BoxProps } from '@mui/material/Box';
import { forwardRef } from 'react';
import {
  solarPaginationEllipsisCompose,
  solarPaginationEllipsisStyle,
  type SolarPaginationEllipsisProps,
} from '@bwp-web/styles/mui';
import { drawChildren } from './internal/layers.js';

/** Each layer's children, as Figma nests them. */
const TREE: Record<string, string[]> = { root: ['label'] };

export interface PaginationEllipsisProps
  extends
    SolarPaginationEllipsisProps,
    // MUI types BoxProps' ref for any element; the component's own comes from forwardRef.
    Omit<BoxProps, keyof SolarPaginationEllipsisProps | 'children' | 'ref'> {}

export const PaginationEllipsis = forwardRef<
  HTMLSpanElement,
  PaginationEllipsisProps
>(function PaginationEllipsis({ sx, ...rest }, ref) {
  const parts = solarPaginationEllipsisCompose({});
  return (
    <Box
      component="span"
      ref={ref}
      {...rest}
      sx={[
        solarPaginationEllipsisStyle({}),
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
    >
      {drawChildren('root', {
        prefix: 'SolarPaginationEllipsis',
        tree: TREE,
        parts,
        text: { label: '…' },
      })}
    </Box>
  );
});
