// Generated by @bwp-web/codegen from packages/codegen/src/components/pagination.mjs. Do not edit.
/**
 * SOLAR Pagination.
 *
 * Generated from its template in `packages/codegen/src/components/` on every `npm run
 * solar:codegen`: change the template there, never this file. What it looks like is not here. That
 * is the recipe, `solarPaginationStyle` in `@bwp-web/styles/mui`: the gaps between its items.
 *
 * A list's pages, where their count is known and a reader jumps between them: the previous arrow,
 * the pages, the next arrow, in a `nav` named "Pagination" and a list, as SOLAR's description asks.
 * The pages shown are the first, the last and the current ± 1, with three at the end the current is
 * near (`1 2 3 … 12`), a gap of more than one page an ellipsis, one of one page that page. The
 * current page is announced (`aria-current="page"`); the arrows are disabled at the ends. `page`
 * (from 1) and `onChange` hold the page; `hrefOf` makes each page a link. A single page draws
 * nothing. For a step-by-step flow use a PageNavigator. The app must load
 * `@bwp-web/styles/tokens.css`.
 */

import { useSolarProps } from './internal/theme.js';
import Box, { type BoxProps } from '@mui/material/Box';
import { useControlled } from '@mui/material/utils';
import { forwardRef } from 'react';
import { solarPaginationStyle } from '@bwp-web/styles/mui';
import { PaginationEllipsis } from './PaginationEllipsis.js';
import { PaginationItem } from './PaginationItem.js';
import { PaginationNav } from './PaginationNav.js';

/**
 * The pages shown for `page` of `count`, and the gaps between them, as Figma draws them: the first,
 * the last, the current ± 1, and three at the end the current is near; a gap of one page is that
 * page.
 */
export function pagesOf(page: number, count: number): (number | 'gap')[] {
  const shown = new Set([1, count, page - 1, page, page + 1]);
  if (page <= 2) [1, 2, 3].forEach((p) => shown.add(p));
  if (page >= count - 1)
    [count - 2, count - 1, count].forEach((p) => shown.add(p));
  const pages = [...shown]
    .filter((p) => p >= 1 && p <= count)
    .sort((a, b) => a - b);
  const out: (number | 'gap')[] = [];
  pages.forEach((p, i) => {
    const before = pages[i - 1];
    if (before !== undefined && p - before === 2) out.push(p - 1);
    else if (before !== undefined && p - before > 2) out.push('gap');
    out.push(p);
  });
  return out;
}

/** The layer Figma draws each page in by its place among the pages. */
// Each layer's class, public or internal (the codegen's util/classes.mjs): a page's layer is its
// position's, chosen as the pages are drawn.
const CLASS: Record<string, string> = {
  previous: 'SolarPagination--previous',
  page1: 'SolarPagination--page1',
  page2: 'SolarPagination--page2',
  page3: 'SolarPagination--page3',
  paginationEllipsis: 'SolarPagination--paginationEllipsis',
  page12: 'SolarPagination--page12',
  next: 'SolarPagination--next',
};
const pageLayer = (i: number, last: boolean) =>
  last ? 'page12' : i === 0 ? 'page1' : i === 1 ? 'page2' : 'page3';

export interface PaginationProps extends Omit<
  BoxProps,
  'children' | 'onChange' | 'ref'
> {
  /** How many pages there are. */
  count: number;
  /** The current page, from 1, where the caller keeps it. */
  page?: number;
  /** The page it starts on, where `page` does not say. */
  defaultPage?: number;
  /** Called with the page chosen. */
  onChange?: (page: number) => void;
  /** Where each page is: each is then a link. */
  hrefOf?: (page: number) => string;
}

export const Pagination = forwardRef<HTMLElement, PaginationProps>(
  function Pagination(inProps, ref) {
    // As the app's MUI theme sets them (components.SolarPagination), under the caller's own.
    const {
      count,
      page: pageProp,
      defaultPage = 1,
      onChange,
      hrefOf,
      'aria-label': label = 'Pagination',
      sx,
      ...rest
    } = useSolarProps(inProps, 'SolarPagination');
    const [page, setPage] = useControlled({
      controlled: pageProp,
      default: defaultPage,
      name: 'Pagination',
      state: 'page',
    });
    // A single page is no pagination, as its description says.
    if (count <= 1) return null;
    const go = (to: number) => {
      setPage(to);
      onChange?.(to);
    };
    const items = pagesOf(page, count);
    const pages = items.filter((p) => p !== 'gap').length;
    let seen = 0;
    return (
      <Box
        component="nav"
        ref={ref}
        aria-label={label}
        {...rest}
        sx={[solarPaginationStyle({}), ...(Array.isArray(sx) ? sx : [sx])]}
      >
        <ul className="SolarPagination-list">
          <li className="SolarPagination--previous">
            <PaginationNav
              direction="previous"
              disabled={page <= 1}
              onClick={() => go(page - 1)}
            />
          </li>
          {items.map((p, i) => {
            if (p === 'gap')
              return (
                <li
                  key={`gap${i}`}
                  className="SolarPagination--paginationEllipsis"
                >
                  <PaginationEllipsis />
                </li>
              );
            const at = seen++;
            return (
              <li key={p} className={CLASS[pageLayer(at, at === pages - 1)]}>
                <PaginationItem
                  selected={p === page}
                  onClick={() => go(p)}
                  {...(hrefOf ? { href: hrefOf(p) } : {})}
                >
                  {p}
                </PaginationItem>
              </li>
            );
          })}
          <li className="SolarPagination--next">
            <PaginationNav
              direction="next"
              disabled={page >= count}
              onClick={() => go(page + 1)}
            />
          </li>
        </ul>
      </Box>
    );
  },
);
