// Generated by @bwp-web/codegen from packages/codegen/src/components/section-nav-group-header.mjs. Do not edit.
/**
 * SOLAR Section Nav Group Header.
 *
 * Generated from its template in `packages/codegen/src/components/` on every `npm run
 * solar:codegen`: change the template there, never this file. What it looks like is not here. That
 * is the recipe, `solarSectionNavGroupHeaderStyle` and `solarSectionNavGroupHeaderCompose` in
 * `@bwp-web/styles/mui`: its words’ text style and ink, and its padding.
 *
 * Bespoke: the heading of a group of SectionNavItems in a section nav rail, drawn from Figma's
 * layer tree (`internal/layers.tsx`), not interactive, and announced as a heading (`level`, 3 by
 * default) so a screen reader names the group, as its description asks. Its words are its children.
 * The app must load `@bwp-web/styles/tokens.css`.
 */

import Box, { type BoxProps } from '@mui/material/Box';
import { forwardRef, type ReactNode } from 'react';
import {
  solarSectionNavGroupHeaderCompose,
  solarSectionNavGroupHeaderStyle,
  type SolarSectionNavGroupHeaderProps,
} from '@bwp-web/styles/mui';
import { drawChildren } from './internal/layers.js';

/** Each layer's children, as Figma nests them. */
const TREE: Record<string, string[]> = { root: ['label'] };
const SLOTS: Record<string, string> = { label: 'label' };

export interface SectionNavGroupHeaderProps
  extends
    SolarSectionNavGroupHeaderProps,
    // MUI types BoxProps' ref for any element; the component's own comes from forwardRef.
    Omit<BoxProps, keyof SolarSectionNavGroupHeaderProps | 'children' | 'ref'> {
  /** The group's name. */
  children: ReactNode;
  /** Its heading level, for a screen reader. */
  level?: 1 | 2 | 3 | 4 | 5 | 6;
}

export const SectionNavGroupHeader = forwardRef<
  HTMLDivElement,
  SectionNavGroupHeaderProps
>(function SectionNavGroupHeader({ children, level = 3, sx, ...rest }, ref) {
  const parts = solarSectionNavGroupHeaderCompose({});
  return (
    <Box
      component="div"
      ref={ref}
      role="heading"
      aria-level={level}
      {...rest}
      sx={[
        solarSectionNavGroupHeaderStyle({}),
        ...(Array.isArray(sx) ? sx : [sx]),
      ]}
    >
      {drawChildren('root', {
        prefix: 'SolarSectionNavGroupHeader',
        tree: TREE,
        slots: SLOTS,
        parts,
        text: { label: children },
      })}
    </Box>
  );
});
