// Generated by @bwp-web/codegen from packages/codegen/src/components/section-nav-item.mjs. Do not edit.
/**
 * SOLAR Section Nav Item.
 *
 * Generated from its template in `packages/codegen/src/components/` on every `npm run
 * solar:codegen`: change the template there, never this file. What it looks like is not here. That
 * is the recipe, `solarSectionNavItemStyle` and `solarSectionNavItemCompose` in
 * `@bwp-web/styles/mui`: the item's fill and focus ring by state, and its icon's and label's ink.
 *
 * One item of a section nav rail, the settings and admin sub-navigation (a sidebar's destinations are
 * NavItems): MUI's ButtonBase, a link where it has an `href` (or a router's link as its
 * `component`), a button otherwise. The `selected` one is the current page
 * (`aria-current="page"`), drawn by its fill, not colour alone, as its description says. Its
 * `icon` and `label` are drawn from Figma's layer tree (`internal/layers.tsx`); it spans its
 * rail. Group them under SectionNavGroupHeaders. The app must load `@bwp-web/styles/tokens.css`.
 */

import ButtonBase, { type ButtonBaseProps } from '@mui/material/ButtonBase';
import { forwardRef, type ReactNode } from 'react';
import {
  solarSectionNavItemCompose,
  solarSectionNavItemStyle,
  type SolarSectionNavItemProps,
} from '@bwp-web/styles/mui';
import { drawChildren } from './internal/layers.js';

/** Each layer's children, as Figma nests them. */
const TREE: Record<string, string[]> = { root: ['icon', 'label'] };

export interface SectionNavItemProps
  extends
    SolarSectionNavItemProps,
    Omit<ButtonBaseProps, keyof SolarSectionNavItemProps | 'children' | 'ref'> {
  /** Where it goes. */
  label: ReactNode;
  /** An icon before the words. */
  icon: ReactNode;
  /** Where it goes: it is a link. */
  href?: string;
}

export const SectionNavItem = forwardRef<
  HTMLButtonElement,
  SectionNavItemProps
>(function SectionNavItem(
  { selected = false, disabled = false, label, icon, className, sx, ...rest },
  ref,
) {
  const look = { selected, disabled };
  const parts = solarSectionNavItemCompose(look);
  return (
    <ButtonBase
      ref={ref}
      aria-current={selected ? 'page' : undefined}
      {...rest}
      disabled={disabled}
      disableRipple
      className={
        [selected ? 'SolarSectionNavItem-selected' : null, className]
          .filter(Boolean)
          .join(' ') || undefined
      }
      sx={[solarSectionNavItemStyle(look), ...(Array.isArray(sx) ? sx : [sx])]}
    >
      {drawChildren('root', {
        prefix: 'SolarSectionNavItem',
        tree: TREE,
        parts,
        text: { label },
        icons: { icon: <span>{icon}</span> },
      })}
    </ButtonBase>
  );
});
