// Generated by @bwp-web/codegen from spec/tokens.json. Do not edit.
// SOLAR in an MUI theme's types: its semantic colours as palette groups (theme.palette.surface.raised,
// sx={{ bgcolor: 'surface.raised' }}) and its text styles as Typography variants (variant="titleSm").
// The values are in @bwp-web/styles/mui's createSolarThemeOptions, which SolarProvider installs.

import type { CSSProperties } from 'react';

declare module '@mui/material/styles' {
  interface Palette {
    brand: {
      primary: string;
      secondary: string;
      tertiary: string;
    };
    surface: {
      background: string;
      base: string;
      raised: string;
      overlay: string;
      dialog: string;
      scrim: string;
      muted: string;
      inverse: string;
      hover: string;
      active: string;
      feedback: {
        success: {
          subtleAlpha: string;
          subtle: string;
          medium: string;
          strong: string;
        };
        warning: {
          subtleAlpha: string;
          subtle: string;
          medium: string;
          strong: string;
        };
        danger: {
          subtleAlpha: string;
          subtle: string;
          medium: string;
          strong: string;
        };
        info: {
          subtleAlpha: string;
          subtle: string;
          medium: string;
          strong: string;
        };
        neutral: {
          subtleAlpha: string;
          subtle: string;
          medium: string;
          strong: string;
        };
      };
    };
    border: {
      subtle: string;
      medium: string;
      strong: string;
      disabled: string;
      inverse: {
        main: string;
        subtle: string;
        strong: string;
      };
      surface: string;
      highlight: string;
      feedback: {
        focus: {
          subtle: string;
          medium: string;
          strong: string;
        };
        success: {
          subtle: string;
          medium: string;
          strong: string;
        };
        warning: {
          subtle: string;
          medium: string;
          strong: string;
        };
        danger: {
          subtle: string;
          medium: string;
          strong: string;
        };
        info: {
          subtle: string;
          medium: string;
          strong: string;
        };
        neutral: {
          subtle: string;
          medium: string;
          strong: string;
        };
      };
    };
    icon: {
      primary: string;
      secondary: string;
      tertiary: string;
      disabled: string;
      inverse: string;
      feedback: {
        success: string;
        warning: string;
        danger: string;
        info: string;
        neutral: string;
      };
      link: {
        default: string;
        hover: string;
        active: string;
        disabled: string;
      };
    };
    shadow: {
      subtle: string;
      strong: string;
      feedback: {
        focus: string;
        warning: string;
        danger: string;
        success: string;
        info: string;
        neutral: string;
      };
    };
    data: {
      category: {
        '01': {
          strong: string;
          subtle: string;
        };
        '02': {
          strong: string;
          subtle: string;
        };
        '03': {
          strong: string;
          subtle: string;
        };
        '04': {
          strong: string;
          subtle: string;
        };
        '05': {
          strong: string;
          subtle: string;
        };
        '06': {
          strong: string;
          subtle: string;
        };
        '07': {
          strong: string;
          subtle: string;
        };
        '08': {
          strong: string;
          subtle: string;
        };
      };
      scale: {
        '100': string;
        '200': string;
        '300': string;
        '400': string;
        '500': string;
        '600': string;
        '700': string;
        '800': string;
        '900': string;
      };
      delta: {
        neutral: string;
        negative100: string;
        negative300: string;
        negative500: string;
        positive100: string;
        positive300: string;
        positive500: string;
      };
    };
    meter: {
      nominal: string;
      warning: string;
      peak: string;
    };
    control: {
      neutral: {
        bg: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
        border: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
        icon: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
      };
      mute: {
        bg: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
        border: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
        icon: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
      };
      solo: {
        bg: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
        border: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
        icon: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
      };
      phantom: {
        bg: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
        border: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
        icon: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
      };
      phase: {
        bg: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
        border: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
        icon: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
      };
    };
  }

  interface PaletteOptions {
    brand?: {
      primary?: string;
      secondary?: string;
      tertiary?: string;
    };
    surface?: {
      background?: string;
      base?: string;
      raised?: string;
      overlay?: string;
      dialog?: string;
      scrim?: string;
      muted?: string;
      inverse?: string;
      hover?: string;
      active?: string;
      feedback?: {
        success?: {
          subtleAlpha?: string;
          subtle?: string;
          medium?: string;
          strong?: string;
        };
        warning?: {
          subtleAlpha?: string;
          subtle?: string;
          medium?: string;
          strong?: string;
        };
        danger?: {
          subtleAlpha?: string;
          subtle?: string;
          medium?: string;
          strong?: string;
        };
        info?: {
          subtleAlpha?: string;
          subtle?: string;
          medium?: string;
          strong?: string;
        };
        neutral?: {
          subtleAlpha?: string;
          subtle?: string;
          medium?: string;
          strong?: string;
        };
      };
    };
    border?: {
      subtle?: string;
      medium?: string;
      strong?: string;
      disabled?: string;
      inverse?: {
        main?: string;
        subtle?: string;
        strong?: string;
      };
      surface?: string;
      highlight?: string;
      feedback?: {
        focus?: {
          subtle?: string;
          medium?: string;
          strong?: string;
        };
        success?: {
          subtle?: string;
          medium?: string;
          strong?: string;
        };
        warning?: {
          subtle?: string;
          medium?: string;
          strong?: string;
        };
        danger?: {
          subtle?: string;
          medium?: string;
          strong?: string;
        };
        info?: {
          subtle?: string;
          medium?: string;
          strong?: string;
        };
        neutral?: {
          subtle?: string;
          medium?: string;
          strong?: string;
        };
      };
    };
    icon?: {
      primary?: string;
      secondary?: string;
      tertiary?: string;
      disabled?: string;
      inverse?: string;
      feedback?: {
        success?: string;
        warning?: string;
        danger?: string;
        info?: string;
        neutral?: string;
      };
      link?: {
        default?: string;
        hover?: string;
        active?: string;
        disabled?: string;
      };
    };
    shadow?: {
      subtle?: string;
      strong?: string;
      feedback?: {
        focus?: string;
        warning?: string;
        danger?: string;
        success?: string;
        info?: string;
        neutral?: string;
      };
    };
    data?: {
      category?: {
        '01'?: {
          strong?: string;
          subtle?: string;
        };
        '02'?: {
          strong?: string;
          subtle?: string;
        };
        '03'?: {
          strong?: string;
          subtle?: string;
        };
        '04'?: {
          strong?: string;
          subtle?: string;
        };
        '05'?: {
          strong?: string;
          subtle?: string;
        };
        '06'?: {
          strong?: string;
          subtle?: string;
        };
        '07'?: {
          strong?: string;
          subtle?: string;
        };
        '08'?: {
          strong?: string;
          subtle?: string;
        };
      };
      scale?: {
        '100'?: string;
        '200'?: string;
        '300'?: string;
        '400'?: string;
        '500'?: string;
        '600'?: string;
        '700'?: string;
        '800'?: string;
        '900'?: string;
      };
      delta?: {
        neutral?: string;
        negative100?: string;
        negative300?: string;
        negative500?: string;
        positive100?: string;
        positive300?: string;
        positive500?: string;
      };
    };
    meter?: {
      nominal?: string;
      warning?: string;
      peak?: string;
    };
    control?: {
      neutral?: {
        bg?: {
          default?: string;
          hover?: string;
          active?: string;
          disabled?: string;
        };
        border?: {
          default?: string;
          hover?: string;
          active?: string;
          disabled?: string;
        };
        icon?: {
          default?: string;
          hover?: string;
          active?: string;
          disabled?: string;
        };
      };
      mute?: {
        bg?: {
          default?: string;
          hover?: string;
          active?: string;
          disabled?: string;
        };
        border?: {
          default?: string;
          hover?: string;
          active?: string;
          disabled?: string;
        };
        icon?: {
          default?: string;
          hover?: string;
          active?: string;
          disabled?: string;
        };
      };
      solo?: {
        bg?: {
          default?: string;
          hover?: string;
          active?: string;
          disabled?: string;
        };
        border?: {
          default?: string;
          hover?: string;
          active?: string;
          disabled?: string;
        };
        icon?: {
          default?: string;
          hover?: string;
          active?: string;
          disabled?: string;
        };
      };
      phantom?: {
        bg?: {
          default?: string;
          hover?: string;
          active?: string;
          disabled?: string;
        };
        border?: {
          default?: string;
          hover?: string;
          active?: string;
          disabled?: string;
        };
        icon?: {
          default?: string;
          hover?: string;
          active?: string;
          disabled?: string;
        };
      };
      phase?: {
        bg?: {
          default?: string;
          hover?: string;
          active?: string;
          disabled?: string;
        };
        border?: {
          default?: string;
          hover?: string;
          active?: string;
          disabled?: string;
        };
        icon?: {
          default?: string;
          hover?: string;
          active?: string;
          disabled?: string;
        };
      };
    };
  }

  interface TypeText {
    tertiary: string;
    inverse: string;
    feedback: {
      success: string;
      warning: string;
      danger: string;
      info: string;
      neutral: string;
    };
    link: {
      default: string;
      hover: string;
      active: string;
      disabled: string;
    };
  }

  interface TypeAction {
    primary: {
      bg: {
        default: string;
        hover: string;
        active: string;
        disabled: string;
        danger: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
      };
      text: {
        default: string;
        hover: string;
        active: string;
        disabled: string;
        danger: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
      };
      icon: {
        default: string;
        hover: string;
        active: string;
        disabled: string;
        danger: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
      };
      border: {
        default: string;
        hover: string;
        active: string;
        disabled: string;
        danger: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
      };
    };
    secondary: {
      bg: {
        default: string;
        hover: string;
        active: string;
        disabled: string;
        danger: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
      };
      text: {
        default: string;
        hover: string;
        active: string;
        disabled: string;
        danger: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
      };
      icon: {
        default: string;
        hover: string;
        active: string;
        disabled: string;
        danger: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
      };
      border: {
        default: string;
        hover: string;
        active: string;
        disabled: string;
        danger: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
      };
    };
    tertiary: {
      bg: {
        default: string;
        hover: string;
        active: string;
        disabled: string;
        danger: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
      };
      text: {
        default: string;
        hover: string;
        active: string;
        disabled: string;
        danger: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
      };
      icon: {
        default: string;
        hover: string;
        active: string;
        disabled: string;
        danger: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
      };
      border: {
        default: string;
        hover: string;
        active: string;
        disabled: string;
        danger: {
          default: string;
          hover: string;
          active: string;
          disabled: string;
        };
      };
    };
  }

  interface TypographyVariants {
    displayLg: CSSProperties;
    displayMd: CSSProperties;
    displaySm: CSSProperties;
    displayXsMedium: CSSProperties;
    displayXsSemibold: CSSProperties;
    titleLg: CSSProperties;
    titleMd: CSSProperties;
    titleSm: CSSProperties;
    titleXs: CSSProperties;
    title2xs: CSSProperties;
    bodyLgRegular: CSSProperties;
    bodyLgMedium: CSSProperties;
    bodyLgSemibold: CSSProperties;
    bodyLgBold: CSSProperties;
    bodyMdRegular: CSSProperties;
    bodyMdMedium: CSSProperties;
    bodyMdSemibold: CSSProperties;
    bodyMdBold: CSSProperties;
    bodySmRegular: CSSProperties;
    bodySmMedium: CSSProperties;
    bodySmSemibold: CSSProperties;
    bodySmBold: CSSProperties;
    bodyXsRegular: CSSProperties;
    bodyXsMedium: CSSProperties;
    bodyXsSemibold: CSSProperties;
    bodyXsBold: CSSProperties;
    body2xsRegular: CSSProperties;
    body2xsMedium: CSSProperties;
    body2xsSemibold: CSSProperties;
    body2xsBold: CSSProperties;
    labelMd: CSSProperties;
    labelSm: CSSProperties;
    helperMd: CSSProperties;
    helperSm: CSSProperties;
    codeLg: CSSProperties;
    codeMd: CSSProperties;
    captionXs: CSSProperties;
    linkLgDefault: CSSProperties;
    linkLgHover: CSSProperties;
    linkMdDefault: CSSProperties;
    linkMdHover: CSSProperties;
    linkSmDefault: CSSProperties;
    linkSmHover: CSSProperties;
    linkXsDefault: CSSProperties;
    linkXsHover: CSSProperties;
    link2xsDefault: CSSProperties;
    link2xsHover: CSSProperties;
  }

  interface TypographyVariantsOptions {
    displayLg?: CSSProperties;
    displayMd?: CSSProperties;
    displaySm?: CSSProperties;
    displayXsMedium?: CSSProperties;
    displayXsSemibold?: CSSProperties;
    titleLg?: CSSProperties;
    titleMd?: CSSProperties;
    titleSm?: CSSProperties;
    titleXs?: CSSProperties;
    title2xs?: CSSProperties;
    bodyLgRegular?: CSSProperties;
    bodyLgMedium?: CSSProperties;
    bodyLgSemibold?: CSSProperties;
    bodyLgBold?: CSSProperties;
    bodyMdRegular?: CSSProperties;
    bodyMdMedium?: CSSProperties;
    bodyMdSemibold?: CSSProperties;
    bodyMdBold?: CSSProperties;
    bodySmRegular?: CSSProperties;
    bodySmMedium?: CSSProperties;
    bodySmSemibold?: CSSProperties;
    bodySmBold?: CSSProperties;
    bodyXsRegular?: CSSProperties;
    bodyXsMedium?: CSSProperties;
    bodyXsSemibold?: CSSProperties;
    bodyXsBold?: CSSProperties;
    body2xsRegular?: CSSProperties;
    body2xsMedium?: CSSProperties;
    body2xsSemibold?: CSSProperties;
    body2xsBold?: CSSProperties;
    labelMd?: CSSProperties;
    labelSm?: CSSProperties;
    helperMd?: CSSProperties;
    helperSm?: CSSProperties;
    codeLg?: CSSProperties;
    codeMd?: CSSProperties;
    captionXs?: CSSProperties;
    linkLgDefault?: CSSProperties;
    linkLgHover?: CSSProperties;
    linkMdDefault?: CSSProperties;
    linkMdHover?: CSSProperties;
    linkSmDefault?: CSSProperties;
    linkSmHover?: CSSProperties;
    linkXsDefault?: CSSProperties;
    linkXsHover?: CSSProperties;
    link2xsDefault?: CSSProperties;
    link2xsHover?: CSSProperties;
  }
}

declare module '@mui/material/Typography' {
  interface TypographyPropsVariantOverrides {
    displayLg: true;
    displayMd: true;
    displaySm: true;
    displayXsMedium: true;
    displayXsSemibold: true;
    titleLg: true;
    titleMd: true;
    titleSm: true;
    titleXs: true;
    title2xs: true;
    bodyLgRegular: true;
    bodyLgMedium: true;
    bodyLgSemibold: true;
    bodyLgBold: true;
    bodyMdRegular: true;
    bodyMdMedium: true;
    bodyMdSemibold: true;
    bodyMdBold: true;
    bodySmRegular: true;
    bodySmMedium: true;
    bodySmSemibold: true;
    bodySmBold: true;
    bodyXsRegular: true;
    bodyXsMedium: true;
    bodyXsSemibold: true;
    bodyXsBold: true;
    body2xsRegular: true;
    body2xsMedium: true;
    body2xsSemibold: true;
    body2xsBold: true;
    labelMd: true;
    labelSm: true;
    helperMd: true;
    helperSm: true;
    codeLg: true;
    codeMd: true;
    captionXs: true;
    linkLgDefault: true;
    linkLgHover: true;
    linkMdDefault: true;
    linkMdHover: true;
    linkSmDefault: true;
    linkSmHover: true;
    linkXsDefault: true;
    linkXsHover: true;
    link2xsDefault: true;
    link2xsHover: true;
  }
}

export {};
