// Generated by @bwp-web/codegen from packages/codegen/src/components/splitbutton.mjs. Do not edit.
/**
 * SOLAR SplitButton.
 *
 * Generated from its template in `packages/codegen/src/components/` on every `npm run
 * solar:codegen`: change the template there, never this file. What it looks like is not here. That
 * is the recipe, `solarSplitButtonStyle` in `@bwp-web/styles/mui`: the control's colours, border,
 * shadow and focus ring by state, its halves' padding, and the rule between them.
 *
 * The dominant action and a chevron that opens a menu of its variants (Save, Save as, Save and
 * close): two buttons in one joined control, drawn from Figma's layer tree
 * (`internal/layers.tsx`). Given `items`, the chevron, or Alt+Down on the action, opens them in
 * a DropdownMenu of its size under the control, and choosing one closes it; without them, the
 * chevron calls `onMenuOpen` for the caller's own menu, whose `menuOpen` it announces
 * (`aria-haspopup`, `aria-expanded`). The app must load `@bwp-web/styles/tokens.css`.
 */

import Box, { type BoxProps } from '@mui/material/Box';
import ButtonBase from '@mui/material/ButtonBase';
import { IconChevronDown } from '@bwp-web/assets';
import { useForkRef } from '@mui/material/utils';
import {
  forwardRef,
  useRef,
  useState,
  type KeyboardEvent,
  type MouseEvent,
  type ReactNode,
} from 'react';
import {
  solarSplitButtonCompose,
  solarSplitButtonStyle,
  type SolarSplitButtonProps,
  type SolarSpinnerSize,
  type SolarSpinnerVariant,
} from '@bwp-web/styles/mui';
import { DropdownItem } from './DropdownItem.js';
import { DropdownMenu } from './DropdownMenu.js';
import { drawChildren, type DrawnLayer } from './internal/layers.js';
import { Spinner } from './Spinner.js';

/** One of the action's variants, a row of the menu. */
export interface SplitButtonItem {
  /** Its words. */
  label: ReactNode;
  /** Called when it is chosen; the menu closes first. */
  onSelect: () => void;
  disabled?: boolean;
  /** An icon before its words. */
  icon?: ReactNode;
}

/** Each layer's children, as Figma nests them. */
const TREE: Record<string, string[]> = {
  root: ['action', 'divider', 'trigger', 'spinner'],
  action: ['label'],
  trigger: ['iconChevronDown'],
};
const SLOTS: Record<string, string> = { label: 'label' };

export interface SplitButtonProps
  extends
    SolarSplitButtonProps,
    // MUI types BoxProps' ref for any element; the component's own, a <div>, comes from forwardRef.
    Omit<
      BoxProps,
      keyof SolarSplitButtonProps | 'children' | 'onClick' | 'ref'
    > {
  /** The dominant action's label. */
  children: ReactNode;
  /** The dominant action. */
  onClick?: (event: MouseEvent<HTMLButtonElement>) => void;
  /** The action's variants, which the chevron opens in a menu of its own. */
  items?: SplitButtonItem[];
  /** Called as the chevron, or Alt+Down on the action, opens the menu: the caller's own, without `items`. */
  onMenuOpen?: () => void;
  /** Whether the caller's own menu is open, for the chevron's `aria-expanded`. */
  menuOpen?: boolean;
  /** The chevron's accessible name. */
  menuLabel?: string;
}

export const SplitButton = forwardRef<HTMLDivElement, SplitButtonProps>(
  function SplitButton(
    {
      variant,
      size,
      disabled,
      loading,
      children,
      onClick,
      items,
      onMenuOpen,
      menuOpen: menuOpenProp = false,
      menuLabel = 'More options',
      className,
      sx,
      ...rest
    },
    ref,
  ) {
    const busy = Boolean(loading && !disabled);
    const inactive = Boolean(disabled) || busy;
    const parts = solarSplitButtonCompose(
      { variant, size, disabled, loading },
      busy ? 'loading' : 'default',
    );
    const spinner = solarSplitButtonCompose(
      { variant, size, disabled, loading },
      'loading',
    ).spinner;
    // What the loading state hides keeps its room, so the control does not resize.
    const kept = { ...parts };
    for (const half of ['action', 'divider', 'trigger'])
      kept[half] = { ...parts[half], present: true };
    const shown = (layer: string) =>
      parts[layer]?.present === false
        ? { visibility: 'hidden' as const }
        : undefined;
    // Its own menu, where it is given the items, under the control.
    const [open, setOpen] = useState(false);
    const control = useRef<HTMLDivElement>(null);
    const joined = useForkRef(ref, control);
    const menuOpen = items ? open : menuOpenProp;
    const toggleMenu = () => {
      if (items) setOpen(true);
      onMenuOpen?.();
    };
    const openMenu = (event: KeyboardEvent) => {
      if (event.altKey && event.key === 'ArrowDown') {
        event.preventDefault();
        toggleMenu();
      }
    };
    return (
      <>
        <Box
          component="div"
          ref={joined}
          role="group"
          aria-busy={busy || undefined}
          className={
            [
              disabled ? 'SolarSplitButton-disabled' : null,
              busy ? 'SolarSplitButton-loading' : null,
              className,
            ]
              .filter(Boolean)
              .join(' ') || undefined
          }
          {...rest}
          sx={[
            solarSplitButtonStyle({ variant, size, disabled, loading }),
            ...(Array.isArray(sx) ? sx : [sx]),
          ]}
        >
          {drawChildren('root', {
            prefix: 'SolarSplitButton',
            tree: TREE,
            slots: SLOTS,
            parts: kept,
            text: { label: children },
            icons: { iconChevronDown: <IconChevronDown /> },
            render: {
              action: ({
                className: c,
                style,
                children: inner,
              }: DrawnLayer) => (
                <ButtonBase
                  className={c}
                  style={{ ...style, ...shown('action') }}
                  disabled={inactive}
                  disableRipple
                  onClick={onClick}
                  onKeyDown={openMenu}
                >
                  {inner}
                </ButtonBase>
              ),
              divider: ({ className: c, style }: DrawnLayer) => (
                <span
                  className={c}
                  style={{ ...style, ...shown('divider') }}
                  aria-hidden
                />
              ),
              trigger: ({
                className: c,
                style,
                children: inner,
              }: DrawnLayer) => (
                <ButtonBase
                  className={c}
                  style={{ ...style, ...shown('trigger') }}
                  disabled={inactive}
                  disableRipple
                  aria-label={menuLabel}
                  aria-haspopup="menu"
                  aria-expanded={menuOpen}
                  onClick={toggleMenu}
                >
                  {inner}
                </ButtonBase>
              ),
              spinner: ({ className: c }: DrawnLayer) =>
                busy ? (
                  <span className={c}>
                    <Spinner
                      size={spinner['variant.size'] as SolarSpinnerSize}
                      variant={spinner['variant.style'] as SolarSpinnerVariant}
                    />
                  </span>
                ) : null,
            },
          })}
        </Box>
        {items ? (
          <DropdownMenu
            size={size}
            anchorEl={control.current}
            open={open}
            onClose={() => setOpen(false)}
          >
            {items.map((item, i) => (
              <DropdownItem
                key={i}
                disabled={item.disabled}
                icon={item.icon}
                onClick={() => {
                  setOpen(false);
                  item.onSelect();
                }}
              >
                {item.label}
              </DropdownItem>
            ))}
          </DropdownMenu>
        ) : null}
      </>
    );
  },
);
