// Generated by @bwp-web/codegen from packages/codegen/src/components/stepper.mjs. Do not edit.
/**
 * SOLAR Stepper.
 *
 * Generated from its template in `packages/codegen/src/components/` on every `npm run
 * solar:codegen`: change the template there, never this file. What it looks like is not here. That
 * is the recipe, `solarStepperStyle` and `solarStepperCompose` in `@bwp-web/styles/mui`: each
 * type's bar, segments, lines and gaps.
 *
 * A linear flow's progress (a wizard, onboarding, a device's setup), in two to five `steps`: those
 * before `activeStep` (from 0) complete, it active, announced (`aria-current="step"`), those after
 * upcoming, and `errorStep` in error. Four types: round Steps over a progress bar (`with label`),
 * StepperIndicators joined by lines (`no label`), a bar of segments (`line`), and horizontal
 * Steps (`line+text`); where a type draws no words, each step's label is read, not drawn. Given
 * `onStepClick`, a completed Step is a button that goes back to it. The back and next buttons are
 * the Multi-step Wizard's, not the Stepper's. The app must load `@bwp-web/styles/tokens.css`.
 */

import { useSolarProps } from './internal/theme.js';
import Box, { type BoxProps } from '@mui/material/Box';
import { forwardRef, Fragment, type ReactNode } from 'react';
import {
  solarStepperCompose,
  solarStepperStyle,
  type SolarStepperProps,
} from '@bwp-web/styles/mui';
import { Step } from './Step.js';
import { StepperIndicator } from './StepperIndicator.js';

// Each layer's class, public or internal (the codegen's util/classes.mjs): a step's layers are its
// position's, chosen as the steps are drawn.
const CLASS: Record<string, string> = {
  progress: 'SolarStepper--progress',
  progressRectangle2: 'SolarStepper--progressRectangle2',
  steps: 'SolarStepper--steps',
  stepsStep: 'SolarStepper--stepsStep',
  stepsStep2: 'SolarStepper--stepsStep2',
  stepsStep3: 'SolarStepper--stepsStep3',
  stepperIndicator: 'SolarStepper--stepperIndicator',
  frame: 'SolarStepper--frame',
  stepperIndicator2: 'SolarStepper--stepperIndicator2',
  frame2: 'SolarStepper--frame2',
  stepperIndicator3: 'SolarStepper--stepperIndicator3',
  rectangle1: 'SolarStepper--rectangle1',
  rectangle2: 'SolarStepper--rectangle2',
  rectangle3: 'SolarStepper--rectangle3',
  rectangle4: 'SolarStepper--rectangle4',
  rectangle5: 'SolarStepper--rectangle5',
  stepCompleteHorizontal: 'SolarStepper--stepCompleteHorizontal',
  step: 'SolarStepper--step',
  step3: 'SolarStepper-step3',
  step4: 'SolarStepper-step4',
  step5: 'SolarStepper-step5',
};

type Status = 'complete' | 'active' | 'upcoming' | 'error';

/** A step's status as its Stepper Indicator names it (Figma calls a complete step's circle completed). */
const INDICATOR = {
  complete: 'completed',
  active: 'active',
  upcoming: 'upcoming',
  error: 'error',
} as const;

export interface StepperProps
  extends
    SolarStepperProps,
    Omit<BoxProps, keyof SolarStepperProps | 'children' | 'ref'> {
  /** The steps' labels, two to five. */
  steps: ReactNode[];
  /** The active step, from 0; those before it are complete. */
  activeStep: number;
  /** A step in error, from 0. */
  errorStep?: number;
  /** Called with a completed step's index where one is chosen: completed Steps are buttons. */
  onStepClick?: (index: number) => void;
}

export const Stepper = forwardRef<HTMLElement, StepperProps>(
  function Stepper(inProps, ref) {
    // As the app's MUI theme sets them (components.SolarStepper), under the caller's own.
    const {
      type = 'with label',
      steps,
      activeStep,
      errorStep,
      onStepClick,
      'aria-label': label = 'Progress',
      sx,
      ...rest
    } = useSolarProps(inProps, 'SolarStepper');
    const parts = solarStepperCompose({ type });
    const status = (i: number): Status =>
      i === errorStep
        ? 'error'
        : i < activeStep
          ? 'complete'
          : i === activeStep
            ? 'active'
            : 'upcoming';
    const n = steps.length;
    const cls = (layer: string, box = false) =>
      `${CLASS[layer]}${box ? ' SolarStepper-box' : ''}`;
    const current = (i: number) =>
      i === activeStep ? ('step' as const) : undefined;
    const name = (i: number) => (
      <span className="SolarStepper-name">{steps[i]}</span>
    );
    const step = (i: number, round: boolean) => (
      <Step
        status={status(i)}
        type={round ? 'round' : 'horizontal'}
        label={steps[i]}
        number={i + 1}
        onClick={
          onStepClick && status(i) === 'complete'
            ? () => onStepClick(i)
            : undefined
        }
      />
    );
    const root = (children: ReactNode, list = true) => (
      <Box
        component={list ? 'ol' : 'div'}
        ref={ref}
        aria-label={label}
        {...rest}
        sx={[solarStepperStyle({ type }), ...(Array.isArray(sx) ? sx : [sx])]}
      >
        {children}
      </Box>
    );
    // Each part in the layer Figma draws for its status, or at its place.
    const byStatus = (
      i: number,
      complete: string,
      active: string,
      upcoming: string,
    ) => ({ complete, active, error: active, upcoming })[status(i)];

    if (type === 'with label') {
      const fill =
        n > 1 ? Math.min(Math.max(activeStep, 0), n - 1) / (n - 1) : 0;
      const top = parts.progress?.y;
      return root(
        <>
          <div
            aria-hidden
            className={cls('progress', true)}
            style={{
              position: 'absolute',
              left: 0,
              right: 0,
              top:
                typeof top === 'number'
                  ? `calc(${top}px - var(--solar-placed-top, 0px))`
                  : undefined,
            }}
          >
            <div
              className={cls('progressRectangle2', true)}
              style={{ width: `${fill * 100}%` }}
            />
          </div>
          <ol className={cls('steps', true)}>
            {steps.map((_, i) => (
              <li
                key={i}
                className={cls(
                  byStatus(i, 'stepsStep', 'stepsStep2', 'stepsStep3'),
                )}
                aria-current={current(i)}
              >
                {step(i, true)}
              </li>
            ))}
          </ol>
        </>,
        false,
      );
    }
    if (type === 'no label')
      return root(
        steps.map((_, i) => (
          <Fragment key={i}>
            {i > 0 ? (
              <li
                aria-hidden
                className={cls(i - 1 < activeStep ? 'frame' : 'frame2', true)}
              />
            ) : null}
            <li
              className={cls(
                byStatus(
                  i,
                  'stepperIndicator',
                  'stepperIndicator2',
                  'stepperIndicator3',
                ),
              )}
              aria-current={current(i)}
            >
              <StepperIndicator number={i + 1} status={INDICATOR[status(i)]} />
              {name(i)}
            </li>
          </Fragment>
        )),
      );
    if (type === 'line')
      return root(
        steps.map((_, i) => (
          <li
            key={i}
            className={cls(
              i <= activeStep ? 'rectangle1' : `rectangle${i + 1}`,
              true,
            )}
            aria-current={current(i)}
          >
            {name(i)}
          </li>
        )),
      );
    return root(
      steps.map((_, i) => (
        <li
          key={i}
          className={cls(
            status(i) === 'complete'
              ? 'stepCompleteHorizontal'
              : (['step', 'step', 'step3', 'step4', 'step5'][i] ?? 'step5'),
          )}
          aria-current={current(i)}
        >
          {step(i, false)}
        </li>
      )),
    );
  },
);
