// Generated by @bwp-web/codegen from packages/codegen/src/components/tab-item.mjs. Do not edit.
/**
 * SOLAR Tab Item.
 *
 * Generated from its template in `packages/codegen/src/components/` on every `npm run
 * solar:codegen`: change the template there, never this file. What it looks like is not here. That
 * is the recipe, `solarTabItemStyle` and `solarTabItemCompose` in `@bwp-web/styles/mui`: the
 * tab's underline and focus ring by state, and its words' and icons' ink.
 *
 * One tab of a Tabs strip, MUI's Tab, so it lives inside a Tabs: the strip moves the focus from tab
 * to tab with the arrow keys, Enter or Space selects (SOLAR's description: "arrow keys move focus
 * and aria-selected marks the current tab"), and the selected tab is announced so. Its `label`,
 * an icon either side (`leadingIcon`, `trailingIcon`) and a `count`, a SOLAR Counter in the
 * variant Figma draws for the tab's state, are drawn from Figma's layer tree
 * (`internal/layers.tsx`). A focused tab draws Figma's focus, the selected underline and the ring.
 * In a Tabs it takes the strip's size, and its `value` is what the strip's `onChange` gives. The
 * app must load `@bwp-web/styles/tokens.css`.
 */

import Tab, { type TabProps } from '@mui/material/Tab';
import {
  forwardRef,
  useState,
  type FocusEvent,
  type FocusEventHandler,
  type ReactNode,
} from 'react';
import {
  solarTabItemCompose,
  solarTabItemStyle,
  type SolarTabItemProps,
} from '@bwp-web/styles/mui';
import { Counter } from './Counter.js';
import { useTabsSize } from './Tabs.js';
import { drawChildren } from './internal/layers.js';

/** Each layer's children, as Figma nests them. */
const TREE: Record<string, string[]> = {
  root: ['leadingIcon', 'label', 'trailingIcon', 'counter'],
};

export interface TabItemProps
  extends
    SolarTabItemProps,
    Omit<
      TabProps,
      | keyof SolarTabItemProps
      | 'label'
      | 'icon'
      | 'iconPosition'
      | 'children'
      | 'wrapped'
      | 'onBlur'
      | 'onFocusVisible'
      | 'ref'
    > {
  /** The tab's words. */
  label: ReactNode;
  /** An icon before the words. */
  leadingIcon?: ReactNode;
  /** An icon after the words. */
  trailingIcon?: ReactNode;
  /** A count after the words, a SOLAR Counter; none at 0 or below. */
  count?: number;
  /** Called as the tab takes the keyboard's focus. */
  onFocusVisible?: FocusEventHandler<HTMLDivElement>;
  /** Called as the tab loses the focus. */
  onBlur?: FocusEventHandler<HTMLDivElement>;
}

export const TabItem = forwardRef<HTMLDivElement, TabItemProps>(
  function TabItem(
    {
      size,
      selected = false,
      disabled = false,
      label,
      leadingIcon,
      trailingIcon,
      count,
      className,
      onFocusVisible,
      onBlur,
      sx,
      ...rest
    },
    ref,
  ) {
    // In a strip, the strip's size, as Figma draws its tabs.
    const look = { size: useTabsSize() ?? size, selected, disabled };
    const composed = solarTabItemCompose(look);
    // The Counter's variant is the tab's state's, the keyboard's focus among them.
    const [focused, setFocused] = useState(false);
    const state = disabled
      ? 'disabled'
      : selected
        ? 'selected'
        : focused
          ? 'focus'
          : 'default';
    const counter = solarTabItemCompose(look, state).counter;
    // A slot left empty is not drawn.
    const parts = {
      ...composed,
      leadingIcon: { ...composed.leadingIcon, present: leadingIcon != null },
      trailingIcon: { ...composed.trailingIcon, present: trailingIcon != null },
      counter: { ...composed.counter, present: count != null && count > 0 },
    };
    // MUI types a Tab's root, and its events, as a div's, though it renders a button.
    return (
      <Tab
        ref={ref}
        {...rest}
        // Tabs gives each Tab `selected`, which MUI's types leave out; a tab's own says it too.
        {...({ selected } as object)}
        disabled={disabled}
        disableRipple
        onFocusVisible={(event: FocusEvent<HTMLDivElement>) => {
          setFocused(true);
          onFocusVisible?.(event);
        }}
        onBlur={(event: FocusEvent<HTMLDivElement>) => {
          setFocused(false);
          onBlur?.(event);
        }}
        className={className}
        sx={[solarTabItemStyle(look), ...(Array.isArray(sx) ? sx : [sx])]}
        label={drawChildren('root', {
          prefix: 'SolarTabItem',
          tree: TREE,
          parts,
          text: { label },
          icons: {
            leadingIcon: <span>{leadingIcon}</span>,
            trailingIcon: <span>{trailingIcon}</span>,
          },
          // The counter is a SOLAR Counter in the variant the recipe names for the tab's state.
          render: {
            counter: ({ className, style }) => (
              <span className={className} style={style}>
                <Counter
                  count={count ?? 0}
                  type={counter['variant.type'] as never}
                />
              </span>
            ),
          },
        })}
      />
    );
  },
);
