// Generated by @bwp-web/codegen from packages/codegen/src/components/timepicker.mjs. Do not edit.
/**
 * SOLAR TimePicker.
 *
 * Generated from its template in `packages/codegen/src/components/` on every `npm run
 * solar:codegen`: change the template there, never this file. What it looks like is not here. That
 * is the recipe, `solarTimePickerStyle` and `solarTimePickerCompose` in `@bwp-web/styles/mui`: the
 * field's fill, edge and focus ring by state, its words' and icon's ink, and the label and helper.
 *
 * A time of day, typed or picked: its `label` above (a `mandatory` one is starred, and the input
 * required), its `helper` below, which says what is wrong where it is in `error`. The field is
 * MUI's InputBase, taking the time on the locale's clock (`9:30 AM`, `21:30`; either clock is
 * read), read on Enter and as the focus leaves; its clock button, or the down arrow, opens a
 * TimePickerDropdown under it, the chosen time in sight, where a click or Enter picks one and
 * Escape closes it. `value` and `onChange` hold the time, `HH:mm` (`09:30`), or null for none;
 * words that are no time leave it as it was, for the caller to flag with `error`. `step`, `min`
 * and `max` say which times the list offers; `dropdownProps` reach it. For a date and a time
 * together, put a DatePicker beside it.
 * The app must load `@bwp-web/styles/tokens.css`.
 */

import Box from '@mui/material/Box';
import InputBase, { type InputBaseProps } from '@mui/material/InputBase';
import { useControlled, useForkRef } from '@mui/material/utils';
import { IconClock } from '@bwp-web/assets';
import {
  forwardRef,
  useEffect,
  useId,
  useRef,
  useState,
  type ReactNode,
} from 'react';
import {
  solarTimePickerCompose,
  solarTimePickerStyle,
  solarTimePickerStyles,
  type SolarTimePickerProps,
} from '@bwp-web/styles/mui';
import {
  TimePickerDropdown,
  type TimePickerDropdownProps,
} from './TimePickerDropdown.js';
import {
  hhmmOf,
  parseHhmm,
  parseTimeWords,
  timeWords,
} from './internal/clock.js';
import {
  drawChildren,
  drawLayer,
  type LayerDrawing,
} from './internal/layers.js';

/** Each layer's children, as Figma nests them. */
const TREE: Record<string, string[]> = {
  root: ['label', 'field', 'helper'],
  label: ['labelLabel', 'required'],
  field: ['iconClock', 'value'],
};
const SLOTS: Record<string, string> = {
  label: 'label',
  required: 'required',
  value: 'value',
  helper: 'helper',
};

export interface TimePickerProps
  extends
    SolarTimePickerProps,
    Omit<
      InputBaseProps,
      | keyof SolarTimePickerProps
      | 'size'
      | 'color'
      | 'fullWidth'
      | 'margin'
      | 'multiline'
      | 'rows'
      | 'minRows'
      | 'maxRows'
      | 'startAdornment'
      | 'endAdornment'
      | 'required'
      | 'type'
      | 'value'
      | 'defaultValue'
      | 'onChange'
      | 'ref'
    > {
  /** What it asks for, above it. */
  label?: ReactNode;
  /** Whether it must be filled, which stars the label and makes the input required. */
  mandatory?: boolean;
  /** More about it, below; where it is in `error`, what is wrong. */
  helper?: ReactNode;
  /** The time, `HH:mm` (`09:30`), where the caller keeps it; null for none. */
  value?: string | null;
  /** The time it starts with, where `value` does not say. */
  defaultValue?: string | null;
  /** Called with the time typed or picked, `HH:mm`, or null where the words are cleared. */
  onChange?: (value: string | null) => void;
  /** The locale its times are written in, on its clock; the page's by default. */
  locale?: string;
  /** The minutes between one time and the next in the list. */
  step?: number;
  /** The earliest and latest times the list offers, `HH:mm`. */
  min?: string;
  max?: string;
  /** More of the list's props. */
  dropdownProps?: Partial<TimePickerDropdownProps>;
  /** Whether its panel is open, where the caller keeps it. */
  open?: boolean;
  /** Called when the panel opens, and when it closes. */
  onOpen?: () => void;
  onClose?: () => void;
  /** The button that opens the panel, named for a screen reader. */
  openLabel?: string;
}

export const TimePicker = forwardRef<HTMLDivElement, TimePickerProps>(
  function TimePicker(
    {
      size,
      disabled,
      error,
      label,
      mandatory = false,
      helper,
      id: idProp,
      value: valueProp,
      defaultValue = null,
      onChange,
      locale,
      step,
      min,
      max,
      dropdownProps,
      open: openProp,
      onOpen,
      onClose,
      openLabel = 'Choose time',
      inputProps,
      inputRef: inputRefProp,
      onBlur,
      onKeyDown,
      className,
      style,
      sx,
      ...rest
    },
    ref,
  ) {
    const own = useId();
    const id = idProp ?? own;
    const [value, setValue] = useControlled<string | null>({
      controlled: valueProp,
      default: defaultValue,
      name: 'TimePicker',
      state: 'value',
    });
    const [open, setOpen] = useControlled({
      controlled: openProp,
      default: false,
      name: 'TimePicker',
      state: 'open',
    });
    // The words follow the value, as the locale writes it, and are the user's while typed.
    const time = parseHhmm(value);
    const words = time ? timeWords(time, locale) : '';
    const [text, setText] = useState(words);
    useEffect(() => setText(words), [words]);
    const field = useRef<HTMLDivElement>(null);
    const input = useRef<HTMLInputElement>(null);
    const inputRef = useForkRef(inputRefProp, input);
    const choose = (next: string | null) => {
      setValue(next);
      onChange?.(next);
    };
    /** The value the words are, or null where they are none. */
    const read = (typed: string): string | null => {
      const t = parseTimeWords(typed, locale);
      return t ? hhmmOf(t) : null;
    };
    // The words read back: cleared, no value; a value, it; anything else leaves it as it was.
    const commit = () => {
      const typed = text.trim();
      if (typed === '') {
        if (value !== null) choose(null);
        return;
      }
      const next = read(typed);
      if (next === null) return;
      if (next !== value) choose(next);
      else setText(words);
    };
    const show = () => {
      if (disabled || open) return;
      setOpen(true);
      onOpen?.();
    };
    const hide = () => {
      setOpen(false);
      onClose?.();
    };
    // Filled where it holds words: they are then the value's, not the placeholder's.
    const filled = text !== '';
    const look = { size, disabled, error, filled };
    const parts = solarTimePickerCompose(look);
    const drawing: LayerDrawing = {
      prefix: 'SolarTimePicker',
      tree: TREE,
      slots: SLOTS,
      // A part left empty is not drawn.
      parts: {
        ...parts,
        label: { ...parts.label, present: label != null },
        required: { ...parts.required, present: mandatory },
        helper: { ...parts.helper, present: helper != null },
      },
      text: { labelLabel: label, required: <span aria-hidden>*</span> },
      render: {
        label: (layer) => <label htmlFor={id} {...layer} />,
        // The icon is the button that opens the panel.
        iconClock: (layer) => (
          <button
            type="button"
            className={layer.className}
            style={layer.style}
            aria-label={openLabel}
            aria-haspopup="listbox"
            aria-expanded={open}
            disabled={disabled}
            onClick={show}
          >
            <IconClock />
          </button>
        ),
        // The field is MUI's InputBase, the button before the input, which is its words.
        field: (layer) => (
          <InputBase
            {...rest}
            ref={field}
            className={layer.className}
            style={layer.style}
            id={id}
            value={text}
            onChange={(event) => setText(event.target.value)}
            onBlur={(event) => {
              commit();
              onBlur?.(event);
            }}
            onKeyDown={(event) => {
              if (event.key === 'Enter') commit();
              if (event.key === 'ArrowDown') {
                event.preventDefault();
                show();
              }
              onKeyDown?.(event);
            }}
            disabled={disabled}
            error={error}
            required={mandatory}
            inputRef={inputRef}
            startAdornment={drawLayer('iconClock', drawing)}
            inputProps={{
              ...inputProps,
              className: ['SolarTimePicker-value', inputProps?.className]
                .filter(Boolean)
                .join(' '),
              'aria-describedby': helper != null ? `${id}-helper` : undefined,
            }}
          />
        ),
        helper: (layer) => (
          <span
            id={`${id}-helper`}
            className={layer.className}
            style={layer.style}
          >
            {helper}
          </span>
        ),
      },
    };
    // The panel, under the field, as far from it as the helper is.
    const gap = solarTimePickerStyles.root.gap;
    return (
      <Box
        ref={ref}
        className={
          [
            filled ? 'SolarTimePicker-filled' : null,
            error ? 'SolarTimePicker-error' : null,
            disabled ? 'SolarTimePicker-disabled' : null,
            className,
          ]
            .filter(Boolean)
            .join(' ') || undefined
        }
        style={style}
        sx={[solarTimePickerStyle(look), ...(Array.isArray(sx) ? sx : [sx])]}
      >
        {drawChildren('root', drawing)}
        {open ? (
          <TimePickerDropdown
            size={size}
            step={step}
            min={min}
            max={max}
            locale={locale}
            {...dropdownProps}
            sx={[
              { marginTop: gap },
              ...(Array.isArray(dropdownProps?.sx)
                ? dropdownProps.sx
                : [dropdownProps?.sx]),
            ]}
            anchorEl={field.current}
            open
            onClose={hide}
            value={value}
            onChange={(time) => {
              choose(time);
              hide();
              input.current?.focus();
            }}
          />
        ) : null}
      </Box>
    );
  },
);
