// Generated by @bwp-web/codegen from packages/codegen/src/components/alert.mjs. Do not edit.
/// SOLAR Alert.
///
/// Generated from its template in `packages/codegen/src/components/` on every `npm run
/// solar:codegen`: change the template there, never this file. What it looks like is not here. That
/// is the recipe, [SolarAlertRecipe]: each type’s fill, edge and words, filled or outlined, and the
/// StatusIndicator it shows, read cell by cell.
///
/// A callout in the page, of a status: a title, a description and one action, each shown where it
/// is given, beside the StatusIndicator of its type. It is announced as it appears, at once where
/// it warns or reports a danger. A callout of its full size, for a page or a panel; inside cards
/// and narrower panels, use Alert Small. Bespoke: drawn from Figma's layer tree with [SolarLayers].
library;

import 'package:flutter/material.dart';

import '../generated/components/alert.dart';
import '../solar_layers.dart';
import '../solar_states.dart';
import '../solar_target.dart';
import '../generated/components/statusindicator.dart';
import 'solar_statusindicator.dart';
import 'solar_theme_of.dart';

class SolarAlert extends StatelessWidget {
  const SolarAlert({
    super.key,
    this.type = SolarAlertType.success,
    this.variant = SolarAlertVariant.filled,
    this.title,
    this.description,
    this.action,
    this.onAction,
  });

  final SolarAlertType type;
  final SolarAlertVariant variant;

  /// What happened, in a few words.
  final String? title;

  /// What it means, and what to do.
  final String? description;

  /// The one action's words, which call [onAction].
  final String? action;

  /// Called by the action.
  final VoidCallback? onAction;

  /// Each layer's children, as Figma nests them.
  static const _tree = <String, List<String>>{
    'root': ['statusIndicator', 'content', 'action'],
    'content': ['title', 'description'],
  };

  @override
  Widget build(BuildContext context) {
    final t = solarThemeOf(context);
    final p = SolarAlertProps(type: type, variant: variant);
    const states = <WidgetState>{};
    final mark = SolarLayers(
      recipe: SolarLayerRecipe(
        lookup: (c) => SolarAlertRecipe.lookup(c, p, states),
        dimension: (c) => SolarAlertRecipe.dimension(c, p, states),
        color: (c) => SolarAlertRecipe.color(t, c, p, states),
        shadow: (c) => SolarAlertRecipe.shadow(t, c, p, states),
        textStyle: (c) => SolarAlertRecipe.textStyle(t, c, p, states),
        present: (l) => switch (l) {
          'title' => title != null,
          'description' => description != null,
          'action' => action != null,
          _ => SolarAlertRecipe.present(l, p, states),
        },
        glyph: (_) => null,
      ),
      tree: _tree,
      keyPrefix: 'alert',
      text: {'title': ?title, 'description': ?description, 'action': ?action},
      builders: {
        'action': (words) => SolarTarget.inside(
          child: Semantics(
            // A node of its own, so the control keeps its name inside the component's.
            container: true,
            child: SolarPressable(
              onPressed: onAction,
              builder: (_, _) => words,
            ),
          ),
        ),
      },
      composed: {
        'statusIndicator': ExcludeSemantics(
          child: SolarStatusIndicator(
            type: SolarStatusIndicatorType.values.byName(
              SolarAlertRecipe.lookup(
                'statusIndicator.variant.type',
                p,
                states,
              )!.substring(2),
            ),
            size: SolarStatusIndicatorSize.values.byName(
              SolarAlertRecipe.lookup(
                'statusIndicator.variant.size',
                p,
                states,
              )!.substring(2),
            ),
          ),
        ),
      },
    ).layer('root');
    return Semantics(container: true, liveRegion: true, child: mark);
  }
}
