// Generated by @bwp-web/codegen from packages/codegen/src/components/interactive-card.mjs. Do not edit.
/// SOLAR Interactive Card.
///
/// Generated from its template in `packages/codegen/src/components/` on every `npm run
/// solar:codegen`: change the template there, never this file. What it looks like is not here. That
/// is the recipe, [SolarInteractiveCardRecipe]: the card’s fill, edge and focus ring by selection
/// and drag, its words’ and icon’s ink, and the controls it shows, read cell by cell.
///
/// One choice in a list of them (a room to book, a setting): a drag handle where it can be
/// reordered ([dragHandle]), the [control] that selects it (a Checkbox, a Radio or a Toggle,
/// following [selected] and calling [onSelectedChange], named by [selectLabel] or its title), an
/// [icon] and its [title], its [description], and the caller's [actions] (SOLAR Icon Buttons, sm).
/// [dragging] draws it lifted, as it moves. Given [onPressed], it is pressable: its title is the
/// button or link, and its hit area the whole card, its control and actions reachable above it; it
/// is focused only then. Drawn from Figma's layer tree with [SolarLayers]; pressable, the whole
/// card is its button, named by its title, and its own controls are controls of their own inside
/// it.
library;

import 'package:flutter/material.dart';

import '../generated/components/interactive_card.dart';
import '../solar_layers.dart';
import '../solar_states.dart';
import '../generated/components/draghandle.dart';
import 'solar_checkbox.dart';
import 'solar_draghandle.dart';
import 'solar_radio.dart';
import 'solar_toggle.dart';
import 'solar_theme_of.dart';

class SolarInteractiveCard extends StatelessWidget {
  const SolarInteractiveCard({
    super.key,
    required this.title,
    this.selected = false,
    this.dragging = false,
    this.control = SolarInteractiveCardControl.none,
    this.icon,
    this.description,
    this.actions,
    this.dragHandle,
    this.onSelectedChanged,
    this.selectLabel,
    this.onPressed,
    this.statesController,
  });

  final bool selected;

  final bool dragging;

  final SolarInteractiveCardControl control;

  /// What it is, its headline; its action’s name where it is pressable.
  final String title;

  /// An icon before the title.
  final Widget? icon;

  /// What it means.
  final String? description;

  /// The caller’s actions: SOLAR Icon Buttons, sm, square and secondary, laid out as Figma lays them out.
  final List<Widget>? actions;

  /// Shows a drag handle, where the list can be reordered.
  final bool? dragHandle;

  /// Called with whether it is to be selected, by its control.
  final ValueChanged<bool>? onSelectedChanged;

  /// The control’s accessible name; its title, where that is words.
  final String? selectLabel;

  /// Makes it pressable: the whole card is a button that calls it.
  final VoidCallback? onPressed;

  /// Its states, where the caller keeps them.
  final WidgetStatesController? statesController;

  /// Each layer's children, as Figma nests them.
  static const _tree = <String, List<String>>{
    'root': [
      'dragHandle',
      'toggle',
      'radioButton',
      'checkbox',
      'text',
      'actions',
    ],
    'text': ['textIcon', 'description'],
    'textIcon': ['icon', 'title'],
    'actions': ['iconButton', 'iconButton2', 'iconButton3'],
  };

  @override
  Widget build(BuildContext context) {
    final t = solarThemeOf(context);
    final p = SolarInteractiveCardProps(
      selected: selected,
      dragging: dragging,
      control: control,
    );
    final pressable = onPressed != null;
    Widget draw(Set<WidgetState> states) {
      final recipe = SolarLayerRecipe(
        lookup: (c) => SolarInteractiveCardRecipe.lookup(c, p, states),
        dimension: (c) => SolarInteractiveCardRecipe.dimension(c, p, states),
        color: (c) => SolarInteractiveCardRecipe.color(t, c, p, states),
        shadow: (c) => SolarInteractiveCardRecipe.shadow(t, c, p, states),
        textStyle: (c) => SolarInteractiveCardRecipe.textStyle(t, c, p, states),
        // A slot left empty is not drawn, and one Figma hides at rest is drawn where it is given.
        present: (l) => switch (l) {
          'icon' => icon != null,
          'description' =>
            description != null &&
                SolarInteractiveCardRecipe.present(l, p, states),
          'actions' => actions != null,
          'dragHandle' => dragHandle == true,
          'checkbox' => control == SolarInteractiveCardControl.checkbox,
          'radioButton' => control == SolarInteractiveCardControl.radio,
          'toggle' => control == SolarInteractiveCardControl.toggle,
          _ => SolarInteractiveCardRecipe.present(l, p, states),
        },
        glyph: (_) => null,
      );
      SolarLayers layers(Map<String, List<Widget>> content) => SolarLayers(
        recipe: recipe,
        tree: _tree,
        keyPrefix: 'interactiveCard',
        text: {'title': title, 'description': ?description},
        wraps: const {'title': TextAlign.start, 'description': TextAlign.start},
        slots: {'icon': ?icon},
        content: content,
        composed: {
          // The drag handle, a SOLAR DragHandle of the size the recipe names.
          'dragHandle': SolarDragHandle(
            size: SolarDragHandleSize.values.byName(
              SolarInteractiveCardRecipe.lookup(
                'dragHandle.variant.size',
                p,
                states,
              )!.substring(2),
            ),
          ),
          // The control that selects it, SOLAR's own, following selected; a Radio in a group of its own.
          'checkbox': SolarCheckbox(
            checked: selected,
            onChanged: onSelectedChanged,
            semanticLabel: selectLabel ?? title,
          ),
          'radioButton': RadioGroup<bool>(
            groupValue: selected ? true : null,
            onChanged: (_) => onSelectedChanged?.call(true),
            child: SolarRadio<bool>(
              value: true,
              semanticLabel: selectLabel ?? title,
            ),
          ),
          'toggle': SolarToggle(
            selected: selected,
            onChanged: onSelectedChanged,
            semanticLabel: selectLabel ?? title,
          ),
        },
      );
      return layers({'actions': ?actions}).layer('root');
    }

    final Widget mark = pressable
        ? SolarPressable(
            onPressed: onPressed,
            statesController: statesController,
            selected: selected,
            builder: (_, states) =>
                draw({...states, if (selected) WidgetState.selected}),
          )
        : draw({if (selected) WidgetState.selected});
    return Semantics(container: true, child: mark);
  }
}
