// Generated by @bwp-web/codegen from packages/codegen/src/components/pagenavigator.mjs. Do not edit.
/// SOLAR PageNavigator.
///
/// Generated from its template in `packages/codegen/src/components/` on every `npm run
/// solar:codegen`: change the template there, never this file. What it looks like is not here. That
/// is the recipe, [SolarPageNavigatorRecipe]: the gaps between its parts, and its position's text
/// style and ink, read cell by cell.
///
/// A linear pager for a sequence walked from start to end (a wizard, onboarding, a document): the
/// previous and next SolarPageNavButtons, disabled at the ends rather than hidden, and between them
/// where the reader is ("1 of 10", [indicator] overrides), announced as it changes. [page] (from 1)
/// and [onChanged] hold the page. No page numbers: for jumping between pages use a SolarPagination.
library;

import 'package:flutter/material.dart';

import '../generated/components/pagenavbutton.dart';
import '../generated/components/pagenavigator.dart';
import '../solar_layers.dart';
import 'solar_pagenavbutton.dart';
import 'solar_theme_of.dart';

class SolarPageNavigator extends StatelessWidget {
  const SolarPageNavigator({
    super.key,
    required this.count,
    required this.page,
    required this.onChanged,
    this.indicator,
  });

  /// How many pages there are.
  final int count;

  /// The current page, from 1.
  final int page;

  /// Called with the page gone to.
  final ValueChanged<int>? onChanged;

  /// Where the reader is, in words; "3 of 10" by default.
  final String Function(int page, int count)? indicator;

  /// Each layer's children, as Figma nests them.
  static const _tree = <String, List<String>>{
    'root': ['prevButton', 'pageIndicator', 'nextButton'],
  };

  @override
  Widget build(BuildContext context) {
    final t = solarThemeOf(context);
    const p = SolarPageNavigatorProps();
    const states = <WidgetState>{};
    return SolarLayers(
      recipe: SolarLayerRecipe(
        lookup: (c) => SolarPageNavigatorRecipe.lookup(c, p, states),
        dimension: (c) => SolarPageNavigatorRecipe.dimension(c, p, states),
        color: (c) => SolarPageNavigatorRecipe.color(t, c, p, states),
        shadow: (c) => SolarPageNavigatorRecipe.shadow(t, c, p, states),
        textStyle: (c) => SolarPageNavigatorRecipe.textStyle(t, c, p, states),
        present: (l) => SolarPageNavigatorRecipe.present(l, p, states),
        glyph: (_) => null,
      ),
      tree: _tree,
      keyPrefix: 'pageNavigator',
      text: {
        'pageIndicator': indicator?.call(page, count) ?? '$page of $count',
      },
      composed: {
        'prevButton': SolarPageNavButton(
          direction: SolarPageNavButtonDirection.prev,
          onPressed: page <= 1 ? null : () => onChanged?.call(page - 1),
        ),
        'nextButton': SolarPageNavButton(
          direction: SolarPageNavButtonDirection.next,
          onPressed: page >= count ? null : () => onChanged?.call(page + 1),
        ),
      },
      // Where the reader is, announced as it changes.
      builders: {
        'pageIndicator': (layer) => Semantics(liveRegion: true, child: layer),
      },
    ).layer('root');
  }
}
