// Generated by @bwp-web/codegen from packages/codegen/src/components/stepper.mjs. Do not edit.
/// SOLAR Stepper.
///
/// Generated from its template in `packages/codegen/src/components/` on every `npm run
/// solar:codegen`: change the template there, never this file. What it looks like is not here. That
/// is the recipe, [SolarStepperRecipe]: each type's bar, segments, lines and gaps, read cell by
/// cell.
///
/// A linear flow's progress (a wizard, onboarding, a device's setup), in two to five [steps]: those
/// before [activeStep] (from 0) complete, it active, those after upcoming, and [errorStep] in
/// error. Four types: round Steps over a progress bar (with label), SolarStepperIndicators joined
/// by lines (no label), a bar of segments (line), and horizontal Steps (line+text); where a type
/// draws no words, each step's label is read, not drawn. Given [onStepClick], a completed Step is
/// pressable, going back to it. The back and next buttons are the Multi-step Wizard's, not the
/// Stepper's.
library;

import 'package:flutter/material.dart';

import '../generated/components/step.dart';
import '../generated/components/stepper.dart';
import '../generated/components/stepper_indicator.dart';
import '../solar_layers.dart';
import 'solar_step.dart';
import 'solar_stepper_indicator.dart';
import 'solar_theme_of.dart';

class SolarStepper extends StatelessWidget {
  const SolarStepper({
    super.key,
    this.type = SolarStepperType.withLabel,
    required this.steps,
    required this.activeStep,
    this.errorStep,
    this.onStepClick,
  });

  final SolarStepperType type;

  /// The steps' labels, two to five.
  final List<String> steps;

  /// The active step, from 0; those before it are complete.
  final int activeStep;

  /// A step in error, from 0.
  final int? errorStep;

  /// Called with a completed step's index where one is chosen: completed Steps are pressable.
  final ValueChanged<int>? onStepClick;

  /// Each layer's children, as Figma nests them.
  static const _tree = <String, List<String>>{
    'root': [
      'progress',
      'steps',
      'stepperIndicator',
      'frame',
      'stepperIndicator2',
      'frame2',
      'stepperIndicator3',
      'rectangle1',
      'rectangle2',
      'rectangle3',
      'rectangle4',
      'rectangle5',
      'stepCompleteHorizontal',
      'step',
      'step3',
      'step4',
      'step5',
    ],
    'progress': ['progressRectangle2'],
    'steps': ['stepsStep', 'stepsStep2', 'stepsStep3'],
  };

  SolarStepStatus _status(int i) => i == errorStep
      ? SolarStepStatus.error
      : i < activeStep
      ? SolarStepStatus.complete
      : i == activeStep
      ? SolarStepStatus.active
      : SolarStepStatus.upcoming;

  @override
  Widget build(BuildContext context) {
    final t = solarThemeOf(context);
    final p = SolarStepperProps(type: type);
    const states = <WidgetState>{};
    final recipe = SolarLayerRecipe(
      lookup: (c) => SolarStepperRecipe.lookup(c, p, states),
      dimension: (c) => SolarStepperRecipe.dimension(c, p, states),
      color: (c) => SolarStepperRecipe.color(t, c, p, states),
      shadow: (c) => SolarStepperRecipe.shadow(t, c, p, states),
      textStyle: (c) => SolarStepperRecipe.textStyle(t, c, p, states),
      present: (_) => true,
      glyph: (_) => null,
    );
    SolarLayers layers({
      Map<String, Widget> composed = const {},
      Map<String, List<Widget>> content = const {},
    }) => SolarLayers(
      recipe: recipe,
      tree: _tree,
      keyPrefix: 'stepper',
      composed: composed,
      content: content,
    );
    // Each part in the layer Figma draws for its status, or at its place.
    String byStatus(int i, String complete, String active, String upcoming) =>
        switch (_status(i)) {
          SolarStepStatus.complete => complete,
          SolarStepStatus.upcoming => upcoming,
          _ => active,
        };
    Widget step(int i, bool round) => SolarStep(
      status: _status(i),
      type: round ? SolarStepType.round : SolarStepType.horizontal,
      label: steps[i],
      number: i + 1,
      onPressed: onStepClick != null && _status(i) == SolarStepStatus.complete
          ? () => onStepClick!(i)
          : null,
    );
    // Where a type draws no words, a step's label is read.
    Widget named(int i, Widget drawn) => Semantics(
      label: steps[i],
      selected: i == activeStep,
      child: ExcludeSemantics(child: drawn),
    );
    Widget part(String layer, [Widget? child]) =>
        (child == null ? layers() : layers(composed: {layer: child})).layer(
          layer,
        );
    final List<Widget> row;
    switch (type) {
      case SolarStepperType.withLabel:
        final n = steps.length;
        final fill = n > 1 ? activeStep.clamp(0, n - 1) / (n - 1) : 0.0;
        final bar = layers(
          content: {
            'progress': [
              FractionallySizedBox(
                alignment: AlignmentDirectional.centerStart,
                widthFactor: fill,
                child: part('progressRectangle2'),
              ),
            ],
          },
        ).layer('progress');
        row = [
          Stack(
            children: [
              Positioned(
                left: 0,
                right: 0,
                top: recipe.dimension('progress.y') ?? 0,
                child: ExcludeSemantics(child: bar),
              ),
              layers(
                content: {
                  // Each in a subtree of its own: steps of one status share a layer.
                  'steps': [
                    for (var i = 0; i < steps.length; i++)
                      KeyedSubtree(
                        key: ValueKey(i),
                        child: part(
                          byStatus(i, 'stepsStep', 'stepsStep2', 'stepsStep3'),
                          step(i, true),
                        ),
                      ),
                  ],
                },
              ).layer('steps'),
            ],
          ),
        ];
      case SolarStepperType.noLabel:
        row = [
          for (var i = 0; i < steps.length; i++) ...[
            if (i > 0)
              Expanded(
                child: ExcludeSemantics(
                  child: part(i - 1 < activeStep ? 'frame' : 'frame2'),
                ),
              ),
            named(
              i,
              part(
                byStatus(
                  i,
                  'stepperIndicator',
                  'stepperIndicator2',
                  'stepperIndicator3',
                ),
                SolarStepperIndicator(
                  number: i + 1,
                  status: switch (_status(i)) {
                    SolarStepStatus.complete =>
                      SolarStepperIndicatorStatus.completed,
                    SolarStepStatus.active =>
                      SolarStepperIndicatorStatus.active,
                    SolarStepStatus.upcoming =>
                      SolarStepperIndicatorStatus.upcoming,
                    SolarStepStatus.error => SolarStepperIndicatorStatus.error,
                  },
                ),
              ),
            ),
          ],
        ];
      case SolarStepperType.line:
        row = [
          for (var i = 0; i < steps.length; i++)
            Expanded(
              child: named(
                i,
                part(i <= activeStep ? 'rectangle1' : 'rectangle${i + 1}'),
              ),
            ),
        ];
      case SolarStepperType.lineText:
        const places = ['step', 'step', 'step3', 'step4', 'step5'];
        row = [
          for (var i = 0; i < steps.length; i++)
            Expanded(
              child: part(
                _status(i) == SolarStepStatus.complete
                    ? 'stepCompleteHorizontal'
                    : places[i < places.length ? i : places.length - 1],
                step(i, false),
              ),
            ),
        ];
    }
    return layers(content: {'root': row}).layer('root');
  }
}
