// Generated by @bwp-web/codegen from packages/codegen/src/components/event-row.mjs. Do not edit.
/// SOLAR Event Row.
///
/// Generated from its template in `packages/codegen/src/components/` on every `npm run
/// solar:codegen`: change the template there, never this file. What it looks like is not here. That
/// is the recipe, [SolarEventRowRecipe]: the row’s fill and focus ring by state, its words’ ink and
/// the More icon’s, read cell by cell.
///
/// One event of an activity feed (stack them in an ordered list, newest first): who or what did it
/// ([leading], an Avatar md for a person, an icon for a system or device), what happened ([title]),
/// the product it was in ([product]) and its context ([meta]), when ([timestamp], the words, with
/// [dateTime] the moment, for a `<time>`), and a More menu of [moreItems]. Given [onPressed], it is
/// pressable: its title is the button or link, and its hit area the whole row, the More menu
/// reachable above it; it is hovered and focused only then. Drawn from Figma's layer tree with
/// [SolarLayers]; pressable, the whole card is its button, named by its title, and its own controls
/// are controls of their own inside it.
library;

import 'package:flutter/material.dart';

import '../generated/components/event_row.dart';
import '../generated/icons.dart';
import '../solar_layers.dart';
import '../solar_menu.dart';
import '../solar_states.dart';
import '../solar_target.dart';
import 'solar_card.dart';
import 'solar_dropdown_item.dart';
import 'solar_dropdown_menu.dart';
import 'solar_theme_of.dart';

class SolarEventRow extends StatelessWidget {
  const SolarEventRow({
    super.key,
    required this.title,

    this.leading,
    this.product,
    this.meta,
    this.timestamp,
    this.moreItems,
    this.moreLabel = 'More actions',
    this.onPressed,
    this.statesController,
  });

  /// What happened, in a few words; its action’s name where it is pressable.
  final String title;

  /// Who or what did it: a SOLAR Avatar, md, or an icon.
  final Widget? leading;

  /// The product it was in.
  final String? product;

  /// Its context, in a line.
  final String? meta;

  /// When, in words (“Just now”).
  final String? timestamp;

  /// The More menu's actions: a button opens them.
  final List<SolarCardMoreItem>? moreItems;

  /// The More button's accessible name.
  final String moreLabel;

  /// Makes it pressable: the whole card is a button that calls it.
  final VoidCallback? onPressed;

  /// Its states, where the caller keeps them.
  final WidgetStatesController? statesController;

  /// Each layer's children, as Figma nests them.
  static const _tree = <String, List<String>>{
    'root': ['leading', 'content', 'timestamp', 'more'],
    'content': ['title', 'meta'],
    'meta': ['productTag', 'metaText'],
  };

  @override
  Widget build(BuildContext context) {
    final rows = moreItems;
    if (rows == null || rows.isEmpty) return _card(context, null);
    // Its own menu, under the More button.
    return SolarMenuAnchor(
      menu: SolarDropdownMenu(
        children: [
          for (final item in rows)
            Builder(
              builder: (context) => SolarDropdownItem(
                label: item.label,
                icon: item.icon,
                disabled: item.disabled,
                onPressed: () {
                  MenuController.maybeOf(context)?.close();
                  item.onSelected();
                },
              ),
            ),
        ],
      ),
      builder: (context, controller) => _card(
        context,
        () => controller.isOpen ? controller.close() : controller.open(),
      ),
    );
  }

  Widget _card(BuildContext context, VoidCallback? onMore) {
    final t = solarThemeOf(context);
    const p = SolarEventRowProps();
    final pressable = onPressed != null;
    Widget draw(Set<WidgetState> states) {
      final recipe = SolarLayerRecipe(
        lookup: (c) => SolarEventRowRecipe.lookup(c, p, states),
        dimension: (c) => SolarEventRowRecipe.dimension(c, p, states),
        color: (c) => SolarEventRowRecipe.color(t, c, p, states),
        shadow: (c) => SolarEventRowRecipe.shadow(t, c, p, states),
        textStyle: (c) => SolarEventRowRecipe.textStyle(t, c, p, states),
        // A slot left empty is not drawn.
        present: (l) => switch (l) {
          'leading' =>
            leading != null && SolarEventRowRecipe.present(l, p, states),
          'productTag' =>
            product != null && SolarEventRowRecipe.present(l, p, states),
          'metaText' =>
            meta != null && SolarEventRowRecipe.present(l, p, states),
          'timestamp' =>
            timestamp != null && SolarEventRowRecipe.present(l, p, states),
          'more' => onMore != null && SolarEventRowRecipe.present(l, p, states),
          _ => SolarEventRowRecipe.present(l, p, states),
        },
        glyph: (_) => null,
      );
      SolarLayers layers(Map<String, List<Widget>> content) => SolarLayers(
        recipe: recipe,
        tree: _tree,
        keyPrefix: 'eventRow',
        text: {
          'title': title,
          'productTag': ?product,
          'metaText': ?meta,
          'timestamp': ?timestamp,
        },
        slots: {'leading': ?leading},
        icons: const {'more': SolarIcons.moreOutline},
        content: content,
        builders: {
          'more': (glyph) => SolarTarget.inside(
            child: Semantics(
              // A node of its own, so the control keeps its name inside the card's.
              container: true,
              child: SolarPressable(
                onPressed: onMore,
                builder: (_, _) => Semantics(
                  label: moreLabel,
                  excludeSemantics: true,
                  child: glyph,
                ),
              ),
            ),
          ),
        },
      );
      return layers(const {}).layer('root');
    }

    final Widget mark = pressable
        ? SolarPressable(
            onPressed: onPressed,
            statesController: statesController,
            builder: (_, states) => draw(states),
          )
        : draw({});
    return Semantics(container: true, child: mark);
  }
}
