// Generated by @bwp-web/codegen from packages/codegen/src/components/device-card.mjs. Do not edit.
/// SOLAR Device Card.
///
/// Generated from its template in `packages/codegen/src/components/` on every `npm run
/// solar:codegen`: change the template there, never this file. What it looks like is not here. That
/// is the recipe, [SolarDeviceCardRecipe]: the card’s fill, edge and focus ring, each type’s
/// layout, its words’ and icons’ ink, and the placeholders, read cell by cell.
///
/// One device, or a batch of them ([type]): its [name], and for one device its [details] (what and
/// where it is), for a batch its [count] and the caller's [devices] (a SOLAR Dropdown of them, md);
/// its health, a SOLAR Tag of [tag]'s words in [tagStatus] (success by default), and the caller's
/// [action] (a SOLAR Button, sm and secondary, such as "Try again"). [loading] draws Figma's
/// placeholders, announced busy. Given [onPressed], it is pressable: its name is the button or
/// link, and its hit area the whole card, its action and devices reachable above it; it is focused
/// only then. Drawn from Figma's layer tree with [SolarLayers]; pressable, the whole card is its
/// button, named by its name, and its own controls are controls of their own inside it.
library;

import 'package:flutter/material.dart';

import '../generated/components/device_card.dart';
import '../generated/icons.dart';
import '../solar_layers.dart';
import '../solar_states.dart';
import '../generated/components/tag.dart';
import 'solar_tag.dart';
import 'solar_theme_of.dart';

class SolarDeviceCard extends StatelessWidget {
  const SolarDeviceCard({
    super.key,
    required this.name,
    this.loading = false,
    this.type = SolarDeviceCardType.single,
    this.details,
    this.count,
    this.tag,
    this.tagStatus,
    this.action,
    this.devices,
    this.onPressed,
    this.statesController,
  });

  final bool loading;

  final SolarDeviceCardType type;

  /// The device’s or the batch’s name; its action’s name where it is pressable.
  final String name;

  /// What and where it is, in a line.
  final String? details;

  /// How many a batch holds (“3 devices”).
  final String? count;

  /// Its health, in a SOLAR Tag’s words.
  final String? tag;

  /// The health’s status; success by default.
  final SolarTagStatus? tagStatus;

  /// The caller’s action: a SOLAR Button, sm and secondary (“Try again”).
  final Widget? action;

  /// A batch’s devices: the caller’s SOLAR Dropdown, md.
  final Widget? devices;

  /// Makes it pressable: the whole card is a button that calls it.
  final VoidCallback? onPressed;

  /// Its states, where the caller keeps them.
  final WidgetStatesController? statesController;

  /// Each layer's children, as Figma nests them.
  static const _tree = <String, List<String>>{
    'root': ['icon', 'content', 'tag', 'button', 'headline', 'serialLocation'],
    'icon': ['iconIconDevice', 'iconIconProgress'],
    'content': ['contentName', 'details', 'contentSkeleton'],
    'headline': ['headlineIcon', 'headlineContent', 'headlineTag'],
    'headlineIcon': ['headlineIconIconDevice', 'headlineIconIconProgress'],
    'headlineContent': [
      'headlineContentName',
      'contentCount',
      'row',
      'headlineContentSkeleton',
    ],
    'serialLocation': ['devices'],
    'row': ['rowName', 'rowCount'],
  };

  @override
  Widget build(BuildContext context) {
    final t = solarThemeOf(context);
    final p = SolarDeviceCardProps(loading: loading, type: type);
    // Pressable while it loads too, as Figma draws a loading card hovered.
    final pressable = onPressed != null;
    Widget draw(Set<WidgetState> states) {
      final recipe = SolarLayerRecipe(
        lookup: (c) => SolarDeviceCardRecipe.lookup(c, p, states),
        dimension: (c) => SolarDeviceCardRecipe.dimension(c, p, states),
        color: (c) => SolarDeviceCardRecipe.color(t, c, p, states),
        shadow: (c) => SolarDeviceCardRecipe.shadow(t, c, p, states),
        textStyle: (c) => SolarDeviceCardRecipe.textStyle(t, c, p, states),
        // A slot left empty is not drawn, and one Figma hides at rest is drawn where it is given.
        present: (l) => switch (l) {
          'details' =>
            details != null && SolarDeviceCardRecipe.present(l, p, states),
          'contentCount' =>
            count != null && SolarDeviceCardRecipe.present(l, p, states),
          'rowCount' =>
            count != null && SolarDeviceCardRecipe.present(l, p, states),
          'tag' => tag != null && SolarDeviceCardRecipe.present(l, p, states),
          'headlineTag' =>
            tag != null && SolarDeviceCardRecipe.present(l, p, states),
          'button' => action != null,
          'devices' =>
            devices != null && SolarDeviceCardRecipe.present(l, p, states),
          _ => SolarDeviceCardRecipe.present(l, p, states),
        },
        glyph: (_) => null,
      );
      SolarLayers layers(Map<String, List<Widget>> content) => SolarLayers(
        recipe: recipe,
        tree: _tree,
        keyPrefix: 'deviceCard',
        text: {
          'headlineContentName': name,
          'rowName': name,
          'contentName': name,
          'details': ?details,
          'contentCount': ?count,
          'rowCount': ?count,
        },
        wraps: const {'details': TextAlign.start},
        slots: {'button': ?action, 'devices': ?devices},
        icons: const {
          'iconIconDevice': SolarIcons.deviceOutline,
          'iconIconProgress': SolarIcons.progressOutline,
          'headlineIconIconDevice': SolarIcons.deviceOutline,
          'headlineIconIconProgress': SolarIcons.progressOutline,
        },
        content: content,
        composed: {
          // Its health, a SOLAR Tag in the status the caller gives, with its dot on one device's card.
          'tag': SolarTag(
            status: tagStatus ?? SolarTagStatus.success,
            label: tag,
            indicator: true,
          ),
          'headlineTag': SolarTag(
            status: tagStatus ?? SolarTagStatus.success,
            label: tag,
          ),
        },
      );
      return layers(const {}).layer('root');
    }

    final Widget mark = pressable
        ? SolarPressable(
            onPressed: onPressed,
            statesController: statesController,
            builder: (_, states) => Semantics(
              // Loading, where its title is not drawn (Card's; a Device Card's is), the button is
              // named by it all the same.
              label:
                  loading &&
                      ![
                        'contentName',
                        'headlineContentName',
                        'rowName',
                      ].any((l) => SolarDeviceCardRecipe.present(l, p, states))
                  ? name
                  : null,
              child: draw(states),
            ),
          )
        : draw({});
    return Semantics(
      container: true,
      // Loading, it says so, as the web's aria-busy does.
      label: loading ? 'Loading' : null,
      child: mark,
    );
  }
}
