// Generated by @bwp-web/codegen from packages/codegen/src/components/breadcrumb-item.mjs. Do not edit.
/// SOLAR Breadcrumb Item.
///
/// Generated from its template in `packages/codegen/src/components/` on every `npm run
/// solar:codegen`: change the template there, never this file. What it looks like is not here. That
/// is the recipe, [SolarBreadcrumbItemRecipe]: its words’ text style and ink by state, read cell by
/// cell.
///
/// Bespoke: one segment of a SolarBreadcrumbs trail, drawn from Figma's layer tree with
/// [SolarLayers]. A link to an ancestor page, pressable and announced as a link, where it has
/// [onPressed]; the current page, the trail's last, as text, no link, as its description says; a
/// [disabled] one as text. A focused link draws SOLAR's focus ring. Use it inside a
/// SolarBreadcrumbs.
library;

import 'package:flutter/material.dart';

import '../generated/components/breadcrumb_item.dart';
import '../solar_layers.dart';
import '../solar_states.dart';
import 'solar_theme_of.dart';

class SolarBreadcrumbItem extends StatelessWidget {
  const SolarBreadcrumbItem({
    super.key,
    this.type = SolarBreadcrumbItemType.link,
    this.disabled = false,
    required this.label,
    this.onPressed,
    this.statesController,
  });

  final SolarBreadcrumbItemType type;
  final bool disabled;

  /// The page's name.
  final String label;

  /// Called when it is tapped, which makes it a control of its own; without it, it takes the
  /// states of the control around it (a Button's).
  final VoidCallback? onPressed;

  /// Its states, where the caller keeps them.
  final WidgetStatesController? statesController;

  /// Each layer's children, as Figma nests them.
  static const _tree = <String, List<String>>{
    'root': ['label'],
  };

  @override
  Widget build(BuildContext context) {
    final t = solarThemeOf(context);
    final p = SolarBreadcrumbItemProps(type: type, disabled: disabled);
    Widget draw(Set<WidgetState> states) => SolarLayers(
      recipe: SolarLayerRecipe(
        lookup: (c) => SolarBreadcrumbItemRecipe.lookup(c, p, states),
        dimension: (c) => SolarBreadcrumbItemRecipe.dimension(c, p, states),
        color: (c) => SolarBreadcrumbItemRecipe.color(t, c, p, states),
        shadow: (c) => SolarBreadcrumbItemRecipe.shadow(t, c, p, states),
        textStyle: (c) => SolarBreadcrumbItemRecipe.textStyle(t, c, p, states),
        present: (l) => SolarBreadcrumbItemRecipe.present(l, p, states),
        glyph: (_) => null,
      ),
      tree: _tree,
      keyPrefix: 'breadcrumbItem',
      text: {'label': label},
    ).layer('root');
    // A control of its own only when it has something to do; otherwise it takes the states of
    // the control around it (a Counter in a Button).
    final mark = onPressed == null && statesController == null
        ? SolarStatesBuilder(builder: (_, states) => draw(states))
        : SolarPressable(
            onPressed: type == SolarBreadcrumbItemType.link && !disabled
                ? onPressed
                : null,
            statesController: statesController,
            link: true,
            target: true,
            builder: (_, states) => draw(states),
          );
    return mark;
  }
}
