// Generated by @bwp-web/codegen from packages/codegen/src/components/pagination.mjs. Do not edit.
/// SOLAR Pagination.
///
/// Generated from its template in `packages/codegen/src/components/` on every `npm run
/// solar:codegen`: change the template there, never this file. What it looks like is not here. That
/// is the recipe, [SolarPaginationRecipe]: the gaps between its items, read cell by cell.
///
/// A list's pages, where their count is known and a reader jumps between them: the previous arrow,
/// the pages, the next arrow. The pages shown are the first, the last and the current ± 1, with
/// three at the end the current is near (1 2 3 … 12), a gap of more than one page an ellipsis, one
/// of one page that page. The current page is announced selected; the arrows are disabled at the
/// ends. [page] (from 1) and [onChanged] hold the page. A single page draws nothing. For a
/// step-by-step flow use a SolarPageNavigator.
library;

import 'package:flutter/material.dart';

import '../generated/components/pagination.dart';
import '../generated/components/paginationnav.dart';
import '../solar_layers.dart';
import 'solar_paginationellipsis.dart';
import 'solar_paginationitem.dart';
import 'solar_paginationnav.dart';
import 'solar_theme_of.dart';

/// The pages shown for [page] of [count], and the gaps between them (null), as Figma draws them:
/// the first, the last, the current ± 1, and three at the end the current is near; a gap of one
/// page is that page.
List<int?> solarPagesOf(int page, int count) {
  final shown = {1, count, page - 1, page, page + 1};
  if (page <= 2) shown.addAll([1, 2, 3]);
  if (page >= count - 1) shown.addAll([count - 2, count - 1, count]);
  final pages = shown.where((p) => p >= 1 && p <= count).toList()..sort();
  final out = <int?>[];
  for (var i = 0; i < pages.length; i++) {
    if (i > 0 && pages[i] - pages[i - 1] == 2) out.add(pages[i] - 1);
    if (i > 0 && pages[i] - pages[i - 1] > 2) out.add(null);
    out.add(pages[i]);
  }
  return out;
}

class SolarPagination extends StatelessWidget {
  const SolarPagination({
    super.key,
    required this.count,
    required this.page,
    required this.onChanged,
  });

  /// How many pages there are.
  final int count;

  /// The current page, from 1.
  final int page;

  /// Called with the page chosen.
  final ValueChanged<int>? onChanged;

  /// Each layer's children, as Figma nests them.
  static const _tree = <String, List<String>>{
    'root': [
      'previous',
      'page1',
      'page2',
      'page3',
      'paginationEllipsis',
      'page12',
      'next',
    ],
  };

  @override
  Widget build(BuildContext context) {
    // A single page is no pagination, as its description says.
    if (count <= 1) return const SizedBox.shrink();
    final t = solarThemeOf(context);
    const p = SolarPaginationProps();
    const states = <WidgetState>{};
    final recipe = SolarLayerRecipe(
      lookup: (c) => SolarPaginationRecipe.lookup(c, p, states),
      dimension: (c) => SolarPaginationRecipe.dimension(c, p, states),
      color: (c) => SolarPaginationRecipe.color(t, c, p, states),
      shadow: (c) => SolarPaginationRecipe.shadow(t, c, p, states),
      textStyle: (c) => SolarPaginationRecipe.textStyle(t, c, p, states),
      present: (_) => true,
      glyph: (_) => null,
    );
    void go(int to) => onChanged?.call(to);
    final items = solarPagesOf(page, count);
    final pages = items.whereType<int>().length;
    // Each item drawn in the layer Figma draws at its place.
    final drawn = <(String, Widget)>[
      (
        'previous',
        SolarPaginationNav(
          direction: SolarPaginationNavDirection.previous,
          disabled: page <= 1,
          onPressed: () => go(page - 1),
        ),
      ),
    ];
    var seen = 0;
    for (final item in items) {
      if (item == null) {
        drawn.add(('paginationEllipsis', const SolarPaginationEllipsis()));
        continue;
      }
      final at = seen++;
      drawn.add((
        at == pages - 1
            ? 'page12'
            : at == 0
            ? 'page1'
            : at == 1
            ? 'page2'
            : 'page3',
        SolarPaginationItem(
          page: item,
          selected: item == page,
          onPressed: () => go(item),
        ),
      ));
    }
    drawn.add((
      'next',
      SolarPaginationNav(
        direction: SolarPaginationNavDirection.next,
        disabled: page >= count,
        onPressed: () => go(page + 1),
      ),
    ));
    Widget layerOf((String, Widget) d) => SolarLayers(
      recipe: recipe,
      tree: _tree,
      keyPrefix: 'pagination',
      composed: {d.$1: d.$2},
    ).layer(d.$1);
    return SolarLayers(
      recipe: recipe,
      tree: _tree,
      keyPrefix: 'pagination',
      // Each in a subtree of its own: several items share a layer (the middle pages, two gaps).
      content: {
        'root': [
          for (var i = 0; i < drawn.length; i++)
            KeyedSubtree(key: ValueKey(i), child: layerOf(drawn[i])),
        ],
      },
    ).layer('root');
  }
}
