// Generated by @bwp-web/codegen from packages/codegen/src/components/button.mjs. Do not edit.
/// SOLAR Button.
///
/// Generated from its template in `packages/codegen/src/components/` on every `npm run
/// solar:codegen`: change the template there, never this file. What it looks like is not here. That
/// is the recipe, [SolarButtonRecipe], which regenerates from Figma on every `solar:codegen`. This
/// file is behaviour: the props, the slots, loading and accessibility, with the same props as the
/// React Button.
///
/// It wraps Flutter's FilledButton, which supplies focus, keyboard activation, hover and press;
/// [SolarButtonRecipe.style] restyles it.
library;

import 'package:flutter/material.dart';

import '../generated/components/button.dart';
import '../generated/components/spinner.dart';
import '../solar_button_themes.dart';
import '../solar_own_size.dart';
import '../solar_states.dart';
import 'solar_spinner.dart';
import 'solar_theme_of.dart';

class SolarButton extends StatelessWidget {
  const SolarButton({
    super.key,
    required this.onPressed,
    this.child,
    this.size = SolarButtonSize.md,
    this.variant = SolarButtonVariant.primary,
    this.loading = false,
    this.danger = false,
    this.iconLeading,
    this.iconTrailing,
    this.counter,
    this.semanticLabel,
    this.focusNode,
    this.autofocus = false,
    this.statesController,
  }) : assert(
         child != null || semanticLabel != null,
         'SOLAR Button: an icon-only button needs a semanticLabel.',
       );

  /// Called when the button is tapped; null disables it, as for any Flutter button.
  final VoidCallback? onPressed;

  /// The label.
  final Widget? child;

  final SolarButtonSize size;
  final SolarButtonVariant variant;
  final bool loading;
  final bool danger;

  /// The icon before the label. It reinforces the action: a bin beside "Delete".
  final Widget? iconLeading;

  /// The icon after the label. It indicates direction: an arrow beside "Continue".
  final Widget? iconTrailing;

  /// A count shown after the label: a `SolarCounter`, which takes the button's states.
  final Widget? counter;

  /// The accessible name, required when there is no label.
  final String? semanticLabel;

  final FocusNode? focusNode;
  final bool autofocus;
  final WidgetStatesController? statesController;

  /// Whether it is disabled: by a null [onPressed], as Flutter's own buttons are, not a parameter of
  /// its own.
  bool get disabled => onPressed == null;

  @override
  Widget build(BuildContext context) {
    final t = solarThemeOf(context);
    // Disabled wins over loading, as in Figma's state order, so a disabled button shows no spinner.
    final busy = loading && !disabled;
    final p = SolarButtonProps(
      size: size,
      variant: variant,
      disabled: disabled,
      loading: busy,
      danger: danger,
    );
    const rest = <WidgetState>{};
    bool shows(String layer) => SolarButtonRecipe.present(layer, p, rest);
    final gap = SolarButtonRecipe.dimension('root.gap', p, rest) ?? 0;

    final parts = <Widget>[
      ?iconLeading,
      // Loading hides the label but keeps its room, as Figma does, so the button does not resize;
      // a screen reader still reads it.
      if (child != null)
        Visibility(
          visible: shows('label'),
          maintainSize: true,
          maintainAnimation: true,
          maintainState: true,
          maintainSemantics: true,
          child: child!,
        ),
      // The counter's height is the recipe's; the badge inside it is the caller's.
      if (counter != null)
        SizedBox(
          height: SolarButtonRecipe.dimension('counter.height', p, rest),
          child: Center(widthFactor: 1, child: counter),
        ),
      ?iconTrailing,
    ];
    final content = Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        for (final (i, part) in parts.indexed) ...[
          if (i > 0) SizedBox(width: gap),
          part,
        ],
      ],
    );

    // The button's states are shared with what it holds, so a Counter in it follows its hover,
    // press and disabled colours, as Figma draws it (SolarStatesScope).
    Widget button = SolarStatesScope(
      controller: statesController,
      builder: (context, states) => FilledButton(
        onPressed: disabled || busy ? null : onPressed,
        // The recipe, under the app's SolarButtonThemeData where its theme has one.
        style: SolarButtonThemeData.styled(
          context,
          SolarButtonRecipe.style(t, p),
        ),
        focusNode: focusNode,
        autofocus: autofocus,
        statesController: states,
        child: Stack(
          alignment: Alignment.center,
          children: [
            content,
            if (shows('spinner'))
              // Which Spinner, Figma picks per Button variant; its `style` axis is the Spinner's
              // `variant` prop.
              ExcludeSemantics(
                child: SolarSpinner(
                  size: SolarSpinnerSize.values.byName(
                    SolarButtonRecipe.lookup(
                      'spinner.variant.size',
                      p,
                      rest,
                    )!.substring(2),
                  ),
                  variant: SolarSpinnerVariant.values.firstWhere(
                    (v) =>
                        'k:${v.figma}' ==
                        SolarButtonRecipe.lookup(
                          'spinner.variant.style',
                          p,
                          rest,
                        ),
                  ),
                ),
              ),
          ],
        ),
      ),
    );
    if (semanticLabel != null) {
      // Merged, so the name and the button's own tap action are one node for a screen reader: a
      // Semantics label alone makes a second node, and the button inside it stays unnamed.
      button = MergeSemantics(
        child: Semantics(label: semanticLabel, child: button),
      );
    }
    // Its own size wherever it is put, as Figma draws it, not the width a ListView forces on a
    // Flutter button (owner decision 2026-09-25); a parent that shares its row gives SolarFill.
    return SolarOwnSize(child: button);
  }
}
