// Generated by @bwp-web/codegen from packages/codegen/src/components/action-card.mjs. Do not edit.
/// SOLAR Action Card.
///
/// Generated from its template in `packages/codegen/src/components/` on every `npm run
/// solar:codegen`: change the template there, never this file. What it looks like is not here. That
/// is the recipe, [SolarActionCardRecipe]: the surface’s fill, edge, shadow and focus ring by
/// status and state, its words’ and icons’ ink, read cell by cell.
///
/// A card that asks for one thing (set up a room, fix a fault): an [icon] and its [title], a More
/// menu of [moreItems], the content (the [description], in Figma's words' look, then the caller's
/// children), and its calls to action, the caller's SOLAR Buttons (sm, as Figma draws them): the
/// [primaryAction] and [secondaryAction] at rest, the primary alone once [done] (secondary) or in
/// [danger] (a danger primary). Given [onPressed], it is pressable: its title is the button or
/// link, and its hit area the whole card, its Buttons and the More menu reachable above it; it is
/// hovered and focused only then. Drawn from Figma's layer tree with [SolarLayers]; pressable, the
/// whole card is its button, named by its title, and its own controls are controls of their own
/// inside it.
library;

import 'package:flutter/material.dart';

import '../generated/components/action_card.dart';
import '../generated/icons.dart';
import '../solar_layers.dart';
import '../solar_menu.dart';
import '../solar_states.dart';
import '../solar_target.dart';
import 'solar_card.dart';
import 'solar_dropdown_item.dart';
import 'solar_dropdown_menu.dart';
import 'solar_theme_of.dart';

class SolarActionCard extends StatelessWidget {
  const SolarActionCard({
    super.key,
    required this.title,
    this.status = SolarActionCardStatus.$default,
    this.icon,
    this.description,
    this.primaryAction,
    this.secondaryAction,
    this.children = const [],
    this.moreItems,
    this.moreLabel = 'More actions',
    this.onPressed,
    this.statesController,
  });

  final SolarActionCardStatus status;

  /// What it asks for, in a few words; its action’s name where it is pressable.
  final String title;

  /// An icon before the title.
  final Widget? icon;

  /// The content’s words, in the look Figma draws them.
  final String? description;

  /// The call to action: a SOLAR Button, sm; once done or in danger, the only one.
  final Widget? primaryAction;

  /// Another at rest, beside it: a SOLAR Button, sm and secondary.
  final Widget? secondaryAction;

  /// The caller's content, after the description.
  final List<Widget> children;

  /// The More menu's actions: a button opens them.
  final List<SolarCardMoreItem>? moreItems;

  /// The More button's accessible name.
  final String moreLabel;

  /// Makes it pressable: the whole card is a button that calls it.
  final VoidCallback? onPressed;

  /// Its states, where the caller keeps them.
  final WidgetStatesController? statesController;

  /// Each layer's children, as Figma nests them.
  static const _tree = <String, List<String>>{
    'root': ['title', 'content', 'cta', 'button'],
    'title': ['icon', 'titleTitle', 'iconMore'],
    'content': ['description'],
    'cta': ['primaryCTA', 'secondaryCTA'],
  };

  @override
  Widget build(BuildContext context) {
    final rows = moreItems;
    if (rows == null || rows.isEmpty) return _card(context, null);
    // Its own menu, under the More button.
    return SolarMenuAnchor(
      menu: SolarDropdownMenu(
        children: [
          for (final item in rows)
            Builder(
              builder: (context) => SolarDropdownItem(
                label: item.label,
                icon: item.icon,
                onPressed: item.disabled
                    ? null
                    : () {
                        MenuController.maybeOf(context)?.close();
                        item.onSelected();
                      },
              ),
            ),
        ],
      ),
      builder: (context, controller) => _card(
        context,
        () => controller.isOpen ? controller.close() : controller.open(),
      ),
    );
  }

  Widget _card(BuildContext context, VoidCallback? onMore) {
    final t = solarThemeOf(context);
    final p = SolarActionCardProps(status: status);
    final pressable = onPressed != null;
    Widget draw(Set<WidgetState> states) {
      final recipe = SolarLayerRecipe(
        lookup: (c) => SolarActionCardRecipe.lookup(c, p, states),
        dimension: (c) => SolarActionCardRecipe.dimension(c, p, states),
        color: (c) => SolarActionCardRecipe.color(t, c, p, states),
        shadow: (c) => SolarActionCardRecipe.shadow(t, c, p, states),
        textStyle: (c) => SolarActionCardRecipe.textStyle(t, c, p, states),
        // A slot left empty is not drawn.
        present: (l) => switch (l) {
          'icon' => icon != null && SolarActionCardRecipe.present(l, p, states),
          'description' =>
            description != null && SolarActionCardRecipe.present(l, p, states),
          'primaryCTA' =>
            primaryAction != null &&
                SolarActionCardRecipe.present(l, p, states),
          'button' =>
            primaryAction != null &&
                SolarActionCardRecipe.present(l, p, states),
          'secondaryCTA' =>
            secondaryAction != null &&
                SolarActionCardRecipe.present(l, p, states),
          'iconMore' =>
            onMore != null && SolarActionCardRecipe.present(l, p, states),
          _ => SolarActionCardRecipe.present(l, p, states),
        },
        glyph: (_) => null,
      );
      SolarLayers layers(Map<String, List<Widget>> content) => SolarLayers(
        recipe: recipe,
        tree: _tree,
        keyPrefix: 'actionCard',
        text: {'titleTitle': title, 'description': ?description},
        wraps: const {
          'titleTitle': TextAlign.start,
          'description': TextAlign.start,
        },
        slots: {
          'icon': ?icon,
          'primaryCTA': ?primaryAction,
          'button': ?primaryAction,
          'secondaryCTA': ?secondaryAction,
        },
        icons: const {'iconMore': SolarIcons.moreOutline},
        content: content,
        builders: {
          'iconMore': (glyph) => SolarTarget.inside(
            child: Semantics(
              // A node of its own, so the control keeps its name inside the card's.
              container: true,
              child: SolarPressable(
                onPressed: onMore,
                builder: (_, _) => Semantics(
                  label: moreLabel,
                  excludeSemantics: true,
                  child: glyph,
                ),
              ),
            ),
          ),
        },
      );
      final figma = layers(const {});
      return layers({
        'content': [
          if (description != null) figma.layer('description'),
          ...children,
        ],
      }).layer('root');
    }

    final Widget mark = pressable
        ? SolarPressable(
            onPressed: onPressed,
            statesController: statesController,
            builder: (_, states) => draw(states),
          )
        : draw({});
    return Semantics(container: true, child: mark);
  }
}
