import { join } from 'node:path';
import { flattenSpec } from '../spec.mjs';
import { packagesDir } from '../util/paths.mjs';
import { writeGenerated } from '../util/write.mjs';
import { entry, writeManifest } from './manifest.mjs';
import { shadowLayers, shadowToCss } from './shadow.mjs';

const OUT_DIR = join(packagesDir, 'styles', 'src', 'generated', 'css');
const cssVar = (name) => `--solar-${name.replaceAll('.', '-')}`;

export function cssLiteral(type, value) {
  switch (type) {
    case 'color':
      return String(value);
    case 'dimension':
      return typeof value === 'number' ? `${value}px` : String(value);
    case 'duration':
      return typeof value === 'number' ? `${value}ms` : String(value);
    case 'number':
    case 'fontWeight':
      return String(value);
    case 'fontFamily':
      return /\s/.test(value) ? `"${value}"` : String(value);
    case 'cubicBezier':
      return `cubic-bezier(${value.join(', ')})`;
    default:
      throw new Error(`no CSS literal for type ${type}`);
  }
}

export function renderCss(spec) {
  const tokens = flattenSpec(spec);
  const index = new Map(tokens.map((t) => [t.name, t]));
  const manifest = {};
  const root = [];
  const dark = [];
  const mobile = [];

  for (const t of tokens) {
    if (t.type === 'typography') continue; // parts already exist as type.* tokens
    const name = cssVar(t.name);

    if (t.type === 'shadow') {
      const lightLayers = shadowLayers(index, { $value: t.value }, 'light');
      const darkLayers = shadowLayers(index, { $value: t.value }, 'dark');
      root.push(`  ${name}: ${shadowToCss(lightLayers)};`);
      dark.push(`  ${name}: ${shadowToCss(darkLayers)};`);
      manifest[t.name] = entry(
        'shadow',
        shadowToCss(lightLayers),
        lightLayers,
        {
          light: lightLayers,
          dark: darkLayers,
        },
      );
      continue;
    }

    const literal = cssLiteral(t.type, t.value);
    root.push(`  ${name}: ${literal};`);

    // The literal for the other mode is computed before it is pushed, because the mobile rule
    // carries an extra level of indentation that must not reach the manifest.
    let modes;
    if (t.modes?.dark !== undefined) {
      const darkLiteral = cssLiteral(t.type, t.modes.dark);
      dark.push(`  ${name}: ${darkLiteral};`);
      modes = { light: literal, dark: darkLiteral };
    }
    if (t.modes?.mobile !== undefined) {
      const mobileLiteral = cssLiteral(t.type, t.modes.mobile);
      mobile.push(`    ${name}: ${mobileLiteral};`);
      modes = { desktop: literal, mobile: mobileLiteral };
    }
    manifest[t.name] = entry(t.type, literal, literal, modes);
  }

  const css =
    `/* SOLAR design tokens. Generated by @bwp-web/codegen from spec/tokens.json. Do not edit. */\n` +
    `:root {\n${root.join('\n')}\n}\n\n` +
    `[data-theme='dark'] {\n${dark.join('\n')}\n}\n\n` +
    `@media (max-width: 767.98px) {\n  :root {\n${mobile.join('\n')}\n  }\n}\n\n` +
    `@media (prefers-reduced-motion: reduce) {\n  * {\n    transition-duration: 0ms !important;\n    animation-duration: 0ms !important;\n  }\n}\n`;

  return { css, manifest };
}

export function emitCss(spec, fileVersion) {
  const { css, manifest } = renderCss(spec);
  writeGenerated(join(OUT_DIR, 'tokens.css'), css);
  writeManifest({
    target: 'css',
    dir: OUT_DIR,
    entries: manifest,
    fileVersion,
  });
  return Object.keys(manifest).length;
}
