/**
 * Emits the SOLAR icons and logos as Dart data.
 *
 * **Data only.** The types, the widgets and the painter are hand written in
 * `packages/solar_flutter/lib/src/solar_icon.dart`, for the same reason `icon.tsx` is hand
 * written on the React side: a generated file is a recipe -- a viewBox and some path strings --
 * and everything that is behaviour is decided once, outside the machine-owned tree.
 *
 * **One static const per variant, and deliberately no map.** Dart tree-shakes static fields
 * individually, the way `SolarIconSize.lg` already does in the token file, so taking one icon
 * costs one icon. A `Map<String, SolarVector>` would reference every field, and any build that
 * touched the class would retain all 358 KB of path data. The constants also autocomplete,
 * which a string-keyed map does not.
 *
 * **The Teams mark is absent.** `logos/os-logo/teams.svg` is 11 radial gradients, one linear
 * gradient and every `fill-opacity` in the corpus, which the vector IR cannot represent;
 * redrawing it in a hand-written painter is disproportionate work for one third-party mark and
 * approximating it would invent a brand colour. React and the raw SVG output both carry the real
 * mark, so the gap is one platform's, recorded in the `logo.os-logo.teams` deviation. The
 * emitter asserts it is the *only* variant it skipped, so a second unsupported asset fails the
 * build instead of disappearing quietly.
 */

import { join } from 'node:path';
import { packagesDir } from '../util/paths.mjs';
import { geometryDigest, logoDigest } from '../util/digest.mjs';
import { camel, pascal, quote } from '../util/naming.mjs';
import { byCodeUnit } from '../util/sort.mjs';
import { writeGenerated } from '../util/write.mjs';
import { dartColor } from './flutter.mjs';

const OUT_DIR = join(packagesDir, 'solar_flutter', 'lib', 'src', 'generated');

const HEADER =
  '// Generated by @bwp-web/codegen from spec/icons.json. Do not edit.\n';

/**
 * The one asset the Flutter target does not carry, spelled out rather than inferred.
 *
 * Written as `<set>.<variant>`. The emitter compares what it actually skipped against this, so
 * a second unrepresentable mark stops the build.
 */
export const OMITTED_VARIANTS = ['os-logo.teams'];

const dbl = (n) => (Number.isInteger(n) ? `${n}.0` : String(n));

/**
 * A Dart field name for one variant of one asset: `chevron-right` + `outline` becomes
 * `chevronRightOutline`.
 *
 * No `$` escaping, unlike the token emitter: a token tail can be `2xs` or `default`, but every
 * one of the 680 icon names is a stem followed by `Outline` or `Solid`, so none can start with
 * a digit and none can be a reserved word. That is asserted rather than assumed.
 */
export function dartVariantName(stem, variant) {
  const name = camel(stem) + pascal(variant);
  if (!/^[a-z][A-Za-z0-9]*$/.test(name))
    throw new Error(
      `${stem}/${variant} produces "${name}", which is not a plain Dart field name`,
    );
  return name;
}

// A doc comment is line based, so only a newline could break out of it; the catalog descriptions
// are single-line prose today, and collapsing rather than trusting that keeps it true.
const line = (text) => String(text).replace(/\s+/g, ' ').trim();

const pathLiteral = (path) =>
  `SolarVectorPath(${quote(path.d)}` +
  (path.fillRule === 'evenodd' ? ', evenOdd: true' : '') +
  (path.fill ? `, fill: ${dartColor(path.fill)}` : '') +
  ')';

function vectorLiteral(name, geometry, doc) {
  const [minX, minY, width, height] = geometry.viewBox;
  // The type carries an extent, not a rectangle: nothing in the corpus is offset, and silently
  // dropping an offset would draw the mark in the wrong place.
  if (minX !== 0 || minY !== 0)
    throw new Error(
      `${name}: viewBox "${geometry.viewBox.join(' ')}" does not start at the origin, ` +
        'which SolarVector cannot represent',
    );
  return (
    doc.map((text) => `  /// ${text}\n`).join('  ///\n') +
    `  static const SolarVector ${name} = SolarVector(\n` +
    `    width: ${dbl(width)},\n` +
    `    height: ${dbl(height)},\n` +
    '    paths: <SolarVectorPath>[\n' +
    geometry.paths.map((p) => `      ${pathLiteral(p)},\n`).join('') +
    '    ],\n' +
    '  );\n'
  );
}

const CLASS_DOC =
  '/// Every SOLAR %WHAT%, one `static const` per variant.\n' +
  '///\n' +
  '/// Static fields tree-shake individually, so taking one costs one: there is deliberately no\n' +
  '/// `Map<String, SolarVector>` here, because a map would reference every field and pull all of\n' +
  '/// the path data into any build that touched the class.\n';

/**
 * Renders both Dart files and the manifest, as data.
 *
 * Returning strings rather than writing them keeps the tests off the disk, so "no #111111
 * anywhere" is a property of what this function produces rather than of whatever is checked in.
 */
export function renderFlutterIcons(spec) {
  const icons = {};
  const iconMembers = [];

  for (const stem of Object.keys(spec.icons).sort(byCodeUnit)) {
    const icon = spec.icons[stem];
    const variants = {};
    for (const variant of ['outline', 'solid']) {
      const geometry = icon.variants[variant];
      const name = dartVariantName(stem, variant);
      iconMembers.push(
        vectorLiteral(name, geometry, [
          line(icon.description),
          `The ${variant} variant of ${icon.name}, in the ${icon.category} category.`,
        ]),
      );
      variants[variant] = {
        constant: name,
        viewBox: geometry.viewBox.join(' '),
        pathCount: geometry.paths.length,
        digest: geometryDigest(geometry.paths),
      };
    }
    icons[stem] = { variants };
  }

  const logos = {};
  const logoMembers = [];
  const omitted = [];

  for (const set of Object.keys(spec.logos).sort(byCodeUnit)) {
    const logo = spec.logos[set];
    // The app icons are PNGs. They have no vector to emit and are not omissions: React ships
    // them as data URLs and a Flutter app loads them as image assets.
    if (logo.raster) continue;
    // LogoBiamp becomes biamp*, LogoOs becomes os*: the constants are named after the component
    // the React side exports, not after the Figma set, so the two targets read the same.
    const prefix = camel(logo.component.replace(/^Logo/, ''));
    const variants = {};
    for (const slug of Object.keys(logo.variants).sort(byCodeUnit)) {
      const geometry = logo.variants[slug];
      if (geometry.unsupported) {
        omitted.push(`${set}.${slug}`);
        continue;
      }
      const name = dartVariantName(prefix, slug);
      logoMembers.push(
        vectorLiteral(name, geometry, [
          `${logo.name}, ${slug}. A brand mark: it carries its own colours and is never tinted.`,
        ]),
      );
      variants[slug] = {
        constant: name,
        viewBox: geometry.viewBox.join(' '),
        pathCount: geometry.paths.length,
        digest: logoDigest(geometry.paths),
      };
    }
    logos[set] = { component: logo.component, variants };
  }

  if (
    omitted.length !== OMITTED_VARIANTS.length ||
    omitted.some((name, i) => name !== OMITTED_VARIANTS[i])
  )
    throw new Error(
      `Flutter skipped ${omitted.join(', ') || 'nothing'}, but only ` +
        `${OMITTED_VARIANTS.join(', ')} may be skipped; an asset the vector IR cannot ` +
        'represent is a governance question, not something to drop from one target quietly',
    );

  const library = (what, className, members, imports) =>
    `// SOLAR ${what}s for Flutter.\n` +
    HEADER +
    '\n' +
    imports +
    CLASS_DOC.replaceAll('%WHAT%', what) +
    `abstract final class ${className} {\n` +
    members.join('\n') +
    '}\n';

  return {
    icons: library(
      'icon',
      'SolarIcons',
      iconMembers,
      "import '../solar_icon.dart';\n\n",
    ),
    logos: library(
      'logo',
      'SolarLogos',
      logoMembers,
      "import 'package:flutter/painting.dart' show Color;\n\n" +
        "import '../solar_icon.dart';\n\n",
    ),
    manifest: { icons, logos, omitted },
  };
}

export function emitFlutterIcons(spec) {
  const { icons, logos, manifest } = renderFlutterIcons(spec);
  writeGenerated(join(OUT_DIR, 'icons.dart'), icons);
  writeGenerated(join(OUT_DIR, 'logos.dart'), logos);
  return Object.keys(manifest.icons).length;
}
