import { join } from 'node:path';
import { flattenSpec } from '../spec.mjs';
import { packagesDir } from '../util/paths.mjs';
import { writeGenerated } from '../util/write.mjs';
import {
  canonical,
  entry,
  letterSpacingEm,
  writeManifest,
} from './manifest.mjs';
import { mobileMediaQuery } from './breakpoint.mjs';
import { shadowLayers, shadowToCss } from './shadow.mjs';

const OUT_DIR = join(packagesDir, 'styles', 'src', 'generated', 'mui');

const literal = (type, value) => {
  if (type === 'dimension')
    return typeof value === 'number' ? `${value}px` : value;
  if (type === 'duration')
    return typeof value === 'number' ? `${value}ms` : value;
  if (type === 'cubicBezier') return `cubic-bezier(${value.join(', ')})`;
  return value;
};

/**
 * A text style as CSS-valid declarations. Figma states letter spacing as a percentage of the
 * font size, which is not a valid CSS letter-spacing and is dropped by the browser, so it is
 * emitted in em: the same quantity, and the one unit that stays correct when the Mobile scale
 * changes the font size underneath it.
 */
const cssTextStyle = (v) => ({
  ...v,
  letterSpacing: `${letterSpacingEm(v.letterSpacing, canonical.dimension(v.fontSize))}em`,
});

/** Only the declarations the Mobile mode actually changes. */
const overrides = (desktop, mobile) =>
  Object.fromEntries(
    Object.entries(mobile).filter(([k, v]) => desktop[k] !== v),
  );

export function renderMui(spec) {
  const tokens = flattenSpec(spec);
  const index = new Map(tokens.map((t) => [t.name, t]));
  const mq = mobileMediaQuery(index);
  const data = {
    tokens: { light: {}, dark: {} },
    viewport: { desktop: {}, mobile: {} },
    typography: { desktop: {}, mobile: {} },
    responsiveTypography: {},
    zIndex: {},
    shadows: {},
  };
  const manifest = {};

  for (const t of tokens) {
    if (t.name.startsWith('z.')) {
      data.zIndex[t.name.slice(2)] = t.value;
      manifest[t.name] = entry('number', t.value);
      continue;
    }
    if (t.type === 'typography') {
      // The Type collection switches size and line height between Desktop and Mobile, so both
      // are emitted. Dropping mobile here would lose an axis only the CSS media query has.
      const key = t.name.replace(/^typography\./, '');
      const desktop = cssTextStyle({ ...t.value, ...t.ext.modes.desktop });
      const mobile = cssTextStyle({ ...t.value, ...t.ext.modes.mobile });
      data.typography.desktop[key] = desktop;
      data.typography.mobile[key] = mobile;

      // MUI reads a media query nested in a variant, so one entry carries both viewports and
      // createTheme needs no help from the consumer to switch at the tablet boundary.
      const mobileOnly = overrides(desktop, mobile);
      data.responsiveTypography[key] = Object.keys(mobileOnly).length
        ? { ...desktop, [`@media ${mq}`]: mobileOnly }
        : { ...desktop };

      manifest[t.name] = entry('typography', desktop, desktop, {
        desktop,
        mobile,
      });
      continue;
    }
    if (t.type === 'shadow') {
      const lightLayers = shadowLayers(index, { $value: t.value }, 'light');
      const darkLayers = shadowLayers(index, { $value: t.value }, 'dark');
      const key = t.name.replace(/^shadow\./, '');
      data.shadows[key] = {
        light: shadowToCss(lightLayers),
        dark: shadowToCss(darkLayers),
      };
      manifest[t.name] = entry(
        'shadow',
        shadowToCss(lightLayers),
        lightLayers,
        { light: lightLayers, dark: darkLayers },
      );
      continue;
    }
    const light = literal(
      t.type,
      t.modes?.light ?? t.modes?.desktop ?? t.value,
    );
    const dark = literal(t.type, t.modes?.dark ?? t.modes?.desktop ?? t.value);
    data.tokens.light[t.name] = light;
    data.tokens.dark[t.name] = dark;

    let modes;
    if (t.modes?.light !== undefined) modes = { light, dark };
    else if (t.modes?.desktop !== undefined) {
      // MUI's theme is keyed by theme mode alone, so a viewport-varying token has nowhere to
      // live in solarTokens: both entries hold the Desktop value. The Mobile value is emitted
      // separately rather than dropped, mirroring the CSS media query.
      const mobile = literal(t.type, t.modes.mobile);
      data.viewport.desktop[t.name] = light;
      data.viewport.mobile[t.name] = mobile;
      modes = { desktop: light, mobile };
    }
    manifest[t.name] = entry(t.type, light, light, modes);
  }

  const ts =
    `// SOLAR design tokens for MUI. Generated by @bwp-web/codegen from spec/tokens.json. Do not edit.\n` +
    `// Plain data on purpose: this module imports nothing, so @bwp-web/styles stays dependency free.\n` +
    `// Pass the result of createSolarThemeOptions(mode) to MUI's createTheme.\n\n` +
    `export const solarTokens = ${JSON.stringify(data.tokens, null, 2)} as const;\n\n` +
    `// Mirrors the CSS @media (max-width: 767.98px) override: apply these on top of\n` +
    `// solarTokens[mode] below the sm breakpoint. solarTokens is keyed by theme mode only, so\n` +
    `// it carries the Desktop value of every viewport-varying token in both entries.\n` +
    `export const solarViewportTokens = ${JSON.stringify(data.viewport, null, 2)} as const;\n\n` +
    `export const solarTypography = ${JSON.stringify(data.typography, null, 2)} as const;\n\n` +
    `// One entry per text style carrying both viewports: MUI applies the nested media query, so\n` +
    `// this can be handed to createTheme as-is. solarTypography above keeps the two viewports\n` +
    `// separate for consumers that are not MUI.\n` +
    `export const solarResponsiveTypography = ${JSON.stringify(data.responsiveTypography, null, 2)} as const;\n\n` +
    `export const solarShadows = ${JSON.stringify(data.shadows, null, 2)} as const;\n\n` +
    `export const solarZIndex = ${JSON.stringify(data.zIndex, null, 2)} as const;\n\n` +
    `export type SolarMode = 'light' | 'dark';\n\n` +
    `export function createSolarThemeOptions(mode: SolarMode) {\n` +
    `  const t = solarTokens[mode];\n` +
    `  return {\n` +
    `    palette: {\n` +
    `      mode,\n` +
    `      background: { default: t['color.surface.background'], paper: t['color.surface.base'] },\n` +
    `      text: { primary: t['color.text.primary'], secondary: t['color.text.secondary'], disabled: t['color.text.disabled'] },\n` +
    `      divider: t['color.border.subtle'],\n` +
    `      error: { main: t['color.text.feedback.danger'] },\n` +
    `      warning: { main: t['color.text.feedback.warning'] },\n` +
    `      info: { main: t['color.text.feedback.info'] },\n` +
    `      success: { main: t['color.text.feedback.success'] },\n` +
    `    },\n` +
    `    shape: { borderRadius: parseFloat(t['radius.control']) },\n` +
    `    zIndex: solarZIndex,\n` +
    `    typography: solarResponsiveTypography,\n` +
    `  };\n` +
    `}\n`;

  return { ts, manifest, data };
}

export function emitMui(spec, fileVersion) {
  const { ts, manifest } = renderMui(spec);
  writeGenerated(join(OUT_DIR, 'theme.ts'), ts);
  writeManifest({
    target: 'mui',
    dir: OUT_DIR,
    entries: manifest,
    fileVersion,
  });
  return Object.keys(manifest).length;
}
