/**
 * The Widgetbook Playground's generated data, as Dart:
 *
 * - `widgetbook/lib/playground/icons.dart`: every SOLAR icon's stem (what an icon control offers)
 *   and a map from an icon control's value (`chevron-right`, `chevron-right solid`) to its
 *   `SolarVector`, since Dart cannot look a static field up by name. Widgetbook-only: a map
 *   retains every icon, which an app must not (the reason `SolarIcons` has none,
 *   src/emit/flutter-icons.mjs), and a viewer shows every icon anyway.
 * - `widgetbook/lib/playground/controls.dart`: every component's controls
 *   (src/playground/controls.mjs `componentControls`, the list Storybook draws too, extras
 *   included), each select's options also as the Dart enum values the Flutter enum emitter names
 *   them (`dartOptions`), and the Playground's fixed values (src/playground/values.mjs) as
 *   constants, so the app and its tests read them without npm at build time.
 * - the builder registries, `components/stories/playground/registry.generated.ts` and
 *   `widgetbook/lib/playground/registry.dart`: every component with a Playground
 *   (src/playground/controls.mjs `playgroundNames`) by its name, each with its hand-written
 *   builder, by file name (`playgroundFileOf`). A builder file missing fails the typecheck or
 *   `flutter analyze`, so no component goes without a Playground.
 *
 * The icon map and the controls are written from what the run has just built, never re-read from
 * spec/: writes are held until the run ends, so spec/ on disk is the last run's.
 */

import { join } from 'node:path';
import { componentControls, playgroundNames } from '../playground/controls.mjs';
import {
  ICON_NONE,
  ICON_SAMPLE,
  ICON_SOLID,
  LOG_LENGTH,
  WIDTHS,
} from '../playground/values.mjs';
import { camel } from '../util/naming.mjs';
import { packagesDir } from '../util/paths.mjs';
import { byCodeUnit } from '../util/sort.mjs';
import { writeGenerated } from '../util/write.mjs';
import { dartEnumValue } from './flutter.mjs';
import { dartVariantName } from './flutter-icons.mjs';
import { HEADER, tsKey } from './registries.mjs';

const OUT_DIR = join(
  packagesDir,
  'solar_flutter',
  'widgetbook',
  'lib',
  'playground',
);

/** The generated Dart files' absolute paths, which the codegen gives dart format. */
export const WIDGETBOOK_FILES = [
  'icons.dart',
  'controls.dart',
  'registry.dart',
].map((f) => join(OUT_DIR, f));

const [ICONS_FILE, CONTROLS_FILE, DART_REGISTRY_FILE] = WIDGETBOOK_FILES;

const WEB_REGISTRY_FILE = join(
  packagesDir,
  'components',
  'stories',
  'playground',
  'registry.generated.ts',
);

const STYLES = ['outline', 'solid'];

/**
 * A single-quoted Dart string literal. Unlike `quote` (src/util/naming.mjs), which is valid Dart
 * only for text without `$`, it escapes interpolation and every control character, since the
 * controls carry Figma's words verbatim.
 */
const ESCAPES = {
  '\\': '\\\\',
  "'": "\\'",
  $: '\\$',
  '\n': '\\n',
  '\r': '\\r',
  '\t': '\\t',
};

export function dartString(text) {
  const escaped = Array.from(String(text), (c) => {
    if (ESCAPES[c]) return ESCAPES[c];
    const code = c.codePointAt(0);
    return code < 0x20 || code === 0x7f ? `\\u{${code.toString(16)}}` : c;
  }).join('');
  return `'${escaped}'`;
}

/** A control's value as a Dart constant: a String, bool, num, null or List<String>. */
export function dartValue(value, where) {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'string') return dartString(value);
  if (typeof value === 'boolean') return String(value);
  if (typeof value === 'number') {
    if (!Number.isFinite(value))
      throw new Error(`${where}: ${value} has no Dart constant`);
    return String(value);
  }
  if (Array.isArray(value) && value.every((v) => typeof v === 'string'))
    return `<String>[${value.map(dartString).join(', ')}]`;
  throw new Error(
    `${where}: ${JSON.stringify(value)} is not a String, bool, num, null or List<String>`,
  );
}

const header = (from) =>
  `// Generated by @bwp-web/codegen from ${from}. Do not edit.\n`;

/**
 * The text of `icons.dart`.
 *
 * @param {{icons: Record<string, object>}} spec the icon spec
 */
export function renderWidgetbookIcons(spec) {
  const stems = Object.keys(spec.icons);
  // An icon control's value, the stem with the solid style's suffix where solid, to its field.
  const entries = stems
    .flatMap((stem) =>
      STYLES.map((style) => [
        style === 'solid' ? `${stem}${ICON_SOLID}` : stem,
        dartVariantName(stem, style),
      ]),
    )
    .sort(([a], [b]) => byCodeUnit(a, b));
  return (
    header('spec/icons.json') +
    '// Every SOLAR icon for the Playground: its stems, and each style’s SolarVector by its value.\n' +
    '\n' +
    "import 'package:solar_flutter/solar_flutter.dart';\n" +
    '\n' +
    '/// Every icon’s `SolarIcons` field by the value an icon control gives it (`chevron-right`,\n' +
    '/// `chevron-right solid`). Widgetbook-only: a map retains every icon, which an app must not.\n' +
    'const solarIconsByName = <String, SolarVector>{\n' +
    entries
      .map(([value, field]) => `  ${dartString(value)}: SolarIcons.${field},\n`)
      .join('') +
    '};\n' +
    '\n' +
    '/// Every icon’s stem (`chevron-right`), in the icon spec’s order: what an icon control offers.\n' +
    'const playgroundIcons = <String>[\n' +
    stems.map((s) => `  ${dartString(s)},\n`).join('') +
    '];\n'
  );
}

/**
 * A control as Dart writes it: the list's entry, and for a select its options as the Dart enum
 * values the Flutter enum emitter names them (`top-search` → `topSearch`), so a builder maps a
 * value to its enum without respelling it.
 */
export const dartControl = (c) =>
  c.kind === 'select'
    ? { ...c, dartOptions: c.options.map((o) => dartEnumValue(o)) }
    : c;

/** The fixed values both adapters use (src/playground/values.mjs), as Dart constants. */
const VALUE_CONSTANTS = [
  [
    'playgroundIconNone',
    ICON_NONE,
    'An icon control’s value that hides the slot.',
  ],
  [
    'playgroundIconSample',
    ICON_SAMPLE,
    'An icon control’s value that shows the builder’s sample icon.',
  ],
  [
    'playgroundIconSolid',
    ICON_SOLID,
    'The suffix an icon control’s value carries for the solid style (`chevron-right solid`).',
  ],
  [
    'playgroundWidths',
    WIDTHS,
    'The width box’s choices, in logical pixels or `auto`: the viewer’s layout, not a design value.',
  ],
  [
    'playgroundLogLength',
    LOG_LENGTH,
    'How many callbacks the event log keeps, newest first.',
  ],
];

/** The text of `controls.dart`, from `componentControls`' list. */
function controlsDart(components) {
  const control = (component, c) =>
    '    {' +
    Object.entries(dartControl(c))
      .map(
        ([k, v]) =>
          `${dartString(k)}: ${dartValue(v, `${component} ${c.name} ${k}`)}`,
      )
      .join(', ') +
    '},\n';
  return (
    header('spec/components/ (src/playground/controls.mjs)') +
    '// Every component’s Playground controls, the same list Storybook draws, and the fixed values\n' +
    '// both viewers’ adapters use.\n' +
    '\n' +
    VALUE_CONSTANTS.map(
      ([name, value, doc]) =>
        `/// ${doc}\nconst ${name} = ${dartValue(value, name)};\n\n`,
    ).join('') +
    '/// Each component’s controls, by its name, in order: its API, its slots, its width, its extras.\n' +
    'const playgroundControls = <String, List<Map<String, Object?>>>{\n' +
    Object.entries(components)
      .map(
        ([name, controls]) =>
          `  ${dartString(name)}: [\n` +
          controls.map((c) => control(name, c)).join('') +
          '  ],\n',
      )
      .join('') +
    '};\n'
  );
}

/**
 * The text of `controls.dart`.
 *
 * @param {Record<string, object>} specs every component IR, by name
 * @param {Record<string, {name: string}>} icons the icon spec's icons, by stem
 */
export const renderWidgetbookControls = (specs, icons) =>
  controlsDart(componentControls(specs, icons));

/** Writes icons.dart; returns how many icons it maps. */
export function emitWidgetbookIcons(spec) {
  writeGenerated(ICONS_FILE, renderWidgetbookIcons(spec));
  return Object.keys(spec.icons).length * STYLES.length;
}

/** Writes controls.dart; returns how many components it lists. */
export function emitWidgetbookControls(specs, icons) {
  const components = componentControls(specs, icons);
  writeGenerated(CONTROLS_FILE, controlsDart(components));
  return Object.keys(components).length;
}

/**
 * A component's Playground builder files, named after its builder's identifier, word by word:
 * `Text Input` and `DatePicker` to `text-input.tsx` and `date_picker.dart` (`textInput`,
 * `datePicker`), `PIN Input` to `pin-input.tsx` (`pinInput`).
 */
export function playgroundFileOf(name) {
  const words = camel(name)
    .split(/(?=[A-Z])/)
    .map((w) => w.toLowerCase());
  return { web: `${words.join('-')}.tsx`, dart: `${words.join('_')}.dart` };
}

/**
 * The two builder registries' text: every component with a Playground, sorted, by its name, with
 * its builder, `<camel>` (web, a default export) and `<camel>Playground` (Flutter).
 *
 * @param {string[]} [names] the components; playgroundNames' by default
 * @returns {{web: string, dart: string}}
 */
export function renderPlaygroundRegistries(names = playgroundNames()) {
  const sorted = [...names].sort(byCodeUnit);
  const web = [
    HEADER,
    '// The Playground builders, one per component with a Playground, by its name: a builder file',
    '// missing (stories/playground/<name>.tsx) fails the typecheck, so none goes without one.',
    '',
    ...sorted.map(
      (n) =>
        `import ${camel(n)} from './${playgroundFileOf(n).web.replace(/\.tsx$/, '.js')}';`,
    ),
    "import type { PlaygroundBuilder } from './types.js';",
    '',
    'export const PLAYGROUND_BUILDERS: Record<string, PlaygroundBuilder> = {',
    ...sorted.map((n) => `  ${tsKey(n)}: ${camel(n)},`),
    '};',
  ];
  const dart = [
    HEADER,
    '// The Playground builders, one per component with a Playground, by its name: a builder file',
    '// missing (lib/playground/<name>.dart) fails `flutter analyze`, so none goes without one.',
    '',
    // In order, as the analyzer's directive ordering wants, the interface among the builders.
    ...['playground.dart', ...sorted.map((n) => playgroundFileOf(n).dart)]
      .sort(byCodeUnit)
      .map((f) => `import '${f}';`),
    '',
    'final playgroundBuilders = <String, SolarPlaygroundBuilder>{',
    ...sorted.map((n) => `  ${dartString(n)}: ${camel(n)}Playground,`),
    '};',
  ];
  return { web: `${web.join('\n')}\n`, dart: `${dart.join('\n')}\n` };
}

/** Writes both builder registries; returns how many components they list. */
export function emitPlaygroundRegistries(names = playgroundNames()) {
  const { web, dart } = renderPlaygroundRegistries(names);
  writeGenerated(WEB_REGISTRY_FILE, web);
  writeGenerated(DART_REGISTRY_FILE, dart);
  return names.length;
}
