/**
 * Emits the SOLAR logos as React components, and the raster app icons as data URLs.
 *
 * A logo is not an icon with brand colours, and this file is where that difference is made
 * mechanical rather than remembered:
 *
 * - **No tinting.** Every path keeps the colour SOLAR drew it in, `currentColor` is never
 *   emitted, and the shell's props omit `color` and `fill` so the type system refuses a tinted
 *   brand mark instead of a comment asking for one.
 * - **`os-logo/teams` has no vector IR.** It is 13 paths, 12 of them filled from 11 radial and
 *   one linear gradient, plus every `fill-opacity` in the corpus. React renders that natively,
 *   so its source is converted to JSX here rather than approximated. The conversion is
 *   deliberately narrow: it camelCases the three hyphenated attributes this document actually
 *   uses and throws on a fourth, so a future mark with an unhandled attribute fails the build
 *   instead of rendering an attribute the DOM silently ignores.
 * - **Gradient ids are namespaced per instance.** A browser resolves `url(#id)` to the first
 *   match in the document, so two Teams marks on one page would both paint with the first one's
 *   gradients. Every id is rewritten to a short generated name and prefixed with the shell's
 *   `useId` value; the Figma ids (`paint0_radial_6196_626`) do not survive into the output at
 *   all, which is what lets a test assert their absence literally.
 * - **The app icons are raster and are not components.** They are emitted as base64 data URLs,
 *   one exported const each plus a record, so a consumer can take one without the rest. 14.5 KB
 *   of PNG becomes ~20 KB of base64, which costs no bundler loader, no `*.png` type shim and no
 *   asset-serving decision on the consumer's side.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { docsDir, packagesDir } from '../util/paths.mjs';
import { logoDigest, sha256 } from '../util/digest.mjs';
import { camel, pascal, quote } from '../util/naming.mjs';
import { byCodeUnit } from '../util/sort.mjs';
import { fail, parseAttrs, tagPattern } from '../util/svg-markup.mjs';
import { writeGenerated } from '../util/write.mjs';

const OUT_DIR = join(packagesDir, 'assets', 'src', 'generated', 'logos');

const HEADER =
  '// Generated by @bwp-web/codegen from spec/icons.json. Do not edit.\n';

// The three hyphenated attributes the corpus uses. An unlisted one throws: React would render
// `fill-opacity` as an unknown attribute on some elements and drop it on others, and either way
// a mark would ship subtly wrong with nothing to notice it.
const JSX_ATTRIBUTES = {
  'fill-opacity': 'fillOpacity',
  'stop-color': 'stopColor',
  'stop-opacity': 'stopOpacity',
};

// What the shell owns on the root element, and therefore what may be dropped from it. Anything
// else on a root is an instruction we would be discarding.
const ROOT_ATTRIBUTES = new Set([
  'width',
  'height',
  'viewBox',
  'fill',
  'xmlns',
]);

const MIME = { '.png': 'image/png' };

const URL_REF = /url\(#([^)\s]+)\)/g;

// A JSX expression holding a template literal, written as source rather than evaluated.
const template = (body) => '{`' + body + '`}';

// `google: google` rather than `google` is valid and ugly; a slug that is already an identifier
// gets the shorthand, and `dark-sm` keeps its quotes because it has to.
const entry = (key, value) =>
  key === value ? `  ${key},\n` : `  ${quote(key)}: ${value},\n`;

// os-logo and biamp-logo already say "logo" in their component name, so the module is named
// after the component rather than after the Figma set: os.tsx exports LogoOs.
const moduleStem = (kebab) => kebab.replace(/-logo$/, '');

function rootViewBox(attrs, file) {
  for (const name of Object.keys(attrs)) {
    if (!ROOT_ATTRIBUTES.has(name)) {
      fail(
        file,
        `the root <svg> carries "${name}", which the shell cannot own; the shell writes ` +
          'viewBox, the height and the accessibility attributes itself, so anything else on ' +
          'the root would be dropped',
      );
    }
  }
  // Figma writes fill="none" on every export. It is chrome, not geometry, and the vector reader
  // refuses to inherit it into a path; the same rule applies here.
  if (attrs.fill && attrs.fill !== 'none')
    fail(file, `the root <svg> is filled ${attrs.fill}, which is not chrome`);
  if (!attrs.viewBox) fail(file, 'the root <svg> has no viewBox');
  return attrs.viewBox;
}

/**
 * Renders one attribute as JSX source, namespacing any id it defines or refers to.
 *
 * @param {{file: string, defined: Set<string>, referenced: Set<string>, rename: (id: string) => string}} ctx
 */
function jsxAttribute(name, value, ctx) {
  if (name.includes(':'))
    fail(ctx.file, `namespaced attribute "${name}" is not supported`);
  if (name === 'class' || name === 'for')
    fail(ctx.file, `attribute "${name}" is spelled differently in JSX`);

  let jsxName = name;
  if (name.includes('-')) {
    jsxName = JSX_ATTRIBUTES[name];
    if (!jsxName) {
      fail(
        ctx.file,
        `attribute "${name}" has no known JSX spelling; add it to JSX_ATTRIBUTES once you ` +
          'have checked how React spells it, rather than emitting an attribute the DOM ignores',
      );
    }
  }

  if (value.includes('`') || value.includes('${') || value.includes('"'))
    fail(
      ctx.file,
      `attribute "${name}" has a value JSX cannot quote: ${value}`,
    );

  if (jsxName === 'id') {
    ctx.defined.add(value);
    return 'id=' + template('${uid}' + ctx.rename(value));
  }

  if (value.includes('url(#')) {
    const body = value.replace(URL_REF, (_, id) => {
      ctx.referenced.add(id);
      return 'url(#${uid}' + ctx.rename(id) + ')';
    });
    return `${jsxName}=` + template(body);
  }

  return `${jsxName}="${value}"`;
}

/**
 * Converts an SVG document the vector IR cannot represent into the JSX body of a `<Logo>`.
 *
 * The root `<svg>` is dropped -- the shell writes it, so the sizing and accessibility rules are
 * the same for every mark -- and its `viewBox` is returned separately. Everything below it is
 * carried through verbatim apart from the two rewrites this transform exists for: the three
 * hyphenated attribute names, and the ids.
 *
 * It is narrow on purpose. Every element, attribute and text node it does not recognise is an
 * error naming the file. The alternative -- passing the unknown through and hoping -- is how an
 * asset pipeline ships a mark that renders wrong in one browser and right in the next.
 *
 * @param {string} source
 * @param {{file: string}} context
 * @returns {{viewBox: string, jsx: string, ids: string[]}}
 */
export function svgToJsx(source, { file }) {
  const names = new Map();
  const defined = new Set();
  const referenced = new Set();
  // Short generated names rather than prefixed Figma ones: `paint0_radial_6196_626` says
  // nothing a reader needs, and dropping it entirely means "no source id survives" is a literal
  // assertion a test can make rather than a claim about where a prefix happens to sit.
  const rename = (id) => {
    if (!names.has(id)) names.set(id, `g${names.size}`);
    return names.get(id);
  };
  const ctx = { file, defined, referenced, rename };

  const lines = [];
  let viewBox = null;
  let closed = false;
  let open = 0;
  let cursor = 0;
  const TAG = tagPattern();

  for (let tag; (tag = TAG.exec(source));) {
    const between = source.slice(cursor, tag.index);
    if (between.trim() !== '')
      fail(file, `text content "${between.trim()}" cannot be carried into JSX`);
    cursor = TAG.lastIndex;

    const [, closing, name, attrText] = tag;
    const selfClosing = attrText.trimEnd().endsWith('/');
    const attrs = parseAttrs(attrText);

    if (name === 'svg') {
      if (closing) {
        closed = true;
        continue;
      }
      if (viewBox !== null) fail(file, 'a nested <svg> is not supported');
      viewBox = rootViewBox(attrs, file);
      continue;
    }

    if (viewBox === null)
      fail(file, `<${name}> appears outside the root <svg>`);
    if (closed) fail(file, `<${name}> appears after the root </svg>`);

    if (closing) {
      open -= 1;
      if (open < 0) fail(file, `</${name}> closes an element that is not open`);
      lines.push(`${'  '.repeat(open)}</${name}>`);
      continue;
    }

    const rendered = Object.entries(attrs).map(([key, value]) =>
      jsxAttribute(key, value, ctx),
    );
    const head = `<${name}${rendered.map((a) => ` ${a}`).join('')}`;
    lines.push(`${'  '.repeat(open)}${head}${selfClosing ? ' />' : '>'}`);
    if (!selfClosing) open += 1;
  }

  if (source.slice(cursor).trim() !== '')
    fail(file, 'trailing text after the root </svg>');
  if (viewBox === null) fail(file, 'no root <svg>');
  if (!closed || open !== 0) fail(file, 'unbalanced elements');

  const missing = [...referenced].filter((id) => !defined.has(id));
  const unused = [...defined].filter((id) => !referenced.has(id));
  if (missing.length)
    fail(
      file,
      `url(#…) refers to ${missing.join(', ')}, which nothing defines`,
    );
  if (unused.length)
    fail(file, `${unused.join(', ')} is defined but never referenced`);

  return { viewBox, jsx: lines.join('\n'), ids: [...names.values()] };
}

const pathLiteral = (path) =>
  `{ d: ${quote(path.d)}` +
  (path.fillRule === 'evenodd' ? `, fillRule: 'evenodd'` : '') +
  `, fill: ${quote(path.fill)} }`;

const geometryLiteral = (name, geometry) =>
  `const ${name}: LogoGeometry = {\n` +
  `  viewBox: ${quote(geometry.viewBox.join(' '))},\n` +
  `  paths: [${geometry.paths.map(pathLiteral).join(', ')}],\n` +
  `};\n`;

function markupLiteral(name, variant, file) {
  const { viewBox, jsx } = svgToJsx(variant.source, { file });
  return (
    `const ${name}: LogoMarkup = {\n` +
    `  viewBox: ${quote(viewBox)},\n` +
    '  // Every id below is namespaced with uid, which the shell takes from useId: a browser\n' +
    '  // resolves url(#id) to the first match in the document, so two of these on one page\n' +
    "  // would otherwise both paint with the first one's gradients.\n" +
    '  render: (uid) => (\n' +
    '    <>\n' +
    jsx
      .split('\n')
      .map((line) => `      ${line}\n`)
      .join('') +
    '    </>\n' +
    '  ),\n' +
    '};\n'
  );
}

/** One vector or gradient logo set: a component, its variant union and its artwork. */
function vectorModule(set, logo) {
  const slugs = Object.keys(logo.variants).sort(byCodeUnit);
  const file = (slug) => `logos/${set}/${slug}.svg`;
  const constName = (slug) => camel(slug);
  const variantType = `${logo.component}Variant`;
  const propsType = `${logo.component}Props`;
  // The default is the first variant in sorted order: a generated, deterministic choice rather
  // than an editorial one, so adding a variant cannot quietly change which mark a caller gets
  // without also changing this list.
  const fallback = slugs[0];

  const kinds = ['LogoArtwork', 'LogoProps'];
  if (slugs.some((slug) => !logo.variants[slug].unsupported))
    kinds.push('LogoGeometry');
  if (slugs.some((slug) => logo.variants[slug].unsupported))
    kinds.push('LogoMarkup');

  const artwork = slugs
    .map((slug) => {
      const variant = logo.variants[slug];
      return variant.unsupported
        ? markupLiteral(constName(slug), variant, file(slug))
        : geometryLiteral(constName(slug), variant);
    })
    .join('\n');

  const source =
    HEADER +
    `import {\n  Logo,\n${kinds
      .sort(byCodeUnit)
      .map((kind) => `  type ${kind},\n`)
      .join('')}} from '../../logo.js';\n\n` +
    artwork +
    '\n' +
    `export type ${variantType} = ${slugs.map(quote).join(' | ')};\n\n` +
    `const VARIANTS: Record<${variantType}, LogoArtwork> = {\n${slugs
      .map((slug) => entry(slug, constName(slug)))
      .join('')}};\n\n` +
    `export interface ${propsType} extends LogoProps {\n` +
    `  /** Which mark to draw. Defaults to ${fallback}. */\n` +
    `  variant?: ${variantType};\n` +
    '}\n\n' +
    `/**\n * ${logo.name}. A brand mark: it carries its own colours and is never tinted.\n */\n` +
    `export function ${logo.component}({\n` +
    `  variant = ${quote(fallback)},\n` +
    `  ...props\n` +
    `}: ${propsType}) {\n` +
    `  return <Logo {...props} artwork={VARIANTS[variant]} />;\n` +
    '}\n';

  return {
    set,
    file: `${moduleStem(set)}.tsx`,
    component: logo.component,
    source,
  };
}

/**
 * One raster asset's bytes, checked against the digest the spec recorded.
 *
 * Read from docs/ rather than carried in spec/icons.json, because 20 KB of base64 in a checked-in
 * JSON file would be noise to every other target. The digest is what keeps that honest: without
 * it a changed PNG would change this output while the spec, which the guard compares, stayed the
 * same.
 */
function rasterBytes(logo, slug) {
  const file = logo.files[slug];
  const bytes = readFileSync(join(docsDir, 'solar-icons', file));
  if (sha256(bytes) !== logo.digests?.[slug])
    throw new Error(
      `${file}: the bytes do not match the digest in the icon spec; regenerate the spec`,
    );
  return bytes;
}

/** One raster set, as base64 data URLs. */
function rasterModule(set, logo) {
  const slugs = Object.keys(logo.files).sort(byCodeUnit);
  const nameType = `${pascal(set)}Name`;
  const constName = (slug) => camel(set) + pascal(slug);
  const recordName = `${camel(set)}s`;
  const urls = new Map();

  for (const slug of slugs) {
    const path = logo.files[slug];
    const ext = path.slice(path.lastIndexOf('.'));
    const mime = MIME[ext];
    if (!mime)
      throw new Error(`${path}: no known media type for a ${ext} asset`);
    urls.set(
      slug,
      `data:${mime};base64,${rasterBytes(logo, slug).toString('base64')}`,
    );
  }

  const source =
    HEADER +
    `\n/**\n * ${logo.name}s as base64 data URLs.\n *\n` +
    ' * Raster, so these are not components: they are the value of an `<img src>`, a CSS\n' +
    ' * `background-image` or a manifest entry. Inlined rather than shipped as files so a\n' +
    ' * consumer needs no bundler loader, no `*.png` type shim and no decision about where to\n' +
    ' * serve them from; one exported const each means taking one does not pull in the rest.\n' +
    ' */\n\n' +
    `export type ${nameType} = ${slugs.map(quote).join(' | ')};\n\n` +
    slugs
      .map(
        (slug) =>
          `export const ${constName(slug)} =\n  ${quote(urls.get(slug))};\n`,
      )
      .join('\n') +
    '\n' +
    `export const ${recordName}: Record<${nameType}, string> = {\n${slugs
      .map((slug) => entry(slug, constName(slug)))
      .join('')}};\n`;

  return {
    set,
    file: `${moduleStem(set)}.ts`,
    exports: [nameType, ...slugs.map(constName), recordName],
    types: [nameType],
    source,
  };
}

/**
 * Renders every logo module, the barrel and the manifest, as data.
 *
 * Returning strings rather than writing them keeps the test suite off the disk, so
 * "no currentColor anywhere" is a property of what this function produces rather than of
 * whatever happens to be checked in.
 */
export function renderReactLogos(spec) {
  const sets = Object.keys(spec.logos).sort(byCodeUnit);
  const modules = [];
  const logos = {};

  for (const set of sets) {
    const logo = spec.logos[set];
    if (logo.raster) {
      modules.push(rasterModule(set, logo));
      logos[set] = {
        raster: true,
        files: Object.fromEntries(
          Object.keys(logo.files)
            .sort(byCodeUnit)
            .map((slug) => {
              const bytes = rasterBytes(logo, slug);
              return [
                slug,
                {
                  bytes: bytes.length,
                  digest: sha256(bytes),
                },
              ];
            }),
        ),
      };
      continue;
    }

    modules.push(vectorModule(set, logo));
    logos[set] = {
      component: logo.component,
      raster: false,
      variants: Object.fromEntries(
        Object.keys(logo.variants)
          .sort(byCodeUnit)
          .map((slug) => {
            const variant = logo.variants[slug];
            // A mark with no vector IR is fingerprinted by its source, which is the only thing
            // there is to compare; the manifest says so rather than leaving a hole.
            return [
              slug,
              variant.unsupported
                ? {
                    unsupported: variant.unsupported,
                    digest: sha256(variant.source),
                  }
                : {
                    viewBox: variant.viewBox.join(' '),
                    pathCount: variant.paths.length,
                    digest: logoDigest(variant.paths),
                  },
            ];
          }),
      ),
    };
  }

  const barrel =
    HEADER +
    modules
      .map((m) => {
        const stem = `./${m.file.replace(/\.tsx?$/, '.js')}`;
        if (m.exports)
          return `export {\n${m.exports
            .map(
              (name) => `  ${m.types.includes(name) ? 'type ' : ''}${name},\n`,
            )
            .join('')}} from '${stem}';\n`;
        return (
          `export {\n  ${m.component},\n  type ${m.component}Props,\n` +
          `  type ${m.component}Variant,\n} from '${stem}';\n`
        );
      })
      .join('');

  return { modules, barrel, logos };
}

export function emitReactLogos(spec) {
  const { modules, barrel } = renderReactLogos(spec);
  for (const m of modules) writeGenerated(join(OUT_DIR, m.file), m.source);
  writeGenerated(join(OUT_DIR, 'index.ts'), barrel);
  return modules.length;
}
