/**
 * The lists every generated component is in, written from the component list
 * (`src/components/`), so adding a component edits none of them by hand:
 *
 * - each package's barrel of its shells;
 * - the web visual check's registry of cases, and the Flutter one's;
 * - the variant builders the Flutter check shares with the Widgetbook app, and their library.
 *
 * Each names a file by the shells' conventions (src/shells/index.mjs: `IconButton.tsx`,
 * `icon-button.tsx`, `icon_button.dart`). A file named here that does not exist fails the typecheck or
 * `flutter analyze`, so a component cannot go unregistered, and none can be registered twice.
 */

import { join } from 'node:path';
import { flutterFileOf, shellFileOf } from '../shells/index.mjs';
import { camel, pascal } from '../util/naming.mjs';
import { packagesDir } from '../util/paths.mjs';
import { writeGenerated } from '../util/write.mjs';

const HEADER =
  '// Generated by @bwp-web/codegen from packages/codegen/src/components/. Do not edit.';

/** `Icon Button` to `icon-button`, the web case's file; its `data-case` ids use the same. */
const slug = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
/** `Icon Button` to `icon_button`, a Dart file. */
const snake = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, '_');
const key = (name) => (/^[A-Za-z]\w*$/.test(name) ? name : `'${name}'`);

/**
 * The files, by path from `packages/`, for the components by their names in code, sorted.
 *
 * @param {string[]} names
 * @returns {Array<{file: string, text: string}>}
 */
export function renderRegistries(
  names,
  { shelled = () => true, generic = () => false } = {},
) {
  const sorted = [...names].sort();
  // A component checked as another's state (Autocomplete Open, Autocomplete's) has no shells of
  // its own: it has a case, a builder and a story, and nothing to export.
  const own = sorted.filter(shelled);
  const components = own.map(
    (n) => `export * from './${shellFileOf(n).replace(/\.tsx$/, '.js')}';`,
  );
  const cases = [
    HEADER,
    '// The web registry: a case per generated component, by its name. The spec requires one for',
    '// every component in the codegen’s `COMPONENTS`, so a new component cannot go unmeasured.',
    '',
    ...sorted.map((n) => `import ${camel(n)} from './${slug(n)}.js';`),
    "import type { VisualCase } from './types.js';",
    '',
    'export const CASES: Record<string, VisualCase> = {',
    ...sorted.map((n) => `  ${key(n)}: ${camel(n)},`),
    '};',
  ];
  const dartCases = [
    HEADER,
    '// The Flutter registry: a case per generated component, by its name. The check requires one',
    '// for every oracle under spec/verify/, so a new component cannot go unmeasured.',
    '',
    "import '../harness.dart';",
    ...sorted.map((n) => `import '${snake(n)}.dart';`),
    '',
    'final cases = <String, VisualCase>{',
    ...sorted.map((n) => `  '${n}': ${camel(n)}Case,`),
    '};',
  ];
  const builders = [
    HEADER,
    '// How each generated widget is built in one oracle variant, by its name (see builders.dart).',
    '',
    "import 'builders.dart';",
    ...sorted.map((n) => `import '${snake(n)}.dart';`),
    '',
    'const builders = <String, VariantBuilder>{',
    ...sorted.map((n) => `  '${n}': build${pascal(n)},`),
    '};',
  ];
  const library = [
    HEADER,
    '',
    '/// How each generated solar_flutter widget is built in one oracle variant (spec/verify/), with its',
    '/// slots filled by probes: shared by the visual checks (test/visual/) and the Widgetbook app',
    '/// (widgetbook/), so both show a widget the same way.',
    'library;',
    '',
    ...[
      'builders.dart',
      'probes.dart',
      'registry.dart',
      ...sorted.map((n) => `${snake(n)}.dart`),
    ]
      .sort()
      .map((f) => `export 'src/${f}';`),
  ];
  const widgets = [
    HEADER,
    '// Every generated widget’s shell, which solar_flutter.dart exports.',
    '',
    ...own.map((n) => `export '${flutterFileOf(n)}';`),
  ];
  // Each component's key in an MUI theme's `components`, typed as MUI types its own: what the
  // shells read through internal/theme.ts.
  const themed = [
    HEADER,
    "// The SOLAR components' keys in an MUI theme's `components`, typed as MUI's own are:",
    '// `defaultProps` fill what the caller leaves unset, and `styleOverrides.root` styles the root',
    "// over the recipe, under the caller's `sx` (internal/theme.ts reads them).",
    '',
    "import type { CSSObject, Theme } from '@mui/material/styles';",
    ...own.map(
      (n) =>
        `import type { ${pascal(n)}Props } from './${shellFileOf(n).replace(/\.tsx$/, '.js')}';`,
    ),
    '',
    'interface SolarThemeEntry<P> {',
    '  defaultProps?: Partial<P>;',
    '  styleOverrides?: {',
    '    root?: CSSObject | ((args: { ownerState: P; theme: Theme }) => CSSObject);',
    '  };',
    '}',
    '',
    "declare module '@mui/material/styles' {",
    '  interface Components {',
    ...own.map(
      (n) =>
        `    Solar${pascal(n)}?: SolarThemeEntry<${pascal(n)}Props${generic(n) ? '<unknown>' : ''}>;`,
    ),
    '  }',
    '}',
  ];
  return [
    {
      file: 'components/src/components.generated.ts',
      text: [HEADER, ...components].join('\n'),
    },
    {
      file: 'components/src/theme.generated.ts',
      text: themed.join('\n'),
    },
    {
      file: 'components/test/visual/cases/registry.generated.ts',
      text: cases.join('\n'),
    },
    {
      file: 'solar_flutter/test/visual/cases/cases.dart',
      text: dartCases.join('\n'),
    },
    {
      file: 'solar_flutter/variants/lib/src/registry.dart',
      text: builders.join('\n'),
    },
    {
      file: 'solar_flutter/variants/lib/solar_flutter_variants.dart',
      text: library.join('\n'),
    },
    {
      file: 'solar_flutter/lib/src/components/components.dart',
      text: widgets.join('\n'),
    },
  ].map((f) => ({ ...f, text: `${f.text}\n` }));
}

/** Writes every registry; returns how many. */
export function emitRegistries(names, options) {
  const files = renderRegistries(names, options);
  for (const { file, text } of files)
    writeGenerated(join(packagesDir, file), text);
  return files.length;
}
