import { join } from 'node:path';
import { flattenSpec } from '../spec.mjs';
import { packagesDir } from '../util/paths.mjs';
import { writeGenerated } from '../util/write.mjs';
import { entry, writeManifest } from './manifest.mjs';
import { shadowLayers } from './shadow.mjs';

const OUT_DIR = join(packagesDir, 'styles', 'src', 'generated', 'tailwind');
const ref = (name) => `var(--solar-${name.replaceAll('.', '-')})`;
const key = (name, prefix) => name.replace(prefix, '').replaceAll('.', '-');

export function renderTailwind(spec) {
  const tokens = flattenSpec(spec);
  const index = new Map(tokens.map((t) => [t.name, t]));
  const extend = {
    colors: {},
    spacing: {},
    borderRadius: {},
    borderWidth: {},
    boxShadow: {},
    fontSize: {},
    fontFamily: {},
    screens: {},
    zIndex: {},
    transitionDuration: {},
    transitionTimingFunction: {},
  };
  const manifest = {};

  for (const t of tokens) {
    const n = t.name;
    // Tailwind exposes the semantic layer, so app code cannot reach for a raw palette value.
    // Two families are exceptions because SOLAR gives them no semantic layer at all: motion,
    // and the font families, which Tailwind's own sans/serif/mono defaults know nothing about.
    // Font weights are deliberately not exposed: SOLAR's 100 to 900 are exactly Tailwind's
    // built-in scale, so font-400 would only duplicate font-normal.
    const EXPOSED_PRIMITIVES = /^(motion\.|type\.font-family\.)/;
    if (t.ext.tier === 'primitive' && !EXPOSED_PRIMITIVES.test(n)) continue;
    if (n.startsWith('color.')) extend.colors[key(n, 'color.')] = ref(n);
    else if (n.startsWith('inset.') || n.startsWith('stack.'))
      extend.spacing[key(n, '')] = ref(n);
    else if (n.startsWith('radius.'))
      extend.borderRadius[key(n, 'radius.')] = ref(n);
    else if (n.startsWith('border.'))
      extend.borderWidth[key(n, 'border.')] = ref(n);
    else if (n.startsWith('shadow.'))
      extend.boxShadow[key(n, 'shadow.')] = ref(n);
    else if (n.startsWith('type.size.'))
      extend.fontSize[key(n, 'type.size.')] = ref(n);
    else if (n.startsWith('type.font-family.'))
      extend.fontFamily[key(n, 'type.font-family.')] = ref(n);
    else if (n.startsWith('z.')) extend.zIndex[key(n, 'z.')] = ref(n);
    else if (n.startsWith('motion.duration.'))
      extend.transitionDuration[key(n, 'motion.duration.')] = ref(n);
    else if (n.startsWith('motion.ease.'))
      extend.transitionTimingFunction[key(n, 'motion.ease.')] = ref(n);
    // Media queries cannot read custom properties, so screens need real values.
    else if (n.startsWith('layout.breakpoint.'))
      extend.screens[key(n, 'layout.breakpoint.')] = t.value;
    else continue;

    // What the preset holds is a var() reference, except screens, which must be literal. The
    // resolved value is passed as the canonical input so parity can compare across targets;
    // shadows resolve their colour alias first, the same way CSS and Flutter do.
    const emitted = n.startsWith('layout.breakpoint.') ? t.value : ref(n);
    manifest[n] =
      t.type === 'shadow'
        ? entry(
            'shadow',
            emitted,
            shadowLayers(index, { $value: t.value }, 'light'),
          )
        : entry(t.type, emitted, t.modes?.light ?? t.modes?.desktop ?? t.value);
  }

  const preset = { theme: { extend } };
  const ts =
    `// SOLAR Tailwind preset. Generated by @bwp-web/codegen from spec/tokens.json. Do not edit.\n` +
    `// Values point at the CSS custom properties in tokens.css, so Light and Dark switch with\n` +
    `// [data-theme]. Screens are real pixel values because media queries cannot read variables.\n\n` +
    `export const solarTailwindPreset = ${JSON.stringify(preset, null, 2)} as const;\n`;

  return { ts, preset, manifest };
}

export function emitTailwind(spec, fileVersion) {
  const { ts, manifest } = renderTailwind(spec);
  writeGenerated(join(OUT_DIR, 'preset.ts'), ts);
  writeManifest({
    target: 'tailwind',
    dir: OUT_DIR,
    entries: manifest,
    fileVersion,
  });
  return Object.keys(manifest).length;
}
