import { renderRuleSelector } from '../../components/render-selector.js';
import type {
  ComponentIR,
  DesignIR,
  IRValue,
  Token,
  TokenId,
} from '../../ir/types.js';
import { codeUnitCompare } from '../../sources.js';
import type { TokenValue } from '../../tokens/values.js';
import { renderLiteralValue, renderTokenValue } from '../css-values.js';
import type { GeneratedFile, PluginContext } from '../plugin.js';
import { ignoredForTailwind, isMappedForTailwind } from './hints.js';
import { tailwindVarName } from './names.js';

/** One line; every generated file starts with it, followed by a blank line. */
export function tailwindHeader(ir: DesignIR, ctx: PluginContext): string {
  return `/* Generated by @bwp-web/ds-compiler ${ctx.compilerVersion} for target tailwind from design.ir.json (source hash ${ir.meta.sourceHash}). Do not edit; run bwp-ds generate. */`;
}

/** Tailwind variable name for a token id. Throws on an unknown id (an IR invariant violation). */
export function varNameFor(ir: DesignIR, id: TokenId): string {
  const token = ir.tokens[id];
  if (!token) {
    throw new Error(`IR references unknown token "${id}"`);
  }
  return tailwindVarName(token.category, token.path, ir.meta.prefix);
}

function valueInMode(
  token: Token,
  mode: string,
): { value: TokenValue; alias: TokenId | undefined } {
  if (token.modeInvariant) {
    return { value: token.$value, alias: token.alias };
  }
  return { value: token.$value[mode], alias: token.alias?.[mode] };
}

function renderTokenLine(ir: DesignIR, id: TokenId, mode: string): string {
  const token = ir.tokens[id];
  const { value, alias } = valueInMode(token, mode);
  const text = alias
    ? `var(${varNameFor(ir, alias)})`
    : renderTokenValue(value, token.$type, (ref) => varNameFor(ir, ref));
  return `  ${varNameFor(ir, id)}: ${text};`;
}

/** All token ids, sorted for deterministic output; shared so every caller checks the same set. */
function sortedTokenIds(ir: DesignIR): string[] {
  return Object.keys(ir.tokens).sort(codeUnitCompare);
}

/** Two tokens may render to one variable name (prefix "weight": font-family "weight-x" and font-weight "x"). Refuse rather than emit ambiguous output. */
function assertUniqueNames(ir: DesignIR, ids: readonly string[]): void {
  const seen = new Map<string, string>();
  for (const id of ids) {
    const name = varNameFor(ir, id);
    const other = seen.get(name);
    if (other !== undefined) {
      const first = ir.tokens[other];
      const second = ir.tokens[id];
      throw new Error(
        `tokens ${first.cssName} (${first.source.file}:${first.source.line}) and ${second.cssName} both map to the Tailwind variable ${name}; rename one of them`,
      );
    }
    seen.set(name, id);
  }
}

export function renderTheme(ir: DesignIR, ctx: PluginContext): string {
  const ids = sortedTokenIds(ir);
  assertUniqueNames(ir, ids);
  const lines = [
    tailwindHeader(ir, ctx),
    '',
    '@theme static {',
    ...ids.map((id) => renderTokenLine(ir, id, ir.meta.defaultMode)),
    '}',
  ];
  const varying = ids.filter((id) => !ir.tokens[id].modeInvariant);
  for (const mode of ir.meta.modes) {
    if (mode === ir.meta.defaultMode || varying.length === 0) {
      continue;
    }
    lines.push(
      '',
      `${ir.meta.modeSelector.replaceAll('{mode}', mode)} {`,
      ...varying.map((id) => renderTokenLine(ir, id, mode)),
      '}',
    );
  }
  return `${lines.join('\n')}\n`;
}

export function renderIRValue(ir: DesignIR, value: IRValue): string {
  return value.kind === 'token'
    ? `var(${varNameFor(ir, value.ref)})`
    : renderLiteralValue(value);
}

function renderComponent(ir: DesignIR, component: ComponentIR): string[] {
  const ignored = ignoredForTailwind(component);
  const target = {
    name: component.name,
    rootElement: component.slots.root?.element ?? 'div',
  };
  const blocks: string[] = [];
  for (const rule of component.rules) {
    const props = Object.keys(rule.declarations)
      .filter((p) => !ignored.has(p))
      .sort(codeUnitCompare);
    if (props.length === 0) {
      continue;
    }
    blocks.push(
      [
        `  ${renderRuleSelector(ir.meta.prefix, target, rule)} {`,
        ...props.map(
          (p) => `    ${p}: ${renderIRValue(ir, rule.declarations[p])};`,
        ),
        '  }',
      ].join('\n'),
    );
  }
  return blocks;
}

export function renderComponents(ir: DesignIR, ctx: PluginContext): string {
  assertUniqueNames(ir, sortedTokenIds(ir));
  const blocks = Object.keys(ir.components)
    .sort(codeUnitCompare)
    .filter((name) => isMappedForTailwind(ir.components[name]))
    .flatMap((name) => renderComponent(ir, ir.components[name]));
  const layer =
    blocks.length === 0
      ? '@layer components {\n}'
      : `@layer components {\n${blocks.join('\n\n')}\n}`;
  return `${[tailwindHeader(ir, ctx), '', layer].join('\n')}\n`;
}

export function renderIndex(ir: DesignIR, ctx: PluginContext): string {
  return `${tailwindHeader(ir, ctx)}\n\n@import './theme.css';\n@import './components.css';\n`;
}

/** All Tailwind output files, sorted by path. */
export function generateTailwind(
  ir: DesignIR,
  ctx: PluginContext,
): GeneratedFile[] {
  return [
    { path: 'components.css', contents: renderComponents(ir, ctx) },
    { path: 'index.css', contents: renderIndex(ir, ctx) },
    { path: 'theme.css', contents: renderTheme(ir, ctx) },
  ];
}
