/**
 * Every component's shells: the React component and the Flutter widget, written by hand, one file
 * each, and the Storybook file, generated.
 *
 * The line between the recipe and the shell is the line between look and behaviour. The recipe --
 * what a component looks like -- is generated from Figma and never written by hand. The shell --
 * props, slots, keyboard, focus, accessibility -- is written by hand, in TSX by a React engineer
 * and in Dart by a Flutter engineer (docs/engineering/architecture.md; owner decision
 * 2026-09-25). What the IR decides still reaches it
 * with no edit: its props types, its layer tree and its slot names are generated beside the recipe
 * and imported; a prop or slot Figma adds is a typecheck error in the shell, or a failure of the
 * component-parity test, which proves every one is reached; and a fix to a runtime helper
 * (`components/src/internal/`, `solar_flutter/lib/src/`) reaches every shell that imports it.
 *
 * The codegen writes only the stories here, and checks that each component's two shells exist,
 * without the header a generated file starts with.
 */

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { DESCRIPTORS, fileOfDescriptor } from '../components/index.mjs';
import { packagesDir } from '../util/paths.mjs';

export const componentsSrc = join(packagesDir, 'components', 'src');
export const storiesDir = join(packagesDir, 'components', 'stories');
export const flutterLib = join(packagesDir, 'solar_flutter', 'lib');
export const flutterComponents = join(flutterLib, 'src', 'components');

/** `Button` to `Button.tsx`. */
export const shellFileOf = (component) =>
  `${component.replace(/[^A-Za-z0-9]/g, '')}.tsx`;

/** `Button` to `solar_button.dart`. */
export const flutterFileOf = (component) =>
  `solar_${component.toLowerCase().replace(/[^a-z0-9]+/g, '_')}.dart`;

/** `Button` to `Button.stories.tsx`. */
export const storyFileOf = (component) =>
  shellFileOf(component).replace(/\.tsx$/, '.stories.tsx');

/** The first line of every generated shell: what it is generated from. */
export const headerOf = (component) =>
  `// Generated by @bwp-web/codegen from packages/codegen/src/components/${fileOfDescriptor(component)}. Do not edit.`;

/** Whether a file's text is a generated shell's: the header is how a stale one is told apart. */
export const isGenerated = (text) =>
  text.startsWith('// Generated by @bwp-web/codegen from packages/codegen/');

/**
 * A component's Storybook file. Its stories are generic (`stories/solar.tsx`, from the component's
 * visual case and IR), so the file only names the component; Storybook reads a story file
 * statically, which is why its default export is an object literal rather than a call.
 */
export const storyTemplate = (component) => {
  // On one line where it fits the repository's 80 columns, and otherwise as Prettier wraps it.
  const line = `export default { title: 'SOLAR/${component}', ...meta('${component}') } satisfies Meta;`;
  const meta =
    line.length <= 80
      ? line
      : `export default {
  title: 'SOLAR/${component}',
  ...meta('${component}'),
} satisfies Meta;`;
  return `import type { Meta, StoryObj } from '@storybook/react-vite';
import { meta, playground, variants } from './solar.js';

// Storybook reads a story file statically, so the default export is an object literal here.
${meta}
export const Playground: StoryObj = playground('${component}');
export const Variants: StoryObj = variants('${component}');
`;
};

/**
 * Every component's story, as an absolute path and its text, before formatting (the codegen
 * formats it as it does every generated file), with its two shells checked: each must exist,
 * without the generated header, since a shell is written by hand.
 *
 * @param {Array<{component: string}>} specs
 * @param {{src?: string, stories?: string, flutter?: string, exists?: (path: string) => boolean,
 *   read?: (path: string) => string, descriptors?: object[]}} [o] where the shells are, how a file
 *   is read, and the descriptors (a test's own)
 * @returns {Array<{path: string, text: string}>}
 */
export function renderShells(
  specs,
  {
    src = componentsSrc,
    stories = storiesDir,
    flutter = flutterComponents,
    exists = existsSync,
    read = (path) => readFileSync(path, 'utf8'),
    descriptors = DESCRIPTORS,
  } = {},
) {
  const byName = Object.fromEntries(descriptors.map((d) => [d.name, d]));
  return specs.map((spec) => {
    const name = spec.component;
    const d = byName[name];
    if (!d) throw new Error(`no descriptor for ${name}`);
    const story = {
      path: join(stories, storyFileOf(name)),
      text: `${headerOf(name)}\n${storyTemplate(name)}`,
    };
    // Checked as another component's state (Autocomplete Open, an open Autocomplete): no shells,
    // but its story.
    if (d.checkedAs) {
      if (!byName[d.checkedAs])
        throw new Error(
          `src/components/${fileOfDescriptor(name)}: ${name} is checked as ${d.checkedAs}, which is no component`,
        );
      return story;
    }
    for (const path of [
      join(src, shellFileOf(name)),
      join(flutter, flutterFileOf(name)),
    ]) {
      if (!exists(path))
        throw new Error(`${name}: its shell ${path} does not exist`);
      if (isGenerated(read(path)))
        throw new Error(
          `${name}: ${path} starts with the generated header, but a shell is written by hand; remove the header`,
        );
    }
    return story;
  });
}

/**
 * The generated shells in the shell directories that this run did not write: a component removed
 * from the list leaves its shells behind otherwise, exported by nothing. Only a file with a
 * generated header counts, so an owned shell and `internal/` are never touched, and a barrel
 * (`components.dart`) is kept because this run wrote it.
 *
 * @param {(path: string) => boolean} written whether this run wrote the file (util/write.mjs)
 * @returns {string[]} the stale shells' absolute paths
 */
export function staleShells(
  written,
  {
    dirs = [componentsSrc, storiesDir, flutterComponents],
    list = (dir) => (existsSync(dir) ? readdirSync(dir) : []),
    read = (path) => readFileSync(path, 'utf8'),
  } = {},
) {
  return dirs.flatMap((dir) =>
    list(dir)
      .filter((f) => /\.(tsx|dart)$/.test(f))
      .map((f) => join(dir, f))
      .filter((path) => !written(path) && isGenerated(read(path))),
  );
}
