/**
 * Every component's shells, generated: the React component, the Flutter widget and the Storybook
 * file, rendered from the templates in its descriptor (src/components/) on every `solar:codegen`.
 *
 * The line between the recipe and the shell is the line between look and behaviour. The recipe --
 * what a component looks like -- is generated from Figma and never written by hand. The shell --
 * props, slots, keyboard, focus, accessibility -- is written by hand, as the descriptor's templates,
 * functions of the IR: so a slot or prop Figma adds reaches the shells, and a fix to a shared helper
 * here (drawn.mjs, field.mjs, target.mjs) reaches every component that uses it, both proven by the
 * rebuild CI runs. The generated shell is never edited; its first line says where its template is.
 *
 * A component whose shell has to be edited as a file (a behaviour no template should hold) opts
 * out with `owned: true` in its descriptor: it keeps no templates, its shells are left alone, and
 * they must exist without the generated header, which is what makes the handover deliberate.
 */

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { DESCRIPTORS, fileOfDescriptor } from '../components/index.mjs';
import { packagesDir } from '../util/paths.mjs';
import { byPrefix, withLayerClasses } from '../util/classes.mjs';

export const componentsSrc = join(packagesDir, 'components', 'src');
export const storiesDir = join(packagesDir, 'components', 'stories');
export const flutterLib = join(packagesDir, 'solar_flutter', 'lib');
export const flutterComponents = join(flutterLib, 'src', 'components');

/**
 * The React shell templates, by component, from each component's descriptor. A template is a
 * function of the IR, so prop and slot names come from Figma rather than being retyped, but its
 * structure is written for the one MUI control it wraps.
 */
export const TEMPLATES = Object.fromEntries(
  DESCRIPTORS.filter((d) => d.templates?.react).map((d) => [
    d.name,
    d.templates.react,
  ]),
);

/**
 * The Flutter widget templates, by component: the same props as the React shell, from the same IR,
 * wrapping the Flutter control the overlay names, styled by the generated recipe.
 */
export const FLUTTER_TEMPLATES = Object.fromEntries(
  DESCRIPTORS.filter((d) => d.templates?.flutter).map((d) => [
    d.name,
    d.templates.flutter,
  ]),
);

/** `Button` to `Button.tsx`. */
export const shellFileOf = (component) =>
  `${component.replace(/[^A-Za-z0-9]/g, '')}.tsx`;

/** `Button` to `solar_button.dart`. */
export const flutterFileOf = (component) =>
  `solar_${component.toLowerCase().replace(/[^a-z0-9]+/g, '_')}.dart`;

/** `Button` to `Button.stories.tsx`. */
export const storyFileOf = (component) =>
  shellFileOf(component).replace(/\.tsx$/, '.stories.tsx');

/** The first line of every generated shell: what it is generated from. */
export const headerOf = (component) =>
  `// Generated by @bwp-web/codegen from packages/codegen/src/components/${fileOfDescriptor(component)}. Do not edit.`;

/** Whether a file's text is a generated shell's: the header is how a stale one is told apart. */
export const isGenerated = (text) =>
  text.startsWith('// Generated by @bwp-web/codegen from packages/codegen/');

/**
 * A component's Storybook file. Its stories are generic (`stories/solar.tsx`, from the component's
 * visual case and IR), so the file only names the component; Storybook reads a story file
 * statically, which is why its default export is an object literal rather than a call.
 */
export const storyTemplate = (component) => {
  // On one line where it fits the repository's 80 columns, and otherwise as Prettier wraps it.
  const line = `export default { title: 'SOLAR/${component}', ...meta('${component}') } satisfies Meta;`;
  const meta =
    line.length <= 80
      ? line
      : `export default {
  title: 'SOLAR/${component}',
  ...meta('${component}'),
} satisfies Meta;`;
  return `import type { Meta, StoryObj } from '@storybook/react-vite';
import { meta, playground, variants } from './solar.js';

// Storybook reads a story file statically, so the default export is an object literal here.
${meta}
export const Playground: StoryObj = playground('${component}');
export const Variants: StoryObj = variants('${component}');
`;
};

/**
 * Every generated shell for the specs, as absolute paths and their text, before formatting (the
 * codegen formats them as it does every generated file). An owned component contributes only its
 * story, and is checked instead: its shells must exist, without the header.
 *
 * @param {Array<{component: string}>} specs
 * @param {{src?: string, stories?: string, flutter?: string, exists?: (path: string) => boolean,
 *   read?: (path: string) => string, descriptors?: object[]}} [o] where the shells go, how a file
 *   is read, and the descriptors (a test's own)
 * @returns {Array<{path: string, text: string}>}
 */
export function renderShells(
  specs,
  {
    src = componentsSrc,
    stories = storiesDir,
    flutter = flutterComponents,
    exists = existsSync,
    read = (path) => readFileSync(path, 'utf8'),
    descriptors = DESCRIPTORS,
  } = {},
) {
  const byName = Object.fromEntries(descriptors.map((d) => [d.name, d]));
  // Each layer's class as its own, public or internal, wherever a template names it by the layer.
  const classes = byPrefix(specs);
  const own = (shell) =>
    shell.path.endsWith('.dart')
      ? shell
      : { ...shell, text: withLayerClasses(shell.text, classes) };
  return specs
    .flatMap((spec) => {
      const name = spec.component;
      const d = byName[name];
      if (!d) throw new Error(`no descriptor for ${name}`);
      const header = headerOf(name);
      const story = {
        path: join(stories, storyFileOf(name)),
        text: `${header}\n${storyTemplate(name)}`,
      };
      const react = join(src, shellFileOf(name));
      const widget = join(flutter, flutterFileOf(name));
      // Checked as another component's state (Autocomplete Open, an open Autocomplete): no shells,
      // but its story.
      if (d.checkedAs) {
        if (d.templates || d.owned)
          throw new Error(
            `src/components/${fileOfDescriptor(name)}: ${name} is checked as ${d.checkedAs}, so it has no shells, templates or owned files`,
          );
        if (!byName[d.checkedAs])
          throw new Error(
            `src/components/${fileOfDescriptor(name)}: ${name} is checked as ${d.checkedAs}, which is no component`,
          );
        return [story];
      }
      if (d.owned) {
        if (d.templates)
          throw new Error(
            `src/components/${fileOfDescriptor(name)}: ${name} is owned, so its shells are files, not templates; delete its templates`,
          );
        for (const path of [react, widget]) {
          if (!exists(path))
            throw new Error(
              `${name} is owned, but its shell ${path} does not exist`,
            );
          if (isGenerated(read(path)))
            throw new Error(
              `${name} is owned, but ${path} still starts with the generated header; remove the header to take it over`,
            );
        }
        return [story];
      }
      if (!d.templates?.react || !d.templates?.flutter)
        throw new Error(
          `src/components/${fileOfDescriptor(name)}: ${name} needs both shell templates, react and flutter, or owned: true`,
        );
      return [
        { path: react, text: `${header}\n${d.templates.react(spec)}` },
        { path: widget, text: `${header}\n${d.templates.flutter(spec)}` },
        story,
      ];
    })
    .map(own);
}

/**
 * The generated shells in the shell directories that this run did not write: a component removed
 * from the list leaves its shells behind otherwise, exported by nothing. Only a file with a
 * generated header counts, so an owned shell and `internal/` are never touched, and a barrel
 * (`components.dart`) is kept because this run wrote it.
 *
 * @param {(path: string) => boolean} written whether this run wrote the file (util/write.mjs)
 * @returns {string[]} the stale shells' absolute paths
 */
export function staleShells(
  written,
  {
    dirs = [componentsSrc, storiesDir, flutterComponents],
    list = (dir) => (existsSync(dir) ? readdirSync(dir) : []),
    read = (path) => readFileSync(path, 'utf8'),
  } = {},
) {
  return dirs.flatMap((dir) =>
    list(dir)
      .filter((f) => /\.(tsx|dart)$/.test(f))
      .map((f) => join(dir, f))
      .filter((path) => !written(path) && isGenerated(read(path))),
  );
}
