// The component stage: spec/components/<name>.json from docs/solar-web. The recipe emitters join
// it in milestone 3a tasks 5 and 6.
import { join } from 'node:path';
import {
  buildComponentSpec,
  loadComponent,
  loadWebCatalog,
} from '../normalize/components.mjs';
import { loadDefaults, loadOverlay } from '../normalize/overlay.mjs';
import { tokenNames } from '../normalize/recipe.mjs';
import { buildTokenSpec, loadContract } from '../normalize/tokens.mjs';
import { emitMuiComponents } from '../emit/mui-component.mjs';
import { emitFlutterComponents } from '../emit/flutter-component.mjs';
import { buildOracle } from '../verify/oracle.mjs';
import { specDir } from '../util/paths.mjs';
import { writeGenerated } from '../util/write.mjs';

export const name = 'components';

/** The components generated so far, by their Figma names. Milestone 3b adds the rest. */
export const COMPONENTS = ['Button', 'Spinner', 'Icon Button', 'Button Group'];

export const componentsDir = join(specDir, 'components');
export const verifyDir = join(specDir, 'verify');

/** `Button` to `button.json`, `Icon Button` to `icon-button.json`. */
export const fileOf = (component) =>
  `${component.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.json`;

export function build() {
  const catalog = loadWebCatalog();
  const contract = loadContract();
  const names = tokenNames(contract);
  // The recipe emitters resolve a text style into its parts and check every custom property they
  // name exists, so they need the token spec as well as the component IR.
  const tokens = buildTokenSpec(contract).spec;
  const defaults = loadDefaults();
  const built = COMPONENTS.map((component) => {
    const loaded = loadComponent(catalog, component);
    const overlay = loadOverlay(component);
    const { spec, deviations } = buildComponentSpec(loaded, {
      names,
      fileVersion: catalog.fileVersion,
      overlay,
      defaults,
    });
    // Beside the IR, never from it: the oracle reads the Figma set, and the IR only for names.
    const oracle = buildOracle(loaded.set, spec, deviations, {
      tokens,
      names,
      overlay,
      fileVersion: catalog.fileVersion,
    });
    return { spec, deviations, oracle };
  });
  return { built, tokens };
}

export function emit({ built, tokens }) {
  for (const { spec } of built)
    writeGenerated(
      join(componentsDir, fileOf(spec.component)),
      JSON.stringify(
        {
          $description: `SOLAR ${spec.component}: public API, platform states, slots and style recipe in token names. Generated by @bwp-web/codegen from docs/solar-web. Do not edit; decisions go in spec/overlay/, and the ones applied are listed under overlay.`,
          ...spec,
        },
        null,
        2,
      ) + '\n',
    );
  for (const { spec, oracle } of built)
    writeGenerated(
      join(verifyDir, fileOf(spec.component)),
      JSON.stringify(oracle, null, 2) + '\n',
    );
  const specs = built.map((b) => b.spec);
  return {
    counts: {
      specs: built.length,
      oracles: built.length,
      mui: emitMuiComponents(specs, tokens),
      flutter: emitFlutterComponents(specs, tokens),
    },
    deviations: built.flatMap((b) => b.deviations),
  };
}
