// The component stage: spec/components/<name>.json from docs/solar-web. The recipe emitters join
// it in milestone 3a tasks 5 and 6.
import { join } from 'node:path';
import {
  buildComponentSpec,
  loadComponent,
  loadWebCatalog,
} from '../normalize/components.mjs';
import { loadOverlay } from '../normalize/overlay.mjs';
import { tokenNames } from '../normalize/recipe.mjs';
import { buildTokenSpec, loadContract } from '../normalize/tokens.mjs';
import { emitMuiComponents } from '../emit/mui-component.mjs';
import { emitFlutterComponents } from '../emit/flutter-component.mjs';
import { specDir } from '../util/paths.mjs';
import { writeGenerated } from '../util/write.mjs';

export const name = 'components';

/** The components generated so far, by their Figma names. Milestone 3b adds the rest. */
export const COMPONENTS = ['Button'];

export const componentsDir = join(specDir, 'components');

/** `Button` to `button.json`, `Icon Button` to `icon-button.json`. */
export const fileOf = (component) =>
  `${component.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.json`;

export function build() {
  const catalog = loadWebCatalog();
  const contract = loadContract();
  const names = tokenNames(contract);
  // The recipe emitters resolve a text style into its parts and check every custom property they
  // name exists, so they need the token spec as well as the component IR.
  const tokens = buildTokenSpec(contract).spec;
  const built = COMPONENTS.map((component) =>
    buildComponentSpec(loadComponent(catalog, component), {
      names,
      fileVersion: catalog.fileVersion,
      overlay: loadOverlay(component),
    }),
  );
  return { built, tokens };
}

export function emit({ built, tokens }) {
  for (const { spec } of built)
    writeGenerated(
      join(componentsDir, fileOf(spec.component)),
      JSON.stringify(
        {
          $description: `SOLAR ${spec.component}: public API, platform states, slots and style recipe in token names. Generated by @bwp-web/codegen from docs/solar-web. Do not edit; decisions go in spec/overlay/, and the ones applied are listed under overlay.`,
          ...spec,
        },
        null,
        2,
      ) + '\n',
    );
  const specs = built.map((b) => b.spec);
  return {
    counts: {
      specs: built.length,
      mui: emitMuiComponents(specs, tokens),
      flutter: emitFlutterComponents(specs, tokens),
    },
    deviations: built.flatMap((b) => b.deviations),
  };
}
