/**
 * The Widgetbook Playground's generated Dart (src/emit/playground.mjs): the icon list and map, and
 * every component's controls, the same list Storybook draws.
 */

import { describe, expect, it } from 'vitest';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  dartControl,
  dartString,
  dartValue,
  renderWidgetbookControls,
  renderWidgetbookIcons,
} from '../src/emit/playground.mjs';
import { dartEnumValue } from '../src/emit/flutter.mjs';
import { dartVariantName } from '../src/emit/flutter-icons.mjs';
import { PLAYGROUND_VALUES } from '../src/playground/values.mjs';
import {
  controlsOf,
  playgroundData,
  stemsOf,
} from '../src/playground/controls.mjs';
import { specDir } from '../src/util/paths.mjs';

const readJson = (path) => JSON.parse(readFileSync(path, 'utf8'));
const iconSpec = readJson(join(specDir, 'icons.json'));
const specs = Object.fromEntries(
  readdirSync(join(specDir, 'components'))
    .filter((f) => f.endsWith('.json'))
    .map((f) => readJson(join(specDir, 'components', f)))
    .map((s) => [s.component, s]),
);

/**
 * Reads back the Dart constants the emitter writes: single-quoted strings with their escapes,
 * true, false, null, numbers, `<T>[…]` and `<K, V>{…}` literals, and `SolarIcons.x` references.
 */
function parseDart(text) {
  let i = 0;
  const ws = () => {
    while (/\s/.test(text[i])) i++;
  };
  const expect_ = (c) => {
    ws();
    if (text[i] !== c)
      throw new Error(`expected ${c} at ${i}: ${text.slice(i, i + 20)}`);
    i++;
  };
  const typeArgs = () => {
    ws();
    if (text[i] !== '<') return;
    let depth = 0;
    do {
      if (text[i] === '<') depth++;
      if (text[i] === '>') depth--;
      i++;
    } while (depth > 0);
  };
  const string = () => {
    expect_("'");
    let out = '';
    while (text[i] !== "'") {
      if (text[i] === '$') throw new Error(`unescaped $ at ${i}`);
      if (text[i] !== '\\') {
        out += text[i++];
        continue;
      }
      const c = text[++i];
      i++;
      if (c === 'n') out += '\n';
      else if (c === 'r') out += '\r';
      else if (c === 't') out += '\t';
      else if (c === 'u') {
        const end = text.indexOf('}', i);
        out += String.fromCodePoint(parseInt(text.slice(i + 1, end), 16));
        i = end + 1;
      } else out += c;
    }
    i++;
    return out;
  };
  const sequence = (close, item) => {
    const out = [];
    for (;;) {
      ws();
      if (text[i] === close) break;
      out.push(item());
      ws();
      if (text[i] === ',') i++;
    }
    i++;
    return out;
  };
  const value = () => {
    typeArgs();
    ws();
    const c = text[i];
    if (c === "'") return string();
    if (c === '[') {
      i++;
      return sequence(']', value);
    }
    if (c === '{') {
      i++;
      return Object.fromEntries(
        sequence('}', () => {
          const k = value();
          expect_(':');
          return [k, value()];
        }),
      );
    }
    const word = /^[\w.-]+/.exec(text.slice(i))[0];
    i += word.length;
    if (word === 'true') return true;
    if (word === 'false') return false;
    if (word === 'null') return null;
    if (/^-?\d/.test(word)) return Number(word);
    return { ref: word };
  };
  const consts = {};
  for (const m of text.matchAll(/^const (\w+) = /gm)) {
    i = m.index + m[0].length;
    consts[m[1]] = value();
  }
  return consts;
}

describe('renderWidgetbookIcons', () => {
  const dart = renderWidgetbookIcons(iconSpec);
  const { solarIconsByName, playgroundIcons } = parseDart(dart);

  it('maps every icon control value, in both styles, to its SolarIcons field, sorted', () => {
    const expected = Object.keys(iconSpec.icons).flatMap((stem) => [
      [stem, `SolarIcons.${dartVariantName(stem, 'outline')}`],
      [`${stem} solid`, `SolarIcons.${dartVariantName(stem, 'solid')}`],
    ]);
    expect(Object.keys(solarIconsByName)).toHaveLength(680);
    expect(
      Object.fromEntries(
        Object.entries(solarIconsByName).map(([k, v]) => [k, v.ref]),
      ),
    ).toEqual(Object.fromEntries(expected));
    expect(solarIconsByName['chevron-right solid']).toEqual({
      ref: 'SolarIcons.chevronRightSolid',
    });
    const keys = Object.keys(solarIconsByName);
    expect(keys).toEqual(
      [...keys].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0)),
    );
  });

  it('lists every stem in the icon spec’s order', () => {
    expect(playgroundIcons).toHaveLength(340);
    expect(playgroundIcons).toEqual(Object.keys(iconSpec.icons));
  });

  it('imports solar_flutter and carries the generated header', () => {
    expect(dart).toMatch(
      /^\/\/ Generated by @bwp-web\/codegen .*Do not edit\./,
    );
    expect(dart).toContain(
      "import 'package:solar_flutter/solar_flutter.dart';",
    );
  });
});

describe('renderWidgetbookControls', () => {
  const dart = renderWidgetbookControls(specs, iconSpec.icons);
  const consts = parseDart(dart);
  const { playgroundControls } = consts;
  /** A control as the web has it: the Dart entry less its Dart enum values. */
  const webOf = ({ dartOptions: _, ...c }) => c;

  it('gives Button the controls controlsOf derives from its IR, extras included', () => {
    expect(playgroundControls.Button).toEqual(
      controlsOf(specs.Button, specs, stemsOf(iconSpec.icons)).map(dartControl),
    );
    expect(playgroundControls.Button.at(-1)).toEqual({
      name: 'counter count',
      kind: 'integer',
      default: 3,
      min: 0,
    });
  });

  it('lists the same components and controls, in the same order, as Storybook', () => {
    const web = playgroundData().components;
    expect(Object.keys(playgroundControls)).toEqual(Object.keys(web));
    expect(
      Object.fromEntries(
        Object.entries(playgroundControls).map(([n, cs]) => [n, cs.map(webOf)]),
      ),
    ).toEqual(web);
  });

  it('gives every select its options as the Dart enum values the enum emitter names', () => {
    for (const [name, controls] of Object.entries(playgroundControls))
      for (const c of controls) {
        if (c.kind !== 'select') {
          expect(c.dartOptions, `${name} ${c.name}`).toBeUndefined();
          continue;
        }
        expect(c.dartOptions, `${name} ${c.name}`).toHaveLength(
          c.options.length,
        );
        expect(c.dartOptions).toEqual(c.options.map((o) => dartEnumValue(o)));
      }
    // Button Group's `full-width` is its Dart enum's `fullWidth`.
    expect(
      playgroundControls['Button Group'].find((c) => c.name === 'type'),
    ).toMatchObject({
      options: ['regular', 'full-width'],
      dartOptions: ['regular', 'fullWidth'],
    });
  });

  it('writes the fixed values both adapters use as constants', () => {
    expect(consts.playgroundIconNone).toBe(PLAYGROUND_VALUES.iconNone);
    expect(consts.playgroundIconSample).toBe(PLAYGROUND_VALUES.iconSample);
    expect(consts.playgroundIconSolid).toBe(PLAYGROUND_VALUES.iconSolid);
    expect(consts.playgroundWidths).toEqual(PLAYGROUND_VALUES.widths);
    expect(consts.playgroundLogLength).toBe(PLAYGROUND_VALUES.logLength);
  });

  it('escapes Figma’s words for Dart', () => {
    // Confirmation Dialog's words carry an apostrophe.
    expect(dart).toContain("you\\'ve made");
  });
});

describe('dartString and dartValue', () => {
  it('escapes quotes, backslashes, interpolation and control characters', () => {
    expect(dartString(`it's $5 \\ "x"\n\u0001`)).toBe(
      `'it\\'s \\$5 \\\\ "x"\\n\\u{1}'`,
    );
    const text = "a'b$c${d}\\e\tf\r\n";
    expect(parseDart(`const x = ${dartString(text)};`).x).toBe(text);
  });

  it('writes each kind of value a control holds', () => {
    expect(dartValue('md', 'x')).toBe("'md'");
    expect(dartValue(true, 'x')).toBe('true');
    expect(dartValue(3, 'x')).toBe('3');
    expect(dartValue(1.5, 'x')).toBe('1.5');
    expect(dartValue(null, 'x')).toBe('null');
    expect(dartValue(['md', "l'g"], 'x')).toBe("<String>['md', 'l\\'g']");
    expect(() => dartValue({ a: 1 }, 'x')).toThrow(/not a String/);
    expect(() => dartValue(Number.NaN, 'x')).toThrow(/no Dart constant/);
  });
});
