import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import * as stage from '../src/stages/components.mjs';
import { DESCRIPTORS, fileOfDescriptor } from '../src/components/index.mjs';
import {
  componentsSrc,
  FLUTTER_TEMPLATES,
  flutterComponents,
  flutterFileOf,
  headerOf,
  isGenerated,
  renderShells,
  shellFileOf,
  staleShells,
  storiesDir,
  storyFileOf,
  storyTemplate,
  TEMPLATES,
} from '../src/shells/index.mjs';

const { built } = stage.build();
const button = built.find((b) => b.spec.component === 'Button').spec;
const shell = TEMPLATES.Button(button);
const at = (dir) => ({ src: dir, stories: dir, flutter: dir });

describe('renderShells', () => {
  it('renders each component’s React shell, Flutter widget and story, each under the header naming its descriptor', () => {
    const out = renderShells([button], at('/x'));
    expect(out.map((o) => o.path)).toEqual([
      '/x/Button.tsx',
      '/x/solar_button.dart',
      '/x/Button.stories.tsx',
    ]);
    const header =
      '// Generated by @bwp-web/codegen from packages/codegen/src/components/button.mjs. Do not edit.';
    expect(headerOf('Button')).toBe(header);
    expect(out[0].text).toBe(`${header}\n${shell}`);
    expect(out[1].text).toBe(`${header}\n${FLUTTER_TEMPLATES.Button(button)}`);
    expect(out[2].text).toBe(`${header}\n${storyTemplate('Button')}`);
    for (const o of out) expect(isGenerated(o.text)).toBe(true);
    expect(fileOfDescriptor('Icon Button')).toBe('icon-button.mjs');
  });

  it('leaves an owned component’s shells alone, rendering only its story', () => {
    const owned = { name: 'Button', owned: true };
    const out = renderShells([button], {
      ...at('/x'),
      descriptors: [owned],
      exists: () => true,
      read: () => '/** SOLAR Button, taken over. */\n',
    });
    expect(out.map((o) => o.path)).toEqual(['/x/Button.stories.tsx']);
  });

  it('refuses an owned component that still has templates, has no shell, or kept the header', () => {
    const base = { ...at('/x'), exists: () => true, read: () => '// mine\n' };
    const withTemplates = { name: 'Button', owned: true, templates: {} };
    expect(() =>
      renderShells([button], { ...base, descriptors: [withTemplates] }),
    ).toThrow(/is owned, so its shells are files, not templates/);
    const owned = { name: 'Button', owned: true };
    expect(() =>
      renderShells([button], {
        ...base,
        descriptors: [owned],
        exists: () => false,
      }),
    ).toThrow(/is owned, but its shell \/x\/Button.tsx does not exist/);
    expect(() =>
      renderShells([button], {
        ...base,
        descriptors: [owned],
        read: () => `${headerOf('Button')}\n`,
      }),
    ).toThrow(/still starts with the generated header/);
  });

  it('refuses a component with neither both templates nor owned, rather than writing something generic', () => {
    const half = { name: 'Button', templates: { react: () => '' } };
    expect(() =>
      renderShells([button], { ...at('/x'), descriptors: [half] }),
    ).toThrow(/needs both shell templates, react and flutter, or owned: true/);
  });
});

describe('staleShells', () => {
  it('finds a generated shell this run did not write, and never a hand-written file', () => {
    const files = {
      '/x/Button.tsx': `${headerOf('Button')}\n`,
      '/x/Gone.tsx':
        '// Generated by @bwp-web/codegen from packages/codegen/src/components/gone.mjs. Do not edit.\n',
      '/x/Owned.tsx': '/** SOLAR Owned. */\n',
      '/x/index.ts':
        '// Generated by @bwp-web/codegen from packages/codegen/src/components/. Do not edit.\n',
    };
    const stale = staleShells((p) => p === '/x/Button.tsx', {
      dirs: ['/x'],
      list: () => Object.keys(files).map((p) => p.slice(3)),
      read: (p) => files[p],
    });
    expect(stale).toEqual(['/x/Gone.tsx']);
  });
});

describe('the Button shell', () => {
  it('takes its look from the recipe and holds no design value itself', () => {
    expect(shell).toContain("from '@bwp-web/styles/mui'");
    expect(shell).toContain('solarButtonStyle(');
    // The code, not the comments, which explain where the values come from.
    const code = shell
      .replace(/\/\*[\s\S]*?\*\//g, '')
      .replace(/\/\/.*$/gm, '');
    expect(code).not.toMatch(/#[0-9a-f]{3,8}\b/i);
    expect(code).not.toMatch(/\d+px|var\(--solar/);
  });

  it('takes its props from the IR, so a renamed axis reaches it', () => {
    for (const prop of Object.keys(button.api))
      expect(shell).toContain(`    ${prop},`);
    expect(shell).toContain(
      'solarButtonStyle({ size, variant, disabled, loading, danger })',
    );
  });

  it('gives the widget the IR’s props and slots, and no design value', () => {
    const widget = FLUTTER_TEMPLATES.Button(button);
    for (const prop of Object.keys(button.api))
      expect(widget).toMatch(new RegExp(`this\\.${prop} = `));
    for (const slot of ['iconLeading', 'iconTrailing', 'counter'])
      expect(widget).toContain(`this.${slot},`);
    expect(widget).toContain('style: SolarButtonRecipe.style(t, p)');
    const code = widget.replace(/\/\/.*$/gm, '');
    expect(code).not.toMatch(
      /Color\(0x|Colors\.(?!transparent)|EdgeInsets|fontSize|(width|height|size):\s*\d/,
    );
  });
});

describe('the stories', () => {
  it('write the export on one line where it fits 80 columns, and wrap it as Prettier does', () => {
    expect(storyTemplate('Button')).toContain(
      "export default { title: 'SOLAR/Button', ...meta('Button') } satisfies Meta;",
    );
    expect(storyTemplate('Segmented Control Item')).toContain(
      "export default {\n  title: 'SOLAR/Segmented Control Item',\n  ...meta('Segmented Control Item'),\n} satisfies Meta;",
    );
    expect(storyFileOf('Icon Button')).toBe('IconButton.stories.tsx');
  });
});

// What the rebuild committed: every component's shells, generated unless its descriptor owns them.
describe('the committed shells', () => {
  for (const d of DESCRIPTORS.filter((x) => !x.checkedAs)) {
    it(`${d.name}: ${d.owned ? 'owned, without the header' : 'generated, under its header'}`, () => {
      const files = [
        join(componentsSrc, shellFileOf(d.name)),
        join(flutterComponents, flutterFileOf(d.name)),
      ];
      for (const file of files) {
        const text = readFileSync(file, 'utf8');
        if (d.owned) expect(isGenerated(text), file).toBe(false);
        else expect(text.split('\n')[0], file).toBe(headerOf(d.name));
      }
      const story = readFileSync(join(storiesDir, storyFileOf(d.name)), 'utf8');
      expect(story).toContain(`title: 'SOLAR/${d.name}'`);
    });
  }
});
