// Generated by @bwp-web/codegen from packages/codegen/src/components/. Do not edit.
// The Flutter registry: a case per generated component, by its name. The check requires one
// for every oracle under spec/verify/, so a new component cannot go unmeasured.

import '../harness.dart';
import 'button.dart';
import 'button_group.dart';
import 'icon_button.dart';
import 'spinner.dart';
import 'statusindicator.dart';

final cases = <String, VisualCase>{
  'Button': buttonCase,
  'Button Group': buttonGroupCase,
  'Icon Button': iconButtonCase,
  'Spinner': spinnerCase,
  'StatusIndicator': statusIndicatorCase,
};
