import type { DesignIR } from '../ir/types.js';
import { codeUnitCompare } from '../sources.js';
import type { CoverageEntry, TargetPlugin } from '../targets/plugin.js';

export interface CoverageReport {
  targets: string[];
  components: string[];
  /** Sorted by component, then target. */
  entries: CoverageEntry[];
  unmapped: CoverageEntry[];
}

export function computeCoverage(
  ir: DesignIR,
  plugins: readonly TargetPlugin[],
): CoverageReport {
  const entries = plugins
    .flatMap((p) => p.coverage(ir))
    .sort(
      (a, b) =>
        codeUnitCompare(a.component, b.component) ||
        codeUnitCompare(a.target, b.target),
    );
  return {
    targets: plugins.map((p) => p.id).sort(codeUnitCompare),
    components: Object.keys(ir.components).sort(codeUnitCompare),
    entries,
    unmapped: entries.filter((e) => e.status === 'unmapped'),
  };
}

/** Escapes text for a Markdown table cell: collapses whitespace, then escapes `|` and `` ` ``. */
function escapeCell(text: string): string {
  return text.replace(/\s+/g, ' ').replace(/\|/g, '\\|').replace(/`/g, '\\`');
}

function cell(entry: CoverageEntry | undefined): string {
  if (!entry) {
    return '';
  }
  switch (entry.status) {
    case 'supported':
      return 'supported';
    case 'partial': {
      const ignored = (entry.ignored ?? []).map((p) => `\`${p}\``).join(', ');
      const unsupported = (entry.unsupported ?? [])
        .map((p) => `\`${p}\``)
        .join(', ');
      const parts = [
        ignored ? `ignores ${ignored}` : '',
        unsupported ? `unsupported ${unsupported}` : '',
      ].filter((s) => s !== '');
      return `partial (${parts.join('; ')})`;
    }
    case 'unmapped':
      return '**unmapped**';
    case 'excluded':
      return `excluded: ${escapeCell(entry.reason ?? '')}`;
  }
}

/** The committed coverage document. Generated; the header says so. */
export function renderCoverageMarkdown(
  report: CoverageReport,
  ir: DesignIR,
  compilerVersion: string,
): string {
  const byKey = new Map(
    report.entries.map((e) => [`${e.component}|${e.target}`, e]),
  );
  const lines = [
    `<!-- Generated by @bwp-web/ds-compiler ${compilerVersion} from design.ir.json; source hash ${ir.meta.sourceHash}. Do not edit; run bwp-ds verify. -->`,
    '',
    '# Coverage',
    '',
    'Which components each target covers. `supported`: every rule is generated.',
    '`partial`: the manifest ignores some properties for this target.',
    '`unmapped`: the manifest has no entry for this target, and `bwp-ds verify` fails.',
    '`excluded`: left out on purpose, with the reason from the manifest.',
    '',
    `| Component | ${report.targets.join(' | ')} |`,
    `| --- | ${report.targets.map(() => '---').join(' | ')} |`,
    ...report.components.map(
      (c) =>
        `| \`${c}\` | ${report.targets
          .map((t) => cell(byKey.get(`${c}|${t}`)))
          .join(' | ')} |`,
    ),
  ];
  return `${lines.join('\n')}\n`;
}
