import { describe, expect, it } from 'vitest';
import { tailwindPlugin } from '../src/targets/tailwind/index.js';
import type { TargetPlugin } from '../src/targets/plugin.js';
import {
  computeCoverage,
  renderCoverageMarkdown,
} from '../src/verify/coverage.js';
import { twBuild, twRoot } from './tailwind-fixture.js';

describe('coverage', () => {
  const { ir } = twBuild(
    twRoot({
      'src/components/dot/dot.manifest.json': JSON.stringify({
        name: 'dot',
        displayName: 'Dot',
        baseline: false,
      }),
      'src/components/dot/dot.css': '.fx-dot {\n  display: inline-block;\n}\n',
    }),
  );

  it('computes one entry per component and target with the right status', () => {
    const report = computeCoverage(ir, [tailwindPlugin]);
    expect(report.targets).toEqual(['tailwind']);
    expect(report.components).toEqual(['chip', 'dot', 'pill', 'tag']);
    expect(report.entries).toEqual([
      { component: 'chip', target: 'tailwind', status: 'supported' },
      { component: 'dot', target: 'tailwind', status: 'unmapped' },
      {
        component: 'pill',
        target: 'tailwind',
        status: 'excluded',
        reason: 'starter content',
      },
      {
        component: 'tag',
        target: 'tailwind',
        status: 'partial',
        ignored: ['opacity'],
      },
    ]);
    expect(report.unmapped).toEqual([
      { component: 'dot', target: 'tailwind', status: 'unmapped' },
    ]);
  });

  it('renders a generated Markdown table', () => {
    const md = renderCoverageMarkdown(
      computeCoverage(ir, [tailwindPlugin]),
      ir,
      '0.0.0-test',
    );
    const lines = md.split('\n');
    expect(lines[0]).toBe(
      `<!-- Generated by @bwp-web/ds-compiler 0.0.0-test from design.ir.json; source hash ${ir.meta.sourceHash}. Do not edit; run bwp-ds verify. -->`,
    );
    expect(md).toContain('# Coverage');
    expect(md).toContain('| Component | tailwind |');
    expect(md).toContain('| `chip` | supported |');
    expect(md).toContain('| `dot` | **unmapped** |');
    expect(md).toContain('| `pill` | excluded: starter content |');
    expect(md).toContain('| `tag` | partial (ignores `opacity`) |');
    expect(md.endsWith('\n')).toBe(true);
  });

  it('lists only targets that produced entries, so an auxiliary plugin adds no column', () => {
    const { ir } = twBuild(twRoot());
    const silent: TargetPlugin = {
      id: 'aux',
      auxiliary: true,
      generate: () => [],
      reparse: () => null,
      coverage: () => [],
      isMapped: () => false,
      ignoredProperties: () => new Set(),
    };
    const report = computeCoverage(ir, [tailwindPlugin, silent]);
    expect(report.targets).toEqual(['tailwind']);
    expect(renderCoverageMarkdown(report, ir, '0.0.0-test')).not.toContain(
      'aux',
    );
  });

  it('escapes an exclusion reason for the Markdown table', () => {
    const { ir: withReason } = twBuild(
      twRoot({
        'src/components/weird/weird.manifest.json': JSON.stringify({
          name: 'weird',
          displayName: 'Weird',
          baseline: false,
          targets: {
            tailwind: { excluded: 'a | pipe\nand a `tick`' },
          },
        }),
        'src/components/weird/weird.css':
          '.fx-weird {\n  display: inline-block;\n}\n',
      }),
    );
    const md = renderCoverageMarkdown(
      computeCoverage(withReason, [tailwindPlugin]),
      withReason,
      '0.0.0-test',
    );
    expect(md).toContain('| `weird` | excluded: a \\| pipe and a \\`tick\\` |');
  });
});
