import { describe, expect, it } from 'vitest';
import { Diagnostics } from '../src/errors.js';
import { serializeIR } from '../src/ir/serialize.js';
import type { DesignIR } from '../src/ir/types.js';
import type { MuiCatalog } from '../src/targets/mui/catalog.js';
import { buildMuiModel, muiModelSchema } from '../src/targets/mui/model.js';
import { BTN_FILES, FX_CATALOG } from './mui-mapped-fixture.js';
import { twBuild, twContext, twRoot } from './tailwind-fixture.js';

function modelFor(extra: Record<string, string> = {}) {
  const root = twRoot(extra);
  const { ir, config } = twBuild(root);
  const diag = new Diagnostics();
  const model = buildMuiModel(ir, null, twContext(root, config), diag);
  return { model, diag, ir };
}

describe('mui model', () => {
  it('places color tokens per color scheme and everything else under tokens, all as strings', () => {
    const { model, diag } = modelFor({
      'src/tokens/font-weight.css':
        ':root {\n  --fx-font-weight-semibold: 600;\n}\n',
      'src/tokens/z-index.css': ':root {\n  --fx-z-index-modal: 1000;\n}\n',
      'src/tokens/opacity.css': ':root {\n  --fx-opacity-disabled: 0.4;\n}\n',
      'src/tokens/duration.css': ':root {\n  --fx-duration-fast: 150ms;\n}\n',
    });
    expect(diag.errors).toEqual([]);
    const theme = model!.themeOptions;
    expect(theme.cssVariables).toEqual({
      cssVarPrefix: 'fx',
      colorSchemeSelector: 'data-fx-theme',
    });
    expect(theme.defaultColorScheme).toBe('light');
    expect(Object.keys(theme.colorSchemes)).toEqual(['light', 'dark']);
    expect(theme.colorSchemes.light.palette.tokens).toEqual({
      'neutral-900': '#111111',
      'text-default': 'var(--fx-palette-tokens-neutral-900)',
    });
    expect(theme.colorSchemes.dark.palette.tokens).toEqual({
      'neutral-900': '#111111',
      'text-default': '#ffffff',
    });
    expect(Object.keys(theme.tokens)).toEqual([
      'duration',
      'fontFamily',
      'fontWeight',
      'opacity',
      'shadow',
      'space',
      'zIndex',
    ]);
    expect(theme.tokens.space).toEqual({ '2': '8px' });
    expect(theme.tokens.fontFamily).toEqual({
      body: "'Open Sans', Arial, sans-serif",
    });
    // renderShadow always renders dimensions with an explicit unit, matching
    // the tailwind target's theme.css (see test/tailwind-generate.test.ts).
    expect(theme.tokens.shadow).toEqual({
      focus: '0px 0px 0px 2px var(--fx-palette-tokens-neutral-900)',
    });
    expect(theme.tokens.fontWeight).toEqual({ semibold: '600' });
    expect(theme.tokens.zIndex).toEqual({ modal: '1000' });
    expect(theme.tokens.opacity).toEqual({ disabled: '0.4' });
    expect(theme.tokens.duration).toEqual({ fast: '150ms' });
    expect(model!.framework).toEqual({
      name: '@mui/material',
      range: '^9.4.0',
      version: null,
    });
    expect(model!.generated).toMatch(
      /^Generated by @bwp-web\/ds-compiler 0\.0\.0-test for target mui from design\.ir\.json \(source hash [0-9a-f]+\)\. Do not edit; run bwp-ds generate\.$/,
    );
  });

  it('turns the base rule into styleOverrides.root and every other rule into an ordered variant', () => {
    const { model } = modelFor();
    const chip = model!.themeOptions.components.FxChip;
    expect(chip.styleOverrides.root).toEqual({
      color: 'var(--fx-palette-tokens-text-default)',
      display: 'inline-flex',
      fontFamily: 'var(--fx-tokens-fontFamily-body)',
      paddingBottom: 'var(--fx-tokens-space-2)',
      paddingLeft: 'var(--fx-tokens-space-2)',
      paddingRight: 'var(--fx-tokens-space-2)',
      paddingTop: 'var(--fx-tokens-space-2)',
    });
    expect(chip.variants).toEqual([
      {
        props: {},
        style: { '&:hover': { boxShadow: 'var(--fx-tokens-shadow-focus)' } },
      },
      { props: {}, style: { '&:disabled': { opacity: '0.4' } } },
      { props: { tone: 'loud' }, style: { '&&': { minWidth: '44px' } } },
      { props: {}, style: { '& .FxChip-icon': { width: '20px' } } },
    ]);
  });

  it('drops ignored properties and rules left empty by them; uses aria-disabled for a div root', () => {
    const { model } = modelFor();
    const tag = model!.themeOptions.components.FxTag;
    expect(tag).toEqual({
      styleOverrides: { root: { display: 'inline-block' } },
      variants: [],
    });
    expect(model!.components.tag).toEqual({
      name: 'tag',
      exportName: 'Tag',
      themeKey: 'FxTag',
      rootElement: 'div',
      axes: {},
      stateProps: [
        { state: 'disabled', prop: 'disabled', attribute: 'aria-disabled' },
      ],
      slots: {},
      childrenSlot: null,
      kind: 'own',
      mapped: null,
    });
  });

  it('describes the React shell: axes, state props, slots, children slot', () => {
    const { model } = modelFor();
    expect(model!.components.chip).toEqual({
      name: 'chip',
      exportName: 'Chip',
      themeKey: 'FxChip',
      rootElement: 'button',
      axes: {
        tone: { values: ['quiet', 'loud'], default: 'quiet', prop: 'tone' },
      },
      stateProps: [
        { state: 'disabled', prop: 'disabled', attribute: 'disabled' },
      ],
      slots: {
        icon: {
          element: 'span',
          optional: true,
          className: 'FxChip-icon',
          prop: 'icon',
        },
      },
      childrenSlot: null,
      kind: 'own',
      mapped: null,
    });
    expect(Object.keys(model!.components)).toEqual(['chip', 'tag']);
    expect(Object.keys(model!.themeOptions.components)).toEqual([
      'FxChip',
      'FxTag',
    ]);
  });

  it('routes children into the label slot when there is one', () => {
    const { model } = modelFor({
      'src/components/card/card.manifest.json': JSON.stringify({
        name: 'card',
        displayName: 'Card',
        baseline: false,
        states: ['hover', 'pressed'],
        slots: {
          root: { element: 'article' },
          media: { element: 'div', optional: true },
          label: { element: 'h3' },
          body: { element: 'p' },
        },
        targets: { tailwind: {}, mui: {} },
      }),
      'src/components/card/card.css':
        '.fx-card {\n  display: block;\n}\n.fx-card[aria-pressed="true"] .fx-card__label {\n  display: none;\n}\n',
    });
    const card = model!.components.card;
    expect(card.childrenSlot).toBe('label');
    expect(Object.keys(card.slots)).toEqual(['media', 'label', 'body']);
    expect(card.stateProps).toEqual([
      { state: 'pressed', prop: 'pressed', attribute: 'aria-pressed' },
    ]);
    expect(model!.themeOptions.components.FxCard.variants).toEqual([
      {
        props: {},
        style: { '&[aria-pressed="true"] .FxCard-label': { display: 'none' } },
      },
    ]);
  });

  it('validates against its own schema', () => {
    const { model } = modelFor();
    expect(
      muiModelSchema.safeParse(JSON.parse(JSON.stringify(model))).success,
    ).toBe(true);
    expect(muiModelSchema.safeParse({ ...model, extra: 1 }).success).toBe(
      false,
    );
  });

  it('rejects a mode selector MUI cannot express (DS-E084 at the config)', () => {
    const config = JSON.parse(
      JSON.stringify({
        name: 'Fictional',
        prefix: 'fx',
        modes: ['light', 'dark'],
        defaultMode: 'light',
        modeSelector: 'html[data-fx-theme="{mode}"]',
        targets: {
          tailwind: { outDir: 'out/tailwind' },
          mui: { outDir: 'out/mui' },
        },
        coverageFile: 'out/coverage.md',
      }),
    );
    const { model, diag } = modelFor({
      'ds.config.json': JSON.stringify(config, null, 2),
      'src/tokens/color.css': [
        ':root {',
        '  --fx-color-neutral-900: #111111;',
        '  --fx-color-text-default: var(--fx-color-neutral-900);',
        '}',
        'html[data-fx-theme="dark"] {',
        '  --fx-color-text-default: #ffffff;',
        '}',
        '',
      ].join('\n'),
    });
    expect(model).toBeNull();
    expect(diag.errors.map((d) => [d.code, d.location?.file])).toEqual([
      ['DS-E084', 'ds.config.json'],
    ]);
    expect(diag.errors[0].message).toContain('html[data-fx-theme="{mode}"]');
  });

  it('rejects modes other than light and dark, one DS-E084 per mode', () => {
    const config = JSON.parse(
      JSON.stringify({
        name: 'Fictional',
        prefix: 'fx',
        modes: ['day', 'night'],
        defaultMode: 'day',
        targets: {
          tailwind: { outDir: 'out/tailwind' },
          mui: { outDir: 'out/mui' },
        },
        coverageFile: 'out/coverage.md',
      }),
    );
    const { model, diag } = modelFor({
      'ds.config.json': JSON.stringify(config, null, 2),
      'src/tokens/color.css': [
        ':root {',
        '  --fx-color-neutral-900: #111111;',
        '  --fx-color-text-default: var(--fx-color-neutral-900);',
        '}',
        ':root[data-fx-theme="night"] {',
        '  --fx-color-text-default: #ffffff;',
        '}',
        '',
      ].join('\n'),
    });
    expect(model).toBeNull();
    expect(diag.errors.map((d) => [d.code, d.location?.file])).toEqual([
      ['DS-E084', 'ds.config.json'],
      ['DS-E084', 'ds.config.json'],
    ]);
    expect(diag.errors[0].message).toContain('mode "day"');
    expect(diag.errors[1].message).toContain('mode "night"');
  });

  it('rejects a non-color token that varies by mode (DS-E084 at the token)', () => {
    const { model, diag } = modelFor({
      'src/tokens/space.css':
        ':root {\n  --fx-space-2: 8px;\n}\n:root[data-fx-theme="dark"] {\n  --fx-space-2: 10px;\n}\n',
    });
    expect(model).toBeNull();
    expect(diag.errors.map((d) => [d.code, d.location?.file])).toEqual([
      ['DS-E084', 'src/tokens/space.css'],
    ]);
    expect(diag.errors[0].message).toContain('--fx-space-2');
  });

  it('rejects components a React shell cannot express (DS-E085), naming the reason', () => {
    const { model, diag } = modelFor({
      'src/components/dot/dot.manifest.json': JSON.stringify({
        name: 'dot',
        displayName: 'Dot',
        baseline: false,
        states: ['busy'],
        slots: { root: { element: 'my-dot' }, style: { element: 'span' } },
        targets: { tailwind: {}, mui: {} },
      }),
      'src/components/dot/dot.css':
        '.fx-dot {\n  display: block;\n}\n.fx-dot[data-state="busy"] {\n  display: none;\n}\n',
    });
    expect(model).toBeNull();
    const messages = diag.errors.map((d) => d.message);
    expect(diag.errors.every((d) => d.code === 'DS-E085')).toBe(true);
    expect(
      diag.errors.every(
        (d) => d.location?.file === 'src/components/dot/dot.manifest.json',
      ),
    ).toBe(true);
    expect(messages.some((m) => m.includes('"my-dot"'))).toBe(true);
    expect(messages.some((m) => m.includes('state "busy"'))).toBe(true);
    expect(messages.some((m) => m.includes('slot "style"'))).toBe(true);
  });

  it('leaves excluded and unmapped components out', () => {
    const { model } = modelFor({
      'src/components/free/free.manifest.json': JSON.stringify({
        name: 'free',
        displayName: 'Free',
        baseline: false,
        targets: { tailwind: {} },
      }),
      'src/components/free/free.css': '.fx-free {\n  display: block;\n}\n',
    });
    expect(model!.components.pill).toBeUndefined();
    expect(model!.components.free).toBeUndefined();
    expect(model!.themeOptions.components.FxPill).toBeUndefined();
  });

  it('rejects a root element that is not an HTML element', () => {
    const { model, diag } = modelFor({
      'src/components/thing/thing.manifest.json': JSON.stringify({
        name: 'thing',
        displayName: 'Thing',
        baseline: false,
        slots: { root: { element: 'foo' } },
        targets: { tailwind: {}, mui: {} },
      }),
      'src/components/thing/thing.css': '.fx-thing {\n  display: block;\n}\n',
    });
    expect(model).toBeNull();
    expect(
      diag.errors.some(
        (d) =>
          d.code === 'DS-E085' &&
          d.message.includes('"foo"') &&
          d.message.includes('not an HTML element'),
      ),
    ).toBe(true);
  });

  it('accepts svg and article as HTML elements', () => {
    const { model, diag } = modelFor({
      'src/components/icon-shape/icon-shape.manifest.json': JSON.stringify({
        name: 'icon-shape',
        displayName: 'Icon shape',
        baseline: false,
        slots: { root: { element: 'article' }, mark: { element: 'svg' } },
        targets: { tailwind: {}, mui: {} },
      }),
      'src/components/icon-shape/icon-shape.css':
        '.fx-icon-shape {\n  display: block;\n}\n',
    });
    expect(diag.errors).toEqual([]);
    expect(model!.components['icon-shape'].rootElement).toBe('article');
    expect(model!.components['icon-shape'].slots.mark.element).toBe('svg');
  });

  it('accepts an SVG child element inside an svg root', () => {
    const { model, diag } = modelFor({
      'src/components/icon-glyph/icon-glyph.manifest.json': JSON.stringify({
        name: 'icon-glyph',
        displayName: 'Icon glyph',
        baseline: false,
        slots: { root: { element: 'svg' }, mark: { element: 'path' } },
        targets: { tailwind: {}, mui: {} },
      }),
      'src/components/icon-glyph/icon-glyph.css':
        '.fx-icon-glyph {\n  display: block;\n}\n',
    });
    expect(diag.errors).toEqual([]);
    expect(model!.components['icon-glyph'].rootElement).toBe('svg');
    expect(model!.components['icon-glyph'].slots.mark.element).toBe('path');
  });

  it('rejects a void element, which cannot hold a slot or children (DS-E085)', () => {
    const { model, diag } = modelFor({
      'src/components/pic/pic.manifest.json': JSON.stringify({
        name: 'pic',
        displayName: 'Pic',
        baseline: false,
        slots: { root: { element: 'img' } },
        targets: { tailwind: {}, mui: {} },
      }),
      'src/components/pic/pic.css': '.fx-pic {\n  display: block;\n}\n',
    });
    expect(model).toBeNull();
    expect(
      diag.errors.some(
        (d) =>
          d.code === 'DS-E085' &&
          d.message.includes('slot "root"') &&
          d.message.includes('void element "img"'),
      ),
    ).toBe(true);
  });

  it('rejects an SVG-only element nested outside an svg root (DS-E085)', () => {
    const { model, diag } = modelFor({
      'src/components/icon-bad/icon-bad.manifest.json': JSON.stringify({
        name: 'icon-bad',
        displayName: 'Icon bad',
        baseline: false,
        slots: {
          root: { element: 'span' },
          glyph: { element: 'svg' },
          mark: { element: 'path' },
        },
        targets: { tailwind: {}, mui: {} },
      }),
      'src/components/icon-bad/icon-bad.css':
        '.fx-icon-bad {\n  display: block;\n}\n',
    });
    expect(model).toBeNull();
    expect(
      diag.errors.some(
        (d) =>
          d.code === 'DS-E085' &&
          d.message.includes('slot "mark"') &&
          d.message.includes('SVG element "path"') &&
          d.message.includes('root is "span"'),
      ),
    ).toBe(true);
    // "svg" itself is a plain HTML element wherever it is nested; only the
    // svg-only "path" slot is rejected.
    expect(diag.errors.some((d) => d.message.includes('slot "glyph"'))).toBe(
      false,
    );
  });

  it('rejects two axes that camelCase to the same React prop (DS-E085)', () => {
    const { model, diag } = modelFor({
      'src/components/combo/combo.manifest.json': JSON.stringify({
        name: 'combo',
        displayName: 'Combo',
        baseline: false,
        axes: {
          'a-1b': { values: ['x', 'y'], default: 'x' },
          a1b: { values: ['p', 'q'], default: 'p' },
        },
        targets: { tailwind: {}, mui: {} },
      }),
      'src/components/combo/combo.css': '.fx-combo {\n  display: block;\n}\n',
    });
    expect(model).toBeNull();
    expect(
      diag.errors.some(
        (d) =>
          d.code === 'DS-E085' &&
          d.message.includes('"a-1b"') &&
          d.message.includes('"a1b"'),
      ),
    ).toBe(true);
  });

  it('rejects a slot named "sx" (a reserved MUI prop)', () => {
    const { model, diag } = modelFor({
      'src/components/box/box.manifest.json': JSON.stringify({
        name: 'box',
        displayName: 'Box',
        baseline: false,
        slots: { root: { element: 'div' }, sx: { element: 'span' } },
        targets: { tailwind: {}, mui: {} },
      }),
      'src/components/box/box.css': '.fx-box {\n  display: block;\n}\n',
    });
    expect(model).toBeNull();
    expect(
      diag.errors.some(
        (d) => d.code === 'DS-E085' && d.message.includes('slot "sx"'),
      ),
    ).toBe(true);
  });

  it('is deterministic across an IR that has been serialized and reparsed', () => {
    const root = twRoot();
    const { ir, config } = twBuild(root);
    const ctx = twContext(root, config);
    const model1 = buildMuiModel(ir, null, ctx, new Diagnostics());
    const roundTripped = JSON.parse(serializeIR(ir)) as DesignIR;
    const model2 = buildMuiModel(roundTripped, null, ctx, new Diagnostics());
    expect(JSON.stringify(model1)).toBe(JSON.stringify(model2));
  });

  it('accepts an axis and a pseudo-class state that share a name', () => {
    const { model, diag } = modelFor({
      'src/components/toggle/toggle.manifest.json': JSON.stringify({
        name: 'toggle',
        displayName: 'Toggle',
        baseline: false,
        axes: { hover: { values: ['on', 'off'], default: 'off' } },
        states: ['hover'],
        targets: { tailwind: {}, mui: {} },
      }),
      'src/components/toggle/toggle.css': [
        '.fx-toggle {',
        '  display: block;',
        '}',
        '.fx-toggle:hover {',
        '  opacity: 0.8;',
        '}',
        '.fx-toggle[data-hover="on"] {',
        '  opacity: 1;',
        '}',
        '',
      ].join('\n'),
    });
    expect(diag.errors).toEqual([]);
    expect(model!.components.toggle.axes.hover).toEqual({
      values: ['on', 'off'],
      default: 'off',
      prop: 'hover',
    });
    expect(model!.components.toggle.stateProps).toEqual([]);
  });

  it('camelCases a kebab-case axis and slot into their prop names', () => {
    const { model } = modelFor({
      'src/components/widget/widget.manifest.json': JSON.stringify({
        name: 'widget',
        displayName: 'Widget',
        baseline: false,
        axes: {
          'icon-position': { values: ['start', 'end'], default: 'start' },
        },
        slots: {
          root: { element: 'div' },
          'sub-title': { element: 'span', optional: true },
        },
        targets: { tailwind: {}, mui: {} },
      }),
      'src/components/widget/widget.css': [
        '.fx-widget {',
        '  display: block;',
        '}',
        '.fx-widget[data-icon-position="end"] {',
        '  display: flex;',
        '}',
        '',
      ].join('\n'),
    });
    const widget = model!.components.widget;
    expect(widget.axes['icon-position'].prop).toBe('iconPosition');
    expect(widget.slots['sub-title'].prop).toBe('subTitle');
    expect(model!.themeOptions.components.FxWidget.variants).toEqual([
      {
        props: { iconPosition: 'end' },
        style: { '&&': { display: 'flex' } },
      },
    ]);
  });

  it('orders variant props by axis declaration order across two axes and a slot', () => {
    const { model } = modelFor({
      'src/components/gauge/gauge.manifest.json': JSON.stringify({
        name: 'gauge',
        displayName: 'Gauge',
        baseline: false,
        axes: {
          tone: { values: ['a', 'b'], default: 'a' },
          size: { values: ['sm', 'lg'], default: 'sm' },
        },
        states: ['hover'],
        slots: { root: { element: 'div' }, icon: { element: 'span' } },
        targets: { tailwind: {}, mui: {} },
      }),
      'src/components/gauge/gauge.css': [
        '.fx-gauge {',
        '  display: block;',
        '}',
        '.fx-gauge[data-size="lg"][data-tone="b"]:hover .fx-gauge__icon {',
        '  opacity: 0.5;',
        '}',
        '',
      ].join('\n'),
    });
    expect(model!.themeOptions.components.FxGauge.variants).toEqual([
      {
        props: { tone: 'b', size: 'lg' },
        style: { '&&&:hover .FxGauge-icon': { opacity: '0.5' } },
      },
    ]);
  });

  it('rejects a model whose variant style has more than one selector key', () => {
    const { model } = modelFor();
    const withTwoKeys = {
      ...model,
      themeOptions: {
        ...model!.themeOptions,
        components: {
          FxChip: {
            styleOverrides: { root: {} },
            variants: [
              {
                props: {},
                style: {
                  '&:hover': { color: 'red' },
                  '&:focus': { color: 'blue' },
                },
              },
            ],
          },
        },
      },
    };
    expect(muiModelSchema.safeParse(withTwoKeys).success).toBe(false);
  });
});

describe('mui model: mapped components', () => {
  function mapped(files = BTN_FILES, catalog: MuiCatalog | null = FX_CATALOG) {
    const root = twRoot(files);
    const { ir, config } = twBuild(root);
    const diag = new Diagnostics();
    const model = buildMuiModel(ir, catalog, twContext(root, config), diag);
    return { model, diag, ir };
  }

  it('builds a MuiButton theme entry: defaultProps, base rule, resets, then design-system variants', () => {
    const { model, diag } = mapped();
    expect(diag.errors).toEqual([]);
    expect(model!.framework).toEqual({
      name: '@mui/material',
      range: '^9.4.0',
      version: '9.4.0',
    });
    const entry = model!.themeOptions.components.MuiButton;
    expect(Object.keys(entry)).toEqual([
      'defaultProps',
      'styleOverrides',
      'variants',
    ]);
    expect(entry.defaultProps).toEqual({
      disableElevation: true,
      disableFocusRipple: true,
      disableRipple: true,
      disableTouchRipple: true,
      focusRipple: false,
      variant: 'quiet',
    });
    expect(entry.styleOverrides.root).toEqual({
      color: 'var(--fx-palette-tokens-text-default)',
      cursor: 'pointer',
      display: 'inline-flex',
      fontFamily: 'var(--fx-tokens-fontFamily-body)',
      paddingBottom: 'var(--fx-tokens-space-2)',
      paddingLeft: 'var(--fx-tokens-space-2)',
      paddingRight: 'var(--fx-tokens-space-2)',
      paddingTop: 'var(--fx-tokens-space-2)',
    });
    const meta = model!.components.btn;
    expect(meta.kind).toBe('mapped');
    expect(meta.themeKey).toBe('MuiButton');
    expect(meta.slots.icon.className).toBe('MuiButton-startIcon');
    expect(meta.stateProps).toEqual([
      { state: 'disabled', prop: 'disabled', attribute: 'disabled' },
    ]);
    expect(meta.mapped!.resetCount).toBe(12);
    expect(entry.variants.slice(0, 12).every((v) => 'variant' in v.props)).toBe(
      true,
    );
    expect(entry.variants.slice(12)).toEqual([
      {
        props: {},
        style: { '&:hover': { boxShadow: 'var(--fx-tokens-shadow-focus)' } },
      },
      { props: {}, style: { '&:disabled': { cursor: 'not-allowed' } } },
      { props: { variant: 'loud' }, style: { '&&': { minWidth: '44px' } } },
      { props: {}, style: { '& .MuiButton-startIcon': { width: '20px' } } },
    ]);
    expect(
      muiModelSchema.safeParse(JSON.parse(JSON.stringify(model))).success,
    ).toBe(true);
    // own components are untouched
    expect(model!.themeOptions.components.FxChip.defaultProps).toBeUndefined();
    expect(model!.components.chip.kind).toBe('own');
    expect(model!.components.chip.mapped).toBeNull();
  });

  it.each([
    ['missing catalog', null, 'catalogs/mui.json is missing'],
    [
      'missing framework component',
      { ...FX_CATALOG, frameworkComponents: {} },
      'no entry for Button',
    ],
    [
      'missing component entry',
      { ...FX_CATALOG, components: {} },
      'catalog entry is missing',
    ],
    [
      'stale mapping',
      {
        ...FX_CATALOG,
        components: {
          btn: { ...FX_CATALOG.components.btn, slotMap: { icon: 'endIcon' } },
        },
      },
      'stale (the mapping changed)',
    ],
    [
      'missing permutation',
      {
        ...FX_CATALOG,
        components: {
          btn: {
            ...FX_CATALOG.components.btn,
            renders: FX_CATALOG.components.btn.renders.slice(1),
          },
        },
      },
      'no render for tone=quiet',
    ],
  ])('reports DS-E086 for a %s', (_label, catalog, message) => {
    const { model, diag } = mapped(BTN_FILES, catalog as MuiCatalog | null);
    expect(model).toBeNull();
    expect(diag.errors.map((e) => e.code)).toEqual(['DS-E086']);
    expect(diag.errors[0].message).toContain(message);
  });

  it('routes children through a mapped label slot', () => {
    const files = { ...BTN_FILES };
    const m = JSON.parse(files['src/components/btn/btn.manifest.json']) as {
      slots: Record<string, unknown>;
      targets: { mui: { slotMap: Record<string, string> } };
    };
    m.slots.label = { element: 'span' };
    m.targets.mui.slotMap.label = 'label';
    files['src/components/btn/btn.manifest.json'] = JSON.stringify(m);
    const catalog = structuredClone(FX_CATALOG);
    catalog.components.btn.slotMap = { icon: 'startIcon', label: 'label' };
    const { model, diag } = mapped(files, catalog);
    expect(diag.errors).toEqual([]);
    expect(model!.components.btn.childrenSlot).toBe('label');
    expect(model!.components.btn.mapped!.children).toEqual({
      kind: 'slot',
      slot: 'label',
      muiProp: 'label',
    });
    expect(model!.components.btn.slots.label.className).toBe('MuiButton-label');
  });

  it('rejects a second design-system component mapped onto the same MUI component (DS-E085)', () => {
    const files = { ...BTN_FILES };
    files['src/components/zbtn/zbtn.manifest.json'] = JSON.stringify({
      displayName: 'Zbtn',
      baseline: false,
      name: 'zbtn',
      axes: { tone: { values: ['quiet', 'loud'], default: 'quiet' } },
      states: ['hover', 'disabled'],
      slots: {
        root: { element: 'button' },
        icon: { element: 'span', optional: true },
      },
      targets: {
        tailwind: {},
        mui: {
          component: 'Button',
          axisMap: { tone: 'variant' },
          slotMap: { icon: 'startIcon' },
        },
      },
    });
    files['src/components/zbtn/zbtn.css'] = BTN_FILES[
      'src/components/btn/btn.css'
    ].replaceAll('.fx-btn', '.fx-zbtn');
    const catalog = structuredClone(FX_CATALOG);
    catalog.components.zbtn = structuredClone(FX_CATALOG.components.btn);
    const { model, diag } = mapped(files, catalog);
    expect(model).toBeNull();
    expect(diag.errors.map((e) => e.code)).toEqual(['DS-E085']);
    expect(diag.errors[0].message).toContain(
      'Button is already mapped by "btn"',
    );
  });
});
