import { describe, expect, it } from 'vitest';
import { Diagnostics } from '../src/errors.js';
import { serializeIR } from '../src/ir/serialize.js';
import type { DesignIR } from '../src/ir/types.js';
import { generateMui } from '../src/targets/mui/generate.js';
import { buildMuiModel } from '../src/targets/mui/model.js';
import { renderTsLiteral } from '../src/targets/mui/render-ts.js';
import { twBuild, twContext, twRoot } from './tailwind-fixture.js';

function generated(extra: Record<string, string> = {}) {
  const root = twRoot(extra);
  const { ir, config } = twBuild(root);
  const diag = new Diagnostics();
  const files = generateMui(ir, twContext(root, config), diag);
  const byPath = Object.fromEntries(files.map((f) => [f.path, f.contents]));
  return { files, byPath, diag, ir, ctx: twContext(root, config) };
}

const HEADER =
  /^\/\/ Generated by @bwp-web\/ds-compiler 0\.0\.0-test for target mui from design\.ir\.json \(source hash [0-9a-f]+\)\. Do not edit; run bwp-ds generate\.\n/;

describe('renderTsLiteral', () => {
  it('renders an object literal that evaluates back to the same value', () => {
    const value = {
      'quoted-key': "it's",
      plain: 'back\\slash',
      nested: { list: ['a', { b: '2' }], empty: {}, none: [] },
      n: 3,
      t: true,
    };
    const text = renderTsLiteral(value);
    expect(text.startsWith('{\n  ')).toBe(true);
    expect(text).toContain("'quoted-key': 'it\\'s',");
    expect(text).toContain('plain: ');
    expect(new Function(`return ${text};`)()).toEqual(value);
  });
});

describe('generateMui', () => {
  it('emits the model, the theme, the augmentation, one shell per component, and the indexes, each with a header', () => {
    const { files, byPath, diag } = generated();
    expect(diag.errors).toEqual([]);
    expect(files.map((f) => f.path)).toEqual([
      'theme.model.json',
      'theme.ts',
      'augmentation.ts',
      'components/Chip.tsx',
      'components/Tag.tsx',
      'components/index.ts',
      'index.ts',
      'typecheck.tsx',
    ]);
    for (const path of Object.keys(byPath).filter(
      (p) => p !== 'theme.model.json',
    )) {
      expect(byPath[path], path).toMatch(HEADER);
    }
    const model = JSON.parse(byPath['theme.model.json']) as {
      generated: string;
    };
    expect(Object.keys(model)[0]).toBe('generated');
    expect(
      model.generated.startsWith('Generated by @bwp-web/ds-compiler'),
    ).toBe(true);
    expect(byPath['theme.model.json'].endsWith('\n')).toBe(true);
  });

  it('renders theme.ts from the model so the two are deep-equal', () => {
    const { byPath } = generated();
    const theme = byPath['theme.ts'];
    expect(theme).toContain(
      "import { createTheme, type Theme, type ThemeOptions } from '@mui/material/styles';",
    );
    expect(theme).toContain("import './augmentation.js';");
    expect(theme).toContain('export const fxThemeOptions = {');
    expect(theme).toContain('} satisfies ThemeOptions;');
    expect(theme).toContain(
      'export function createFxTheme(options: ThemeOptions = {}): Theme {',
    );
    expect(theme).toContain('return createTheme(fxThemeOptions, options);');
    const literal = theme.slice(
      theme.indexOf('export const fxThemeOptions = ') +
        'export const fxThemeOptions = '.length,
      theme.indexOf(' satisfies ThemeOptions;'),
    );
    const model = JSON.parse(byPath['theme.model.json']) as {
      themeOptions: unknown;
    };
    expect(new Function(`return ${literal};`)()).toEqual(model.themeOptions);
  });

  it('augments MUI with exact token keys and the component theme entries', () => {
    const { byPath } = generated();
    const aug = byPath['augmentation.ts'];
    expect(aug).toContain(
      "import type { ComponentsOverrides, ComponentsProps, ComponentsVariants } from '@mui/material/styles';",
    );
    expect(aug).toContain(
      "import type { ChipProps } from './components/Chip.js';",
    );
    expect(aug).toContain(
      "type ColorTokenKey = 'neutral-900' | 'text-default';",
    );
    expect(aug).toContain("  fontFamily: Record<'body', string>;");
    expect(aug).toContain("  space: Record<'2', string>;");
    expect(aug).toContain("  fontFamily?: Partial<Record<'body', string>>;");
    expect(aug).toContain("declare module '@mui/material/styles' {");
    expect(aug).toContain(
      '  interface CssThemeVariables {\n    enabled: true;\n  }',
    );
    expect(aug).toContain(
      '  interface Palette {\n    tokens: Record<ColorTokenKey, string>;\n  }',
    );
    expect(aug).toContain(
      '  interface PaletteOptions {\n    tokens?: Partial<Record<ColorTokenKey, string>>;\n  }',
    );
    expect(aug).toContain('  interface Theme {\n    tokens: DsTokens;\n  }');
    expect(aug).toContain(
      '  interface ThemeOptions {\n    tokens?: DsTokenOptions;\n  }',
    );
    expect(aug).toContain(
      '  interface ThemeVars {\n    tokens: DsTokens;\n  }',
    );
    expect(aug).toContain(
      '  interface ComponentsPropsList {\n    FxChip: ChipProps;\n    FxTag: TagProps;\n  }',
    );
    expect(aug).toContain(
      "  interface ComponentNameToClassKey {\n    FxChip: 'root' | 'icon';\n    FxTag: 'root';\n  }",
    );
    expect(aug).toContain('  interface Components<Theme = unknown> {');
    expect(aug).toContain(
      "    FxChip?: {\n      defaultProps?: ComponentsProps['FxChip'];\n      styleOverrides?: ComponentsOverrides<Theme>['FxChip'];\n      variants?: ComponentsVariants<Theme>['FxChip'];\n    };",
    );
    expect(aug).not.toContain('ColorSchemeOverrides');
    expect(aug.trimEnd().endsWith('export {};')).toBe(true);
  });

  it('rejects modes other than light and dark, emitting nothing (DS-E084)', () => {
    const config = {
      name: 'Fictional',
      prefix: 'fx',
      modes: ['day', 'night'],
      defaultMode: 'day',
      targets: {
        tailwind: { outDir: 'out/tailwind' },
        mui: { outDir: 'out/mui' },
      },
      coverageFile: 'out/coverage.md',
    };
    const { files, diag } = generated({
      'ds.config.json': JSON.stringify(config, null, 2),
      'src/tokens/color.css': [
        ':root {',
        '  --fx-color-neutral-900: #111111;',
        '  --fx-color-text-default: var(--fx-color-neutral-900);',
        '}',
        ':root[data-fx-theme="night"] {',
        '  --fx-color-text-default: #ffffff;',
        '}',
        '',
      ].join('\n'),
    });
    expect(files).toEqual([]);
    expect(diag.errors.map((d) => [d.code, d.location?.file])).toEqual([
      ['DS-E084', 'ds.config.json'],
      ['DS-E084', 'ds.config.json'],
    ]);
    expect(diag.errors[0].message).toContain('mode "day"');
    expect(diag.errors[1].message).toContain('mode "night"');
  });

  it('renders a button-rooted shell with exact prop unions, a disabled attribute, and an optional icon slot', () => {
    const { byPath } = generated();
    const chip = byPath['components/Chip.tsx'];
    expect(chip).toContain("import * as React from 'react';");
    expect(chip).toContain(
      "import { styled, useThemeProps } from '@mui/material/styles';",
    );
    expect(chip).toContain("export type ChipTone = 'quiet' | 'loud';");
    expect(chip).toContain(
      'export interface ChipOwnerState {\n  tone: ChipTone;\n}',
    );
    expect(chip).toContain(
      "extends Omit<React.ComponentPropsWithoutRef<'button'>, 'children' | 'disabled' | 'icon' | 'tone'>",
    );
    expect(chip).toContain('  tone?: ChipTone;');
    expect(chip).toContain('  disabled?: boolean;');
    expect(chip).toContain('  children?: React.ReactNode;');
    expect(chip).toContain('  icon?: React.ReactNode;');
    expect(chip).toContain(
      "export const chipClasses = {\n  root: 'FxChip-root',\n  icon: 'FxChip-icon',\n} as const;",
    );
    expect(chip).toContain(
      "const ChipRoot = styled('button', {\n  name: 'FxChip',\n  slot: 'Root',\n  overridesResolver: (_props, styles) => styles.root,\n})<{ ownerState: ChipOwnerState }>({});",
    );
    expect(chip).toContain(
      "export const Chip = React.forwardRef<React.ComponentRef<'button'>, ChipProps>(",
    );
    expect(chip).toContain('function Chip(inProps, ref) {');
    expect(chip).toContain(
      "const props = useThemeProps({ props: inProps, name: 'FxChip' });",
    );
    expect(chip).toContain(
      "const { tone = 'quiet', disabled = false, children, icon, className, ...other } = props;",
    );
    expect(chip).toContain('const ownerState: ChipOwnerState = { tone };');
    expect(chip).toContain('disabled={disabled}');
    expect(chip).not.toContain('aria-disabled');
    // The state attribute is emitted after `{...other}` so the component's
    // own state always wins over whatever the spread forwards.
    expect(chip).toContain(
      [
        '        className={className ? `${chipClasses.root} ${className}` : chipClasses.root}',
        '        {...other}',
        '        disabled={disabled}',
        '      >',
      ].join('\n'),
    );
    expect(chip).toContain('{children}');
    expect(chip).toContain(
      '{icon === undefined ? null : <span className={chipClasses.icon}>{icon}</span>}',
    );
    expect(chip.trimEnd().endsWith(');')).toBe(true);
  });

  it('renders a div-rooted shell with aria-disabled and an empty owner state', () => {
    const { byPath } = generated();
    const tag = byPath['components/Tag.tsx'];
    expect(tag).toContain("const TagRoot = styled('div', {");
    expect(tag).toContain('export type TagOwnerState = Record<never, never>;');
    expect(tag).toContain('aria-disabled={disabled ? true : undefined}');
    expect(tag).not.toContain('disabled={disabled}');
    // The `aria-disabled` attribute name is omitted alongside the `disabled`
    // prop name, even though they differ, so a consumer cannot pass the DOM
    // attribute the component itself sets.
    expect(tag).toContain(
      "extends Omit<React.ComponentPropsWithoutRef<'div'>, 'aria-disabled' | 'children' | 'disabled'>",
    );
    expect(tag).toContain(
      [
        '        className={className ? `${tagClasses.root} ${className}` : tagClasses.root}',
        '        {...other}',
        '        aria-disabled={disabled ? true : undefined}',
        '      >',
      ].join('\n'),
    );
    expect(tag).not.toContain('opacity');
  });

  it('routes children into the label slot and renders the other slots in manifest order', () => {
    const { byPath } = generated({
      'src/components/card/card.manifest.json': JSON.stringify({
        name: 'card',
        displayName: 'Card',
        baseline: false,
        states: ['pressed'],
        slots: {
          root: { element: 'article' },
          media: { element: 'div', optional: true },
          label: { element: 'h3' },
          body: { element: 'p' },
        },
        targets: { tailwind: {}, mui: {} },
      }),
      'src/components/card/card.css': '.fx-card {\n  display: block;\n}\n',
    });
    const card = byPath['components/Card.tsx'];
    expect(card).toContain('aria-pressed={pressed ? true : undefined}');
    expect(card).toContain(
      "extends Omit<React.ComponentPropsWithoutRef<'article'>, 'aria-pressed' | 'body' | 'children' | 'media' | 'pressed'>",
    );
    expect(card).toContain(
      [
        '        className={className ? `${cardClasses.root} ${className}` : cardClasses.root}',
        '        {...other}',
        '        aria-pressed={pressed ? true : undefined}',
        '      >',
      ].join('\n'),
    );
    expect(card).toContain(
      [
        '        {media === undefined ? null : <div className={cardClasses.media}>{media}</div>}',
        '        <h3 className={cardClasses.label}>{children}</h3>',
        '        {body === undefined ? null : <p className={cardClasses.body}>{body}</p>}',
      ].join('\n'),
    );
  });

  it('camelCases kebab-case axis and slot names as props', () => {
    const { byPath } = generated({
      'src/components/menu-item/menu-item.manifest.json': JSON.stringify({
        name: 'menu-item',
        displayName: 'Menu item',
        baseline: false,
        axes: {
          'icon-position': { values: ['start', 'end'], default: 'start' },
        },
        slots: {
          root: { element: 'li' },
          'sub-title': { element: 'span', optional: true },
        },
        targets: { tailwind: {}, mui: {} },
      }),
      'src/components/menu-item/menu-item.css':
        '.fx-menu-item {\n  display: flex;\n}\n.fx-menu-item[data-icon-position="end"] .fx-menu-item__sub-title {\n  display: none;\n}\n',
    });
    const tsx = byPath['components/MenuItem.tsx'];
    expect(tsx).toContain(
      "export type MenuItemIconPosition = 'start' | 'end';",
    );
    expect(tsx).toContain('  iconPosition?: MenuItemIconPosition;');
    expect(tsx).toContain('  subTitle?: React.ReactNode;');
    expect(tsx).toContain("  subTitle: 'FxMenuItem-sub-title',");
    expect(tsx).toContain(
      "const { iconPosition = 'start', children, subTitle, className, ...other } = props;",
    );
    expect(tsx).toContain(
      '{subTitle === undefined ? null : <span className={menuItemClasses.subTitle}>{subTitle}</span>}',
    );
    expect(byPath['theme.ts']).toContain("iconPosition: 'end',");
    expect(byPath['typecheck.tsx']).toContain(
      '<MenuItem iconPosition="end" subTitle="sub-title">',
    );
  });

  it('indexes the components and the theme', () => {
    const { byPath } = generated();
    expect(byPath['components/index.ts']).toContain(
      "export * from './Chip.js';\nexport * from './Tag.js';\n",
    );
    expect(byPath['index.ts']).toContain(
      "import './augmentation.js';\nexport * from './components/index.js';\nexport { createFxTheme, fxThemeOptions } from './theme.js';\n",
    );
  });

  it('emits a type-level probe that accepts the design system values and rejects others', () => {
    const { byPath } = generated();
    const probe = byPath['typecheck.tsx'];
    // No React import: the react-jsx transform needs no React identifier in
    // scope for plain JSX.
    expect(probe).not.toContain("import * as React from 'react';");
    expect(probe).toContain(
      "import { Chip, Tag } from './components/index.js';",
    );
    expect(probe).toContain(
      'export const chipAccepted = (\n  <Chip tone="loud" disabled icon="icon">\n    content\n  </Chip>\n);',
    );
    expect(probe).toContain(
      '// @ts-expect-error tone accepts only the design system values\nexport const chipRejectedTone = <Chip tone="__not_a_value__" />;',
    );
    expect(probe).toContain(
      '// @ts-expect-error unknown props are rejected\nexport const chipRejectedProp = <Chip notAProp="x" />;',
    );
    expect(probe).toContain(
      'export const tagAccepted = (\n  <Tag disabled>\n    content\n  </Tag>\n);',
    );
    expect(probe).not.toContain('tagRejectedTone');
  });

  it('is byte-identical from the in-memory IR and from the serialized IR, preserving axis and slot order', () => {
    // serializeIR alphabetizes every record's keys, including a
    // component's axes and slots; "zeta" and "alpha" (declared in this
    // order) and "tone" and "size" would come out reversed if a generator
    // trusted Object.keys instead of the IR's recorded axisOrder/slotOrder.
    const { files, ir, ctx } = generated({
      'src/components/gizmo/gizmo.manifest.json': JSON.stringify({
        name: 'gizmo',
        displayName: 'Gizmo',
        baseline: false,
        axes: {
          tone: { values: ['a', 'b'], default: 'a' },
          size: { values: ['sm', 'lg'], default: 'sm' },
        },
        slots: {
          root: { element: 'div' },
          zeta: { element: 'span' },
          alpha: { element: 'span' },
        },
        targets: { tailwind: {}, mui: {} },
      }),
      'src/components/gizmo/gizmo.css': '.fx-gizmo {\n  display: block;\n}\n',
    });
    const fromDisk = generateMui(
      JSON.parse(serializeIR(ir)) as DesignIR,
      ctx,
      new Diagnostics(),
    );
    expect(fromDisk).toEqual(files);
    const roundTripped = JSON.parse(serializeIR(ir)) as DesignIR;
    const model1 = buildMuiModel(ir, ctx, new Diagnostics());
    const model2 = buildMuiModel(roundTripped, ctx, new Diagnostics());
    expect(model1!.components.gizmo.childrenSlot).toBe('zeta');
    expect(model2!.components.gizmo.childrenSlot).toBe('zeta');
    expect(JSON.stringify(model1)).toBe(JSON.stringify(model2));
  });

  it('emits nothing and reports when the model cannot be built', () => {
    const { files, diag } = generated({
      'src/tokens/space.css':
        ':root {\n  --fx-space-2: 8px;\n}\n:root[data-fx-theme="dark"] {\n  --fx-space-2: 10px;\n}\n',
    });
    expect(files).toEqual([]);
    expect(diag.errors.map((d) => d.code)).toEqual(['DS-E084']);
  });
});
