import ts from 'typescript';
import { describe, expect, it } from 'vitest';
import { Diagnostics } from '../src/errors.js';
import type { MuiCatalog } from '../src/targets/mui/catalog.js';
import { quoteTs } from '../src/targets/mui/render-ts.js';
import { storiesPlugin } from '../src/targets/stories/index.js';
import { BTN_FILES, FX_CATALOG } from './mui-mapped-fixture.js';
import {
  BLOB_FILES,
  twBuild,
  twConfigWith,
  twContext,
  twRoot,
} from './tailwind-fixture.js';

/** A component whose manifest text is deliberately hostile to naive JSX interpolation (H2). */
const X2_FILES: Record<string, string> = {
  'src/components/x2/x2.manifest.json': JSON.stringify({
    name: 'x2',
    displayName: 'X Two',
    baseline: false,
    slots: {
      root: { element: 'button' },
      icon: { element: 'span', optional: true },
    },
    preview: {
      label: 'It\'s <b> {c} "d"',
      icon: 'a"b\\c',
    },
    targets: { tailwind: {}, mui: {} },
  }),
  'src/components/x2/x2.css': [
    '.fx-x2 {',
    '  display: inline-flex;',
    '}',
    '.fx-x2 .fx-x2__icon {',
    '  width: 20px;',
    '}',
    '',
  ].join('\n'),
};

/** An interface for the internal (undocumented) property TypeScript's parser attaches. */
interface ParsedSourceFile extends ts.SourceFile {
  parseDiagnostics?: readonly ts.Diagnostic[];
}

function generated(
  extra: Record<string, string> = {},
  catalog: MuiCatalog | null = FX_CATALOG,
) {
  const root = twRoot(extra);
  const { ir, config } = twBuild(root);
  const ctx = { ...twContext(root, config), outDir: `${root}/out/stories` };
  const diag = new Diagnostics();
  const files = storiesPlugin.generate(ir, catalog, ctx, diag);
  return {
    files,
    byPath: Object.fromEntries(files.map((f) => [f.path, f.contents])),
    diag,
  };
}

const HEADER =
  /^\/\/ Generated by @bwp-web\/ds-compiler 0\.0\.0-test for target stories from design\.ir\.json \(source hash [0-9a-f]+\)\. Do not edit; run bwp-ds generate\.\n/;

describe('stories plugin', () => {
  it('is auxiliary and registered', () => {
    expect(storiesPlugin.id).toBe('stories');
    expect(storiesPlugin.auxiliary).toBe(true);
    expect(storiesPlugin.coverage({} as never)).toEqual([]);
    expect(
      storiesPlugin.reparse(
        [],
        {} as never,
        null,
        {} as never,
        new Diagnostics(),
      ),
    ).toBeNull();
  });

  it('emits config, one story per component, one per token category, each with a header', () => {
    const { files, byPath, diag } = generated();
    expect(diag.errors).toEqual([]);
    expect(files.map((f) => f.path)).toEqual([
      'config.ts',
      'styles/chip.stories.tsx',
      'styles/pill.stories.tsx',
      'styles/tag.stories.tsx',
      'foundations/color.stories.tsx',
      'foundations/font-family.stories.tsx',
      'foundations/shadow.stories.tsx',
      'foundations/space.stories.tsx',
    ]);
    for (const [path, text] of Object.entries(byPath)) {
      expect(text, path).toMatch(HEADER);
      expect(text.endsWith('\n'), path).toBe(true);
    }
  });

  it('renders config.ts as a typed constant', () => {
    const { byPath } = generated();
    const text = byPath['config.ts'];
    expect(text).toContain("import type { StoriesConfig } from '../harness';");
    expect(text).toContain('export const storiesConfig: StoriesConfig = {');
    expect(text).toContain("  prefix: 'fx',");
    expect(text).toContain(
      "  mode: {\n    kind: 'attribute',\n    name: 'data-fx-theme',\n  },",
    );
    expect(text).toContain("    'background-color',");
    expect(text).toContain("  muiThemeFactory: 'createFxTheme',");
  });

  it('renders an own-component story with a CompareSpec, the MUI render function, and parityPlay', () => {
    const { byPath } = generated();
    const text = byPath['styles/chip.stories.tsx'];
    expect(text).toContain(
      "import type { Meta, StoryObj } from '@storybook/react-vite';",
    );
    expect(text).toContain(
      "import { Chip, createFxTheme } from '@fx/styles-mui';",
    );
    expect(text).toContain(
      "import { CompareGrid, parityPlay, type CompareRow, type CompareSpec } from '../../harness';",
    );
    expect(text).toContain("import { storiesConfig } from '../config';");
    expect(text).toContain("  title: 'Styles/Chip',");
    expect(text).toContain("  name: 'chip',");
    expect(text).toContain("  rootElement: 'button',");
    expect(text).toContain("    { name: 'hover', kind: 'hover' },");
    expect(text).toContain(
      "    { name: 'disabled', kind: 'attribute', attributes: { disabled: '' }, muiProp: 'disabled' },",
    );
    expect(text).toContain(
      "  slots: [{ name: 'icon', element: 'span', content: 'icon' }],",
    );
    expect(text).toContain("  label: 'Chip',");
    expect(text).toContain('  labelSlot: null,');
    expect(text).toContain("  labelElement: 'span',");
    expect(text).toContain('  tailwind: true,');
    expect(text).toContain("    rootClass: 'FxChip-root',");
    expect(text).toContain("    slotClasses: { icon: 'FxChip-icon' },");
    expect(text).toContain('    theme: createFxTheme(),');
    // Slot content and the label are rendered as JSX expression containers
    // holding a `quoteTs`-escaped string literal, not as a raw JSX
    // attribute string or text node, so manifest text containing `"` or `\`
    // can never produce invalid or mismeaning JSX (see H2).
    expect(text).toContain(
      [
        '    render: (row: CompareRow) => (',
        "      <Chip tone={row.axes.tone as 'quiet' | 'loud'} disabled={row.state === 'disabled'} icon={'icon'}>",
        "        {'Chip'}",
        '      </Chip>',
        '    ),',
      ].join('\n'),
    );
    expect(text).toContain('export const Compare: StoryObj = {');
    expect(text).toContain(
      '  render: (_args, context) => <CompareGrid spec={spec} config={storiesConfig} targets={context.globals.dsTargets} />,',
    );
    expect(text).toContain(
      '  play: (context) => parityPlay(context, spec, storiesConfig),',
    );
  });

  it('renders a mapped component with MUI props and a CSS-only component without a mui cell', () => {
    const { byPath } = generated(BTN_FILES);
    const btn = byPath['styles/btn.stories.tsx'];
    expect(btn).toContain(
      "import { Btn, createFxTheme } from '@fx/styles-mui';",
    );
    expect(btn).toContain("    rootClass: 'MuiButton-root',");
    expect(btn).toContain("    slotClasses: { icon: 'MuiButton-startIcon' },");
    expect(btn).toContain(
      "      <Btn tone={row.axes.tone as 'quiet' | 'loud'} disabled={row.state === 'disabled'} icon={'icon'}>",
    );
    const pill = byPath['styles/pill.stories.tsx'];
    expect(pill).not.toContain('@fx/styles-mui');
    expect(pill).toContain('  tailwind: false,');
    expect(pill).toContain('  mui: null,');
    expect(pill).toContain(
      "import { CompareGrid, parityPlay, type CompareSpec } from '../../harness';",
    );
  });

  it('renders a foundations story with the token list and tokenParityPlay', () => {
    const { byPath } = generated();
    const text = byPath['foundations/color.stories.tsx'];
    expect(text).toContain(
      "import { TokenGrid, tokenParityPlay, type TokenSpec } from '../../harness';",
    );
    expect(text).toContain("  title: 'Foundations/Color',");
    expect(text).toContain('export const tokens: TokenSpec[] = [');
    // The file exports its token data as well as the story, and CSF would
    // otherwise treat that data as a second, unrenderable story.
    expect(text).toContain("  includeStories: ['Compare'],");
    // `renderTsLiteral` (shared with the MUI target) always breaks a
    // non-empty array across lines, so `path` is multi-line here too; the
    // plan's inline `['text', 'default']` literal does not match what the
    // shared renderer legitimately produces.
    expect(text).toContain(
      [
        '  {',
        "    id: 'color.text.default',",
        '    path: [',
        "      'text',",
        "      'default',",
        '    ],',
        "    cssVar: '--fx-color-text-default',",
        "    tailwindVar: '--color-fx-text-default',",
        "    muiVar: '--fx-palette-tokens-text-default',",
        '    modeInvariant: false,',
        '  },',
      ].join('\n'),
    );
    expect(text).toContain(
      '  render: () => <TokenGrid category="color" tokens={tokens} config={storiesConfig} />,',
    );
    expect(text).toContain(
      "  play: (context) => tokenParityPlay(context, tokens, 'color', storiesConfig),",
    );
    expect(byPath['foundations/font-family.stories.tsx']).toContain(
      "  title: 'Foundations/Font Family',",
    );
  });

  it('is deterministic and independent of catalog key order', () => {
    const a = generated();
    // Reverse key order at every level that is a plain object, not only the
    // top level: `frameworkComponents.Button.props`, `.classes`, and
    // `components` itself.
    const button = FX_CATALOG.frameworkComponents.Button;
    const reversedButton = {
      ...button,
      classes: Object.fromEntries(Object.entries(button.classes).reverse()),
      props: Object.fromEntries(Object.entries(button.props).reverse()),
    };
    const reversedFrameworkComponents = Object.fromEntries(
      Object.entries({
        ...FX_CATALOG.frameworkComponents,
        Button: reversedButton,
      }).reverse(),
    );
    const reversedComponents = Object.fromEntries(
      Object.entries(FX_CATALOG.components).reverse(),
    );
    const reversed = Object.fromEntries(
      Object.entries({
        ...FX_CATALOG,
        frameworkComponents: reversedFrameworkComponents,
        components: reversedComponents,
      }).reverse(),
    ) as unknown as typeof FX_CATALOG;
    const b = generated({}, reversed);
    expect(a.files).toEqual(b.files);
  });

  it('reports the MUI side once and emits nothing when the MUI model cannot be built', () => {
    // Overriding just the config's modes (keeping TW_FILES' color.css, which
    // has a `dark`-mode block) would fail at the lint step (DS-E010: the
    // block matches no configured mode selector) before buildMuiModel ever
    // runs. Renaming the mode-varying block to match keeps the fixture
    // lint-clean so the failure is exactly the one this test targets: MUI
    // rejecting a non-light/dark mode.
    const { files, diag } = generated(
      {
        'ds.config.json': twConfigWith({
          modes: ['light', 'sepia'],
          defaultMode: 'light',
        }),
        'src/tokens/color.css': [
          ':root {',
          '  --fx-color-neutral-900: #111111;',
          '  --fx-color-text-default: var(--fx-color-neutral-900);',
          '}',
          ':root[data-fx-theme="sepia"] {',
          '  --fx-color-text-default: #ffffff;',
          '}',
          '',
        ].join('\n'),
      },
      null,
    );
    expect(files).toEqual([]);
    expect(diag.errors.map((e) => e.code)).toEqual(['DS-E084']);
    expect(diag.errors[0].message).toContain(
      'stories: the mui model could not be built',
    );
  });

  it('generates a story for a component with a data-state state without crashing (H1)', () => {
    const { byPath, diag } = generated(BLOB_FILES);
    expect(diag.errors).toEqual([]);
    const text = byPath['styles/blob.stories.tsx'];
    expect(text).toContain(
      "    { name: 'loading', kind: 'attribute', attributes: { 'data-state': 'loading' }, muiProp: 'loading' },",
    );
    expect(text).toContain('  mui: null,');
  });

  it('escapes hostile manifest text as quoted string literals inside JSX expression containers, never as raw JSX attributes or text (H2)', () => {
    const { byPath } = generated(X2_FILES);
    const text = byPath['styles/x2.stories.tsx'];
    expect(text).toContain(`icon={${quoteTs('a"b\\c')}}`);
    expect(text).toContain(`{${quoteTs('It\'s <b> {c} "d"')}}`);
    // never the naive, unescaped forms this bug used to produce
    expect(text).not.toContain('icon="a"b\\c"');
    expect(text).not.toContain('It\'s <b> {c} "d"\n');
  });

  it('T1: every generated .ts/.tsx file parses as syntactically valid TypeScript, even with hostile manifest text', () => {
    const { byPath, diag } = generated(X2_FILES);
    expect(diag.errors).toEqual([]);
    for (const [path, text] of Object.entries(byPath)) {
      const scriptKind = path.endsWith('.tsx')
        ? ts.ScriptKind.TSX
        : ts.ScriptKind.TS;
      const source = ts.createSourceFile(
        path,
        text,
        ts.ScriptTarget.Latest,
        true,
        scriptKind,
      ) as ParsedSourceFile;
      expect(source.parseDiagnostics ?? [], path).toEqual([]);
    }
  });

  it('titles a story from the component name, not the free-form displayName, so components sharing a displayName do not collide (M1)', () => {
    const { byPath } = generated();
    // `tag` and `pill` both have displayName "X" in the fixture.
    expect(byPath['styles/tag.stories.tsx']).toContain(
      "  title: 'Styles/Tag',",
    );
    expect(byPath['styles/pill.stories.tsx']).toContain(
      "  title: 'Styles/Pill',",
    );
  });

  it('renders an empty states array inline (L6)', () => {
    const { byPath } = generated();
    // `pill` declares no states.
    expect(byPath['styles/pill.stories.tsx']).toContain('  states: [],');
  });
});
