import type { Meta, StoryObj } from '@storybook/react-vite';
import { Box, Stack, Typography, Tooltip, Divider } from '@mui/material';
import {
  AccessibleIcon,
  AddIcon,
  AddPhotoIcon,
  AddScreenTvIcon,
  AdjustableDeskIcon,
  AppleIcon,
  AppsIcon,
  AppsIconFilled,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowsMaximizeIcon,
  ArrowsMinimizeIcon,
  ArrowsMoveIcon,
  ArrowUpIcon,
  ArrowUpRightIcon,
  AudioFileIcon,
  AudioLibraryIcon,
  AudioPolarityInversionIcon,
  AutoFitFilledIcon,
  AutoFitIcon,
  BadgeClockIcon,
  BadgeLiveIcon,
  BadgeSpeakIcon,
  BiampLaunchIcon,
  BiampLogoIcon,
  BikeIcon,
  BlankIcon,
  BlockIcon,
  BookmarkIcon,
  BuildingIcon,
  CalendarAddIcon,
  CalendarIcon,
  CameraIcon,
  CeilingIcon,
  CheckedIcon,
  ChevronDownIcon,
  ChevronFullLeftIcon,
  ChevronFullRightIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleCheckIcon,
  CircleFilledIcon,
  CircleHalfIcon,
  CircleIcon,
  CircleStopIcon,
  ClipboardListIcon,
  ClockIcon,
  ClockTimeIcon,
  CloseIcon,
  CloudIcon,
  CloudNoConnectionIcon,
  CloudUploadIcon,
  CodeIcon,
  CollapseTreeviewIcon,
  ColumnsIcon,
  CommandFileIcon,
  ComputerIcon,
  ConditionerIcon,
  ContrastIcon,
  ControlPanelIcon,
  CopyIcon,
  CursorIcon,
  DefineIcon,
  DeleteIcon,
  DesignFileIcon,
  DeskAltIcon,
  DeskIcon,
  DeskSolidIcon,
  DeviceSpeakerIcon,
  DisplayIcon,
  DistanceIcon,
  DoorRoomIcon,
  DownloadIcon,
  DragIcon,
  DropdownChevronDownIcon,
  DropdownChevronDuoIcon,
  DropdownChevronUpIcon,
  DualMonitorFilledIcon,
  EarIcon,
  EditIcon,
  ElectricVehicleChargingIcon,
  EmailIcon,
  EqualizerIcon,
  ErrorCircleIcon,
  ErrorStatusIcon,
  ExportIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  FavoriteIcon,
  FileDesignIcon,
  FileIcon,
  FileReportIcon,
  FileTypeLogIcon,
  FileTypePdfIcon,
  FilterIcon,
  FirmwareUpdateIcon,
  FloorPlanIcon,
  FocusModeIcon,
  FolderOpenIcon,
  FollowScreenFilledIcon,
  FollowScreenIcon,
  ForgotPasswordIcon,
  FurnitureIcon,
  GhostDeskIcon,
  GlobeIcon,
  GroupIcon,
  IndeterminateIcon,
  InfoCircleIcon,
  InfoStatusIcon,
  InvertIcon,
  KeyArrowDownIcon,
  KeyArrowUpIcon,
  LayoutSidebarCollapseIcon,
  LayoutSidebarRightCollapseIcon,
  LicencesIcon,
  LightsIcon,
  LinkIcon,
  LinkOffIcon,
  ListIcon,
  LoaderIcon,
  LockerIcon,
  LockIcon,
  LockOpenIcon,
  LoginIcon,
  LogoutIcon,
  MapSiteIcon,
  MapZoomIcon,
  MaximizeIcon,
  MicIcon,
  MicrophoneIcon,
  MicrophoneOffIcon,
  MinimizeIcon,
  MinusIcon,
  MobildFilterIcon,
  MonitorFilledIcon,
  MoreIcon,
  MotorcycleFilledIcon,
  MsTeamsIcon,
  MusicNoteIcon,
  NetworkIcon,
  NoCardIcon,
  NoiseCancellingPanelsQuietZoneIcon,
  NoResultsIcon,
  OtherIcon,
  ParkingAltIcon,
  ParkingIcon,
  PauseIcon,
  PersonIcon,
  PhoneIcon,
  PhotoIcon,
  PinFilledIcon,
  PinLocationIcon,
  PinOutlinedIcon,
  PlayAnnouncementIcon,
  PlaybackSpeedIcon,
  PowerOutletFilledIcon,
  PrivateIcon,
  ProjectorIcon,
  QrIcon,
  QuestionmarkIcon,
  QueueAnnouncementIcon,
  RadioCheckedIcon,
  RadioUncheckedIcon,
  ReceptionIcon,
  RefreshIcon,
  RepeatIcon,
  RestroomIcon,
  RocketLaunchIcon,
  RoomHubIcon,
  RoomIcon,
  RoomSolidIcon,
  RoomTempIcon,
  RotateIcon,
  RulerIcon,
  SaveIcon,
  SearchIcon,
  SelectIcon,
  SendIcon,
  ServiceNotReachableIcon,
  SettingsIcon,
  ShareIcon,
  SoundIcon,
  SourceIcon,
  SpeakerFilledIcon,
  SpeakerIcon,
  SpeakerMinimumVolumeFilledIcon,
  SpeakerOffFilledIcon,
  SpeakerOffIcon,
  SquareRoundedArrowRightFilledIcon,
  SquareRoundedArrowRightIcon,
  SquareRoundedPlusIcon,
  StarIcon,
  StopIcon,
  SuccessStatusIcon,
  SupportIcon,
  TeamMeetingIcon,
  TouchDisplayIcon,
  UncheckedIcon,
  UploadIcon,
  UsersIcon,
  UsersPlusSigninIcon,
  VideoCameraIcon,
  VideoConferenceIcon,
  VideoIcon,
  VideoProcessorFilledIcon,
  VideoProcessorIcon,
  WarningStatusIcon,
  WarningTriangleIcon,
  WeatherProtectionFilledIcon,
  WhiteboardIcon,
  WifiEnlargedIcon,
  WifiIcon,
  WirelessChargingFilledIcon,
  WorkshopIcon,
  ZoneIcon,
} from '@bwp-web/assets';

/* ── helpers ── */

const IconCell = ({
  name,
  children,
}: {
  name: string;
  children: React.ReactNode;
}) => (
  <Tooltip title={name} placement="top">
    <Stack
      alignItems="center"
      spacing={0.5}
      sx={{
        width: 100,
        p: 1,
        borderRadius: 1,
        '&:hover': { bgcolor: 'action.hover' },
      }}
    >
      <Box sx={{ fontSize: 28, display: 'flex' }}>{children}</Box>
      <Typography
        variant="caption"
        noWrap
        sx={{ maxWidth: 90, fontSize: 9, textAlign: 'center' }}
      >
        {name}
      </Typography>
    </Stack>
  </Tooltip>
);

type IconEntry = [string, React.ReactNode];

const IconGroup = ({ title, icons }: { title: string; icons: IconEntry[] }) => (
  <Box>
    <Typography variant="h6" sx={{ mb: 1 }}>
      {title} ({icons.length})
    </Typography>
    <Stack direction="row" flexWrap="wrap" gap={0.5}>
      {icons.map(([name, node]) => (
        <IconCell key={name} name={name}>
          {node}
        </IconCell>
      ))}
    </Stack>
    <Divider sx={{ mt: 3 }} />
  </Box>
);

/* ── icon lists per size group ──
   Single-size icons appear once in their group.
   Multisize icons appear in EVERY group they support, rendered with that variant. */

const xxxxsIcons: IconEntry[] = [
  // single-size
  ['BadgeLiveIcon', <BadgeLiveIcon />],
  // multisize
  ['BadgeClockIcon', <BadgeClockIcon variant="xxxxs" />],
  ['BadgeSpeakIcon', <BadgeSpeakIcon variant="xxxxs" />],
];

const xxxsIcons: IconEntry[] = [
  // multisize only
  ['BadgeClockIcon', <BadgeClockIcon variant="xxxs" />],
  ['BadgeSpeakIcon', <BadgeSpeakIcon variant="xxxs" />],
];

const xxsIcons: IconEntry[] = [
  // single-size
  ['BookmarkIcon', <BookmarkIcon />],
  ['CameraIcon', <CameraIcon />],
  ['ClockIcon', <ClockIcon />],
  ['ControlPanelIcon', <ControlPanelIcon />],
  ['DisplayIcon', <DisplayIcon />],
  ['DropdownChevronDownIcon', <DropdownChevronDownIcon />],
  ['DropdownChevronDuoIcon', <DropdownChevronDuoIcon />],
  ['DropdownChevronUpIcon', <DropdownChevronUpIcon />],
  ['LockerIcon', <LockerIcon />],
  ['MicIcon', <MicIcon />],
  ['NetworkIcon', <NetworkIcon />],
  ['OtherIcon', <OtherIcon />],
  ['PrivateIcon', <PrivateIcon />],
  ['RepeatIcon', <RepeatIcon />],
  ['RoomTempIcon', <RoomTempIcon />],
  ['StarIcon', <StarIcon />],
  // multisize
  ['AccessibleIcon', <AccessibleIcon variant="xxs" />],
  ['AdjustableDeskIcon', <AdjustableDeskIcon variant="xxs" />],
  ['ArrowDownIcon', <ArrowDownIcon variant="xxs" />],
  ['BikeIcon', <BikeIcon variant="xxs" />],
  ['BlankIcon', <BlankIcon variant="xxs" />],
  ['CloseIcon', <CloseIcon variant="xxs" />],
  ['DeleteIcon', <DeleteIcon variant="xxs" />],
  ['DeskIcon', <DeskIcon variant="xxs" />],
  ['DualMonitorFilledIcon', <DualMonitorFilledIcon variant="xxs" />],
  ['EarIcon', <EarIcon variant="xxs" />],
  [
    'ElectricVehicleChargingIcon',
    <ElectricVehicleChargingIcon variant="xxs" />,
  ],
  ['FurnitureIcon', <FurnitureIcon variant="xxs" />],
  ['LightsIcon', <LightsIcon variant="xxs" />],
  ['LinkIcon', <LinkIcon variant="xxs" />],
  ['MonitorFilledIcon', <MonitorFilledIcon variant="xxs" />],
  ['MotorcycleFilledIcon', <MotorcycleFilledIcon variant="xxs" />],
  ['ParkingIcon', <ParkingIcon variant="xxs" />],
  ['PersonIcon', <PersonIcon variant="xxs" />],
  ['PhoneIcon', <PhoneIcon variant="xxs" />],
  ['PinLocationIcon', <PinLocationIcon variant="xxs" />],
  ['PowerOutletFilledIcon', <PowerOutletFilledIcon variant="xxs" />],
  ['ProjectorIcon', <ProjectorIcon variant="xxs" />],
  ['RoomIcon', <RoomIcon variant="xxs" />],
  ['SpeakerIcon', <SpeakerIcon variant="xxs" />],
  [
    'WeatherProtectionFilledIcon',
    <WeatherProtectionFilledIcon variant="xxs" />,
  ],
  ['WhiteboardIcon', <WhiteboardIcon variant="xxs" />],
  ['WirelessChargingFilledIcon', <WirelessChargingFilledIcon variant="xxs" />],
];

const xsIcons: IconEntry[] = [
  // single-size
  ['AddScreenTvIcon', <AddScreenTvIcon />],
  ['ArrowsMinimizeIcon', <ArrowsMinimizeIcon />],
  ['AudioFileIcon', <AudioFileIcon />],
  ['BlockIcon', <BlockIcon />],
  ['CeilingIcon', <CeilingIcon />],
  ['CheckedIcon', <CheckedIcon />],
  ['ChevronFullLeftIcon', <ChevronFullLeftIcon />],
  ['ChevronFullRightIcon', <ChevronFullRightIcon />],
  ['CircleFilledIcon', <CircleFilledIcon />],
  ['CircleHalfIcon', <CircleHalfIcon />],
  ['CircleIcon', <CircleIcon />],
  ['ClipboardListIcon', <ClipboardListIcon />],
  ['CloudUploadIcon', <CloudUploadIcon />],
  ['CodeIcon', <CodeIcon />],
  ['CollapseTreeviewIcon', <CollapseTreeviewIcon />],
  ['CommandFileIcon', <CommandFileIcon />],
  ['DesignFileIcon', <DesignFileIcon />],
  ['DeviceSpeakerIcon', <DeviceSpeakerIcon />],
  ['DistanceIcon', <DistanceIcon />],
  ['DragIcon', <DragIcon />],
  ['EqualizerIcon', <EqualizerIcon />],
  ['FavoriteIcon', <FavoriteIcon />],
  ['FileIcon', <FileIcon />],
  ['FolderOpenIcon', <FolderOpenIcon />],
  ['GhostDeskIcon', <GhostDeskIcon />],
  ['GroupIcon', <GroupIcon />],
  ['IndeterminateIcon', <IndeterminateIcon />],
  ['LayoutSidebarCollapseIcon', <LayoutSidebarCollapseIcon />],
  ['LoaderIcon', <LoaderIcon />],
  ['LockOpenIcon', <LockOpenIcon />],
  ['MusicNoteIcon', <MusicNoteIcon />],
  ['PinFilledIcon', <PinFilledIcon />],
  ['PinOutlinedIcon', <PinOutlinedIcon />],
  ['RotateIcon', <RotateIcon />],
  ['RulerIcon', <RulerIcon />],
  ['SelectIcon', <SelectIcon />],
  ['SendIcon', <SendIcon />],
  ['SoundIcon', <SoundIcon />],
  ['SupportIcon', <SupportIcon />],
  ['UncheckedIcon', <UncheckedIcon />],
  ['UsersIcon', <UsersIcon />],
  ['VideoCameraIcon', <VideoCameraIcon />],
  ['VideoProcessorFilledIcon', <VideoProcessorFilledIcon />],
  ['VideoProcessorIcon', <VideoProcessorIcon />],
  ['ZoneIcon', <ZoneIcon />],
  // multisize
  ['AccessibleIcon', <AccessibleIcon variant="xs" />],
  ['AddIcon', <AddIcon variant="xs" />],
  ['AdjustableDeskIcon', <AdjustableDeskIcon variant="xs" />],
  ['ArrowLeftIcon', <ArrowLeftIcon variant="xs" />],
  ['ArrowsMaximizeIcon', <ArrowsMaximizeIcon variant="xs" />],
  ['ArrowsMoveIcon', <ArrowsMoveIcon variant="xs" />],
  ['ArrowUpRightIcon', <ArrowUpRightIcon variant="xs" />],
  ['AudioLibraryIcon', <AudioLibraryIcon variant="xs" />],
  ['AudioPolarityInversionIcon', <AudioPolarityInversionIcon variant="xs" />],
  ['BikeIcon', <BikeIcon variant="xs" />],
  ['BlankIcon', <BlankIcon variant="xs" />],
  ['BuildingIcon', <BuildingIcon variant="xs" />],
  ['CalendarIcon', <CalendarIcon variant="xs" />],
  ['ChevronDownIcon', <ChevronDownIcon variant="xs" />],
  ['ChevronLeftIcon', <ChevronLeftIcon variant="xs" />],
  ['ChevronRightIcon', <ChevronRightIcon variant="xs" />],
  ['ChevronUpIcon', <ChevronUpIcon variant="xs" />],
  ['CircleCheckIcon', <CircleCheckIcon variant="xs" />],
  ['ClockTimeIcon', <ClockTimeIcon variant="xs" />],
  ['CloseIcon', <CloseIcon variant="xs" />],
  ['CloudIcon', <CloudIcon variant="xs" />],
  ['CloudNoConnectionIcon', <CloudNoConnectionIcon variant="xs" />],
  ['ColumnsIcon', <ColumnsIcon variant="xs" />],
  ['CopyIcon', <CopyIcon variant="xs" />],
  ['DeleteIcon', <DeleteIcon variant="xs" />],
  ['DeskIcon', <DeskIcon variant="xs" />],
  ['DoorRoomIcon', <DoorRoomIcon variant="xs" />],
  ['DownloadIcon', <DownloadIcon variant="xs" />],
  ['DualMonitorFilledIcon', <DualMonitorFilledIcon variant="xs" />],
  ['EarIcon', <EarIcon variant="xs" />],
  ['EditIcon', <EditIcon variant="xs" />],
  ['ElectricVehicleChargingIcon', <ElectricVehicleChargingIcon variant="xs" />],
  ['EmailIcon', <EmailIcon variant="xs" />],
  ['ErrorCircleIcon', <ErrorCircleIcon variant="xs" />],
  ['ExportIcon', <ExportIcon variant="xs" />],
  ['ExternalLinkIcon', <ExternalLinkIcon variant="xs" />],
  ['EyeIcon', <EyeIcon variant="xs" />],
  ['EyeOffIcon', <EyeOffIcon variant="xs" />],
  ['FileReportIcon', <FileReportIcon variant="xs" />],
  ['FileTypeLogIcon', <FileTypeLogIcon variant="xs" />],
  ['FilterIcon', <FilterIcon variant="xs" />],
  ['FirmwareUpdateIcon', <FirmwareUpdateIcon variant="xs" />],
  ['FloorPlanIcon', <FloorPlanIcon variant="xs" />],
  ['FurnitureIcon', <FurnitureIcon variant="xs" />],
  ['InfoCircleIcon', <InfoCircleIcon variant="xs" />],
  ['LicencesIcon', <LicencesIcon variant="xs" />],
  ['LinkIcon', <LinkIcon variant="xs" />],
  ['LinkOffIcon', <LinkOffIcon variant="xs" />],
  ['ListIcon', <ListIcon variant="xs" />],
  ['LockIcon', <LockIcon variant="xs" />],
  ['LoginIcon', <LoginIcon variant="xs" />],
  ['LogoutIcon', <LogoutIcon variant="xs" />],
  ['MapSiteIcon', <MapSiteIcon variant="xs" />],
  ['MapZoomIcon', <MapZoomIcon variant="xs" />],
  ['MicrophoneIcon', <MicrophoneIcon variant="xs" />],
  ['MinusIcon', <MinusIcon variant="xs" />],
  ['MonitorFilledIcon', <MonitorFilledIcon variant="xs" />],
  ['MotorcycleFilledIcon', <MotorcycleFilledIcon variant="xs" />],
  [
    'NoiseCancellingPanelsQuietZoneIcon',
    <NoiseCancellingPanelsQuietZoneIcon variant="xs" />,
  ],
  ['ParkingAltIcon', <ParkingAltIcon variant="xs" />],
  ['ParkingIcon', <ParkingIcon variant="xs" />],
  ['PauseIcon', <PauseIcon variant="xs" />],
  ['PersonIcon', <PersonIcon variant="xs" />],
  ['PhotoIcon', <PhotoIcon variant="xs" />],
  ['PinLocationIcon', <PinLocationIcon variant="xs" />],
  ['PlaybackSpeedIcon', <PlaybackSpeedIcon variant="xs" />],
  ['PowerOutletFilledIcon', <PowerOutletFilledIcon variant="xs" />],
  ['RefreshIcon', <RefreshIcon variant="xs" />],
  ['RocketLaunchIcon', <RocketLaunchIcon variant="xs" />],
  ['SearchIcon', <SearchIcon variant="xs" />],
  ['SettingsIcon', <SettingsIcon variant="xs" />],
  ['ShareIcon', <ShareIcon variant="xs" />],
  ['SourceIcon', <SourceIcon variant="xs" />],
  ['SpeakerFilledIcon', <SpeakerFilledIcon variant="xs" />],
  [
    'SpeakerMinimumVolumeFilledIcon',
    <SpeakerMinimumVolumeFilledIcon variant="xs" />,
  ],
  ['SpeakerOffFilledIcon', <SpeakerOffFilledIcon variant="xs" />],
  ['SquareRoundedPlusIcon', <SquareRoundedPlusIcon variant="xs" />],
  ['StopIcon', <StopIcon variant="xs" />],
  ['UploadIcon', <UploadIcon variant="xs" />],
  ['UsersPlusSigninIcon', <UsersPlusSigninIcon variant="xs" />],
  ['WarningTriangleIcon', <WarningTriangleIcon variant="xs" />],
  ['WeatherProtectionFilledIcon', <WeatherProtectionFilledIcon variant="xs" />],
  ['WirelessChargingFilledIcon', <WirelessChargingFilledIcon variant="xs" />],
];

const smIcons: IconEntry[] = [
  // single-size
  ['AppleIcon', <AppleIcon />],
  ['DeskAltIcon', <DeskAltIcon />],
  ['ForgotPasswordIcon', <ForgotPasswordIcon />],
  ['ReceptionIcon', <ReceptionIcon />],
  ['RestroomIcon', <RestroomIcon />],
  // multisize
  ['AccessibleIcon', <AccessibleIcon variant="sm" />],
  ['AdjustableDeskIcon', <AdjustableDeskIcon variant="sm" />],
  ['BikeIcon', <BikeIcon variant="sm" />],
  ['CircleCheckIcon', <CircleCheckIcon variant="sm" />],
  ['DeskIcon', <DeskIcon variant="sm" />],
  ['DualMonitorFilledIcon', <DualMonitorFilledIcon variant="sm" />],
  ['ElectricVehicleChargingIcon', <ElectricVehicleChargingIcon variant="sm" />],
  ['EmailIcon', <EmailIcon variant="sm" />],
  ['ErrorCircleIcon', <ErrorCircleIcon variant="sm" />],
  ['InfoCircleIcon', <InfoCircleIcon variant="sm" />],
  ['MonitorFilledIcon', <MonitorFilledIcon variant="sm" />],
  ['MotorcycleFilledIcon', <MotorcycleFilledIcon variant="sm" />],
  ['MsTeamsIcon', <MsTeamsIcon variant="sm" />],
  [
    'NoiseCancellingPanelsQuietZoneIcon',
    <NoiseCancellingPanelsQuietZoneIcon variant="sm" />,
  ],
  ['ParkingIcon', <ParkingIcon variant="sm" />],
  ['PhoneIcon', <PhoneIcon variant="sm" />],
  ['PhotoIcon', <PhotoIcon variant="sm" />],
  ['PowerOutletFilledIcon', <PowerOutletFilledIcon variant="sm" />],
  ['RoomIcon', <RoomIcon variant="sm" />],
  ['WarningTriangleIcon', <WarningTriangleIcon variant="sm" />],
  ['WeatherProtectionFilledIcon', <WeatherProtectionFilledIcon variant="sm" />],
  ['WirelessChargingFilledIcon', <WirelessChargingFilledIcon variant="sm" />],
];

const mdIcons: IconEntry[] = [
  // single-size
  ['AddPhotoIcon', <AddPhotoIcon />],
  ['AppsIcon', <AppsIcon />],
  ['AppsIconFilled', <AppsIconFilled />],
  ['AutoFitFilledIcon', <AutoFitFilledIcon />],
  ['AutoFitIcon', <AutoFitIcon />],
  ['CalendarAddIcon', <CalendarAddIcon />],
  ['CircleStopIcon', <CircleStopIcon />],
  ['ContrastIcon', <ContrastIcon />],
  ['CursorIcon', <CursorIcon />],
  ['DefineIcon', <DefineIcon />],
  ['DeskSolidIcon', <DeskSolidIcon />],
  ['FileTypePdfIcon', <FileTypePdfIcon />],
  ['FollowScreenFilledIcon', <FollowScreenFilledIcon />],
  ['FollowScreenIcon', <FollowScreenIcon />],
  ['InvertIcon', <InvertIcon />],
  ['LayoutSidebarRightCollapseIcon', <LayoutSidebarRightCollapseIcon />],
  ['MaximizeIcon', <MaximizeIcon />],
  ['MicrophoneOffIcon', <MicrophoneOffIcon />],
  ['MinimizeIcon', <MinimizeIcon />],
  ['MobildFilterIcon', <MobildFilterIcon />],
  ['MoreIcon', <MoreIcon />],
  ['PlayAnnouncementIcon', <PlayAnnouncementIcon />],
  ['QrIcon', <QrIcon />],
  ['QuestionmarkIcon', <QuestionmarkIcon />],
  ['QueueAnnouncementIcon', <QueueAnnouncementIcon />],
  ['RoomSolidIcon', <RoomSolidIcon />],
  ['SaveIcon', <SaveIcon />],
  ['SpeakerOffIcon', <SpeakerOffIcon />],
  ['SquareRoundedArrowRightFilledIcon', <SquareRoundedArrowRightFilledIcon />],
  ['SquareRoundedArrowRightIcon', <SquareRoundedArrowRightIcon />],
  ['VideoIcon', <VideoIcon />],
  // multisize
  ['AddIcon', <AddIcon variant="md" />],
  ['ArrowDownIcon', <ArrowDownIcon variant="md" />],
  ['ArrowLeftIcon', <ArrowLeftIcon variant="md" />],
  ['ArrowRightIcon', <ArrowRightIcon variant="md" />],
  ['ArrowsMaximizeIcon', <ArrowsMaximizeIcon variant="md" />],
  ['ArrowsMoveIcon', <ArrowsMoveIcon variant="md" />],
  ['ArrowUpIcon', <ArrowUpIcon variant="md" />],
  ['AudioLibraryIcon', <AudioLibraryIcon variant="md" />],
  ['AudioPolarityInversionIcon', <AudioPolarityInversionIcon variant="md" />],
  ['BlankIcon', <BlankIcon variant="md" />],
  ['BuildingIcon', <BuildingIcon variant="md" />],
  ['CalendarIcon', <CalendarIcon variant="md" />],
  ['ChevronDownIcon', <ChevronDownIcon variant="md" />],
  ['ChevronLeftIcon', <ChevronLeftIcon variant="md" />],
  ['ChevronRightIcon', <ChevronRightIcon variant="md" />],
  ['ChevronUpIcon', <ChevronUpIcon variant="md" />],
  ['CircleCheckIcon', <CircleCheckIcon variant="md" />],
  ['ClockTimeIcon', <ClockTimeIcon variant="md" />],
  ['CloseIcon', <CloseIcon variant="md" />],
  ['CloudIcon', <CloudIcon variant="md" />],
  ['CloudNoConnectionIcon', <CloudNoConnectionIcon variant="md" />],
  ['ColumnsIcon', <ColumnsIcon variant="md" />],
  ['CopyIcon', <CopyIcon variant="md" />],
  ['DeleteIcon', <DeleteIcon variant="md" />],
  ['DeskIcon', <DeskIcon variant="md" />],
  ['DoorRoomIcon', <DoorRoomIcon variant="md" />],
  ['DownloadIcon', <DownloadIcon variant="md" />],
  ['EditIcon', <EditIcon variant="md" />],
  ['EmailIcon', <EmailIcon variant="md" />],
  ['ErrorCircleIcon', <ErrorCircleIcon variant="md" />],
  ['ExportIcon', <ExportIcon variant="md" />],
  ['ExternalLinkIcon', <ExternalLinkIcon variant="md" />],
  ['EyeIcon', <EyeIcon variant="md" />],
  ['EyeOffIcon', <EyeOffIcon variant="md" />],
  ['FileReportIcon', <FileReportIcon variant="md" />],
  ['FileTypeLogIcon', <FileTypeLogIcon variant="md" />],
  ['FilterIcon', <FilterIcon variant="md" />],
  ['FirmwareUpdateIcon', <FirmwareUpdateIcon variant="md" />],
  ['FloorPlanIcon', <FloorPlanIcon variant="md" />],
  ['InfoCircleIcon', <InfoCircleIcon variant="md" />],
  ['LicencesIcon', <LicencesIcon variant="md" />],
  ['LinkIcon', <LinkIcon variant="md" />],
  ['LinkOffIcon', <LinkOffIcon variant="md" />],
  ['ListIcon', <ListIcon variant="md" />],
  ['LockIcon', <LockIcon variant="md" />],
  ['LoginIcon', <LoginIcon variant="md" />],
  ['LogoutIcon', <LogoutIcon variant="md" />],
  ['MapSiteIcon', <MapSiteIcon variant="md" />],
  ['MapZoomIcon', <MapZoomIcon variant="md" />],
  ['MicrophoneIcon', <MicrophoneIcon variant="md" />],
  ['MinusIcon', <MinusIcon variant="md" />],
  ['MsTeamsIcon', <MsTeamsIcon variant="md" />],
  ['ParkingAltIcon', <ParkingAltIcon variant="md" />],
  ['ParkingIcon', <ParkingIcon variant="md" />],
  ['PauseIcon', <PauseIcon variant="md" />],
  ['PersonIcon', <PersonIcon variant="md" />],
  ['PhotoIcon', <PhotoIcon variant="md" />],
  ['PinLocationIcon', <PinLocationIcon variant="md" />],
  ['PlaybackSpeedIcon', <PlaybackSpeedIcon variant="md" />],
  ['RefreshIcon', <RefreshIcon variant="md" />],
  ['RocketLaunchIcon', <RocketLaunchIcon variant="md" />],
  ['SearchIcon', <SearchIcon variant="md" />],
  ['SettingsIcon', <SettingsIcon variant="md" />],
  ['ShareIcon', <ShareIcon variant="md" />],
  ['SourceIcon', <SourceIcon variant="md" />],
  ['SpeakerFilledIcon', <SpeakerFilledIcon variant="md" />],
  ['SpeakerIcon', <SpeakerIcon variant="md" />],
  [
    'SpeakerMinimumVolumeFilledIcon',
    <SpeakerMinimumVolumeFilledIcon variant="md" />,
  ],
  ['SpeakerOffFilledIcon', <SpeakerOffFilledIcon variant="md" />],
  ['SquareRoundedPlusIcon', <SquareRoundedPlusIcon variant="md" />],
  ['StopIcon', <StopIcon variant="md" />],
  ['UploadIcon', <UploadIcon variant="md" />],
  ['UsersPlusSigninIcon', <UsersPlusSigninIcon variant="md" />],
  ['WarningTriangleIcon', <WarningTriangleIcon variant="md" />],
  ['WifiIcon', <WifiIcon variant="md" />],
];

const lgIcons: IconEntry[] = [
  // single-size
  ['ComputerIcon', <ComputerIcon />],
  ['ConditionerIcon', <ConditionerIcon />],
  // multisize
  ['FilterIcon', <FilterIcon variant="lg" />],
  ['LightsIcon', <LightsIcon variant="lg" />],
  ['PersonIcon', <PersonIcon variant="lg" />],
  ['PhoneIcon', <PhoneIcon variant="lg" />],
  ['ProjectorIcon', <ProjectorIcon variant="lg" />],
  ['VideoConferenceIcon', <VideoConferenceIcon variant="lg" />],
  ['WhiteboardIcon', <WhiteboardIcon variant="lg" />],
  ['WifiIcon', <WifiIcon variant="lg" />],
];

const xlIcons: IconEntry[] = [
  // multisize only
  ['ArrowDownIcon', <ArrowDownIcon variant="xl" />],
  ['ArrowLeftIcon', <ArrowLeftIcon variant="xl" />],
  ['ArrowRightIcon', <ArrowRightIcon variant="xl" />],
  ['ArrowUpIcon', <ArrowUpIcon variant="xl" />],
];

const xxlIcons: IconEntry[] = [
  // single-size
  ['FileDesignIcon', <FileDesignIcon />],
  ['FocusModeIcon', <FocusModeIcon />],
  ['NoCardIcon', <NoCardIcon />],
  ['NoResultsIcon', <NoResultsIcon />],
  ['ServiceNotReachableIcon', <ServiceNotReachableIcon />],
  ['TeamMeetingIcon', <TeamMeetingIcon />],
  ['WorkshopIcon', <WorkshopIcon />],
  // multisize
  ['CloudNoConnectionIcon', <CloudNoConnectionIcon variant="xxl" />],
  ['DeskIcon', <DeskIcon variant="xxl" />],
  ['ParkingIcon', <ParkingIcon variant="xxl" />],
  ['RoomIcon', <RoomIcon variant="xxl" />],
  ['VideoConferenceIcon', <VideoConferenceIcon variant="xxl" />],
  ['WarningTriangleIcon', <WarningTriangleIcon variant="xxl" />],
];

const xxxlIcons: IconEntry[] = [
  // single-size
  ['GlobeIcon', <GlobeIcon />],
  ['RoomHubIcon', <RoomHubIcon />],
  ['TouchDisplayIcon', <TouchDisplayIcon />],
  ['WifiEnlargedIcon', <WifiEnlargedIcon />],
];

const rootIcons: IconEntry[] = [
  ['BiampLaunchIcon', <BiampLaunchIcon />],
  ['BiampLogoIcon', <BiampLogoIcon />],
  ['ErrorStatusIcon', <ErrorStatusIcon />],
  ['InfoStatusIcon', <InfoStatusIcon />],
  ['KeyArrowDownIcon', <KeyArrowDownIcon />],
  ['KeyArrowUpIcon', <KeyArrowUpIcon />],
  ['RadioCheckedIcon', <RadioCheckedIcon />],
  ['RadioUncheckedIcon', <RadioUncheckedIcon />],
  ['SuccessStatusIcon', <SuccessStatusIcon />],
  ['WarningStatusIcon', <WarningStatusIcon />],
];

const groups: { title: string; icons: IconEntry[] }[] = [
  { title: 'xxxxs', icons: xxxxsIcons },
  { title: 'xxxs', icons: xxxsIcons },
  { title: 'xxs', icons: xxsIcons },
  { title: 'xs', icons: xsIcons },
  { title: 'sm', icons: smIcons },
  { title: 'md', icons: mdIcons },
  { title: 'lg', icons: lgIcons },
  { title: 'xl', icons: xlIcons },
  { title: 'xxl', icons: xxlIcons },
  { title: 'xxxl', icons: xxxlIcons },
  { title: 'Root / Status', icons: rootIcons },
];

const meta: Meta = {
  title: 'Assets/Icons',
  argTypes: {
    color: {
      control: 'color',
      description: 'Icon color — icons use currentColor so they inherit this.',
    },
  },
};

export default meta;
type Story = StoryObj<{ color: string }>;

export const AllIcons: Story = {
  args: {
    color: '#000000',
  },
  render: ({ color }) => (
    <Stack spacing={4} sx={{ color }}>
      {groups.map((g) => (
        <IconGroup key={g.title} title={g.title} icons={g.icons} />
      ))}
    </Stack>
  ),
};
